### ISSUE TITLE
reverseCountourTest fails in run-tests on python 2.7.13

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#1081]
Since commit https://github.com/fonttools/fonttools/commit/273ff461047e80d75b32bb737b9c865a1a0d2717, when running `sh run-tests -2` on a Linux machine, five test cases in Tests/pen/reverseContourTest.py fail on AssertionErrors. It was working fine before that commit, and it still is working fine when running python3 with `sh run-tests -3`. I’m using Python 2.7.13 on Debian stretch.

**Comment by anthrotype** [comment]
yeah, that was expected. I should have explained it better.

This test is there only for checking that the fonttools ReverseContourPen behaves the same as using ufoLib's ReverseContour*Point*Pen.

It is skipped on the CI, because I deliberately did not configure our test runner to install ufoLib as a test requirement. Let's say the test is optional, as it's not testing a different package' functionality, not fonttools'.

After #1080 (where I fixed the duplicate start point being dropped) the two methods for reversing contours still produce (substantially) the same result, only that when using the ufoLib pens you get an extra lineTo whereas we leave it as implied. But they represent the same contour.

I have now adjusted the expected results for the ufoLib pens test to reflect this with faedfac.
I didn't bother fixing it because I knew they it wouldn't be run by the CI, where we control the test environment.

The reason you caught the failures only in your python2 environment is because in your python3 one you don't have ufoLib installed and the test is skipped. The pens behave the same on both pythons.
