### ISSUE TITLE
[subset] Convenience input arg to list to exclude?

### ISSUE THREAD

**Issue by davelab6** [fonttools/fonttools#1153]
I would like to have a simple/convenient way to input a list of glyphs/characters to drop from the font, and keep everything else. Eg,

      pyftsubset font.ttf --exclude glyph1 glyph2 glyph3 

cc @aaronbell

**Comment by chrissimpkins** [comment]
@davelab6 

I pulled together a [tool that prints requested Unicode code point lists to the standard output stream](https://github.com/source-foundry/unilist).  It supports exclusion of individual code points and code point ranges in your command line request.  You can format this output as a comma-delimited list so that it works on the command line with pyftsubset to define included / excluded glyphs for subset files as you requested above (kinda).  It's a workaround until your ticket is implemented.

It looks like pyftsubset ignores missing glyphs by default so you can request the entire desired code point range for the subset and exclude individual points or across point ranges.  

Here is an example of how it looks with Basic Latin to Latin Ext A sets excluding U+0080-009F with shell command expansion:

```
$ pyftsubset font.ttf --unicodes="$(unilist -c 0020-017F x0080-009F)" [other options]
```

I did a "quick test" of the above with pyftsubset (i.e., manually reviewed ttx dump of the subset file) and it seems to work™ appropriately.

You could also define a subset text file with a dump of these Unicode data and use the `--unicodes-file=` pyftsubset flag if the subset definition is going to stick around and you don't want to include `unilist` as a dependency in builds.

**Comment by arrowtype** [comment]
Just commenting to say that I would love the ability to use an "exclude" argument for pyftsubset!

Example use case that comes up a lot for me:

- Subset one font with a "basic English" character set, e.g. `"U+0020-007F,U+00A9,U+2190-2193,U+2018,U+2019,U+201C,U+201D,U+2022"`
- Make another subset that has everything _but_ the subset put into the first
- Set up CSS with `unicode-range` so that the second font is only loaded if those extended characters are needed

**Comment by felipesanches** [comment]
@arrowtype brought up this issue again on a meeting today. It would be handy to have it fixed soon ;-)

**Comment by behdad** [comment]
Ideally it should be done like:
```
$ pyftsubset --unicodes='*' --unicodes-="U+0020-007F,U+00A9,U+2190-2193,U+2018,U+2019,U+201C,U+201D,U+2022"
```
Note that `-=`. We already use that syntax for all parameters. They just don't know how to subtract from `*`.

To expand that to files, the ugly way would be:
```
$ pyftsubset --unicodes='*' --unicodes-file-=exclusion-file-name
```

Better syntax would be nice.

**Comment by arrowtype** [comment]
Not sure whether this will help anyone, but for now, I am using this script to report which Unicodes are in a font, but not in a given list of Unicodes:

https://github.com/arrowtype/recursive/blob/4679f406f92da80886dab376cf9b7ae6e19fedf8/src/build-scripts/make-release/compute-remaining-unicodes-in-font.py

For example, if you wanted to exclude a basic Latin set from a font, you could do this:

```bash
remainingUnicodes=$(python compute-remaining-unicodes-in-font.py <fontPath> --unicodes "U+0020-0039, U+003A-005A, U+0061-007A, U+2018-201D, U+005B, U+005D")
pyftsubset <fontPath> --unicodes=$remainingUnicodes
```

(I can’t guarantee that it is 100% accurate, but it seems to be working well for me. It would be much nicer to have an “exclude” option officially supported by the subsetter.)

**Comment by bennetfabian** [comment]
Excluding glyphs really sounds like such a crucial feature which wouldn't just be used by a small number of users but would be widely used.
Anyone willing to introduce it into pyftsubset?

**Comment by behdad** [comment]
Any volunteers?

**Comment by behdad** [comment]
This works in `hb-subset`. Closing it as no one is working on fonttools subset right now.
