### ISSUE TITLE
[AAT] Implement atifLib

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1173]
Apple's textual format for describing `morx` tables is called MIF. Described here for example:

http://mirror.informatimago.com/next/developer.apple.com/fonts/FontToolsDocs/Apple%20Font%20Tool%20Suite.pdf

FontForge supports it AFAICT.  An example font is available at http://entiumgay.sourceforge.net/#download

It's also not clear if MIF supports kerning: https://github.com/grzegorzrolek/kif-compiler

**Comment by behdad** [comment]
The mif format looks very similar to mtiLib in terms of its closeness to the binary.

**Comment by behdad** [comment]
@brawer

**Comment by olivierberten** [comment]
That's actually the main reason for my other question ;-) Because MIF is much closer to the binary than the xml is...

That said, afaik there aren't that many MIF files in the wild anyway... Here are the other ones I've found until now:

- https://developer.apple.com/download/more/?q=font
- http://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=Mondulkiri-7.100-developer&filename=Mondulkiri-7.100-developer.zip
- https://www.evertype.com/fonts/nko/
- http://web.archive.org/web/20070704171536/http://web.nickshanks.com/typography/kannada/
- http://web.archive.org/web/20070704171640/http://web.nickshanks.com/typography/telugu/
- https://code.google.com/archive/p/lohit-telugu-for-mac/downloads
- https://sites.google.com/site/macmalayalam/
- https://github.com/otaka-san/sievphou-seksaa
- https://sourceforge.net/projects/roaat-regular/files/AAT%20Features/
- https://code.google.com/archive/p/myanmar3source/downloads
- https://sourceforge.net/projects/freetengwar/files/TengwarFont/
- https://sourceforge.net/projects/unifraktur/files/fonts/ (only the 2010-* have mif file)
- https://github.com/tugstugi/mongolian-script/tree/master/apple/fonts/AAT
- http://www.nbcs.rutgers.edu/~hedrick/typography/aat.html
- http://web.archive.org/web/20110425014357/http://people.ktug.or.kr/~nomos/mine/unbatangmorx.mif.txt
- https://sourceforge.net/p/fontforge/mailman/message/25195599/
- http://muthunedumaran.com/2018/01/22/shaping-tamil-fonts-with-aat-for-macos/
- https://stackoverflow.com/questions/25300798/how-do-i-add-aat-contextual-ligatures-to-ttf-fonts


BTW, FontForge supports some morx features but I don't think FontForge supports MIF itself.

**Comment by anthrotype** [comment]
instead of MIF (morph input files), shouldn't we add support for the Advanced Typography Input Files (ATIF) instead? I think this is the "new" format that's supposed to replace the old mif, kif and jif files?

The "Apple Font Tool Suite.pdf" in the "Documentation" folder of the Apple macOS Font Tools contains a full description of this ATIF file format: https://developer.apple.com/download/more/?=font

**Comment by behdad** [comment]
> instead of MIF (morph input files), shouldn't we add support for the Advanced Typography Input Files (ATIF) instead? I think this is the "new" format that's supposed to replace the old mif, kif and jif files, no?

Correct.

**Comment by behdad** [comment]
@ebramino
