### ISSUE TITLE
[ttc] Number of fonts

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#1181]
https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/sfnt.py#L56

It used to be possible to open a font (single or collection) with SFNTReader with fontNumber = 0 and then test for the existence of the attribute "SFNTReader.numFonts" to find out if it is a collection, and how many fonts are in the collection. The number of fonts is not available anymore. Is there a new way of getting this info?

**Comment by anthrotype** [comment]
you should be able to take the `len()` of a TTCollection object, which has a `fonts` attribute (list of `TTFont`).

The code that used to read the TTC header in SFNTReader was factored out to a separate function `readTTCHeader`. However, this no longer sets attributes on the SFNTReader instance but is returning a new (temporary) `header` namespace.

For woff or vanilla sfnt fonts we do still read the respective header's attributes into the SFNTReader object (i.e. we pass `self` to `sstruct.unpack`). Maybe for consistency with the previous behavior, this `readTTCHeader` function should do the same and set attributes on the SFNTReader object instead of creating a SimpleNamespace and then throw it away. We could either turn this into an instance method, or keep it as a module-level function that takes an additional `object` to read data into and we pass `self` (i.e. the SFNTReader).

@behdad I think we discussed about having a generic opener function that can take a file and return either a TTFont or a TTCollection object?

**Comment by behdad** [comment]
I'd say just copy the number so it behaves like old version.

> @behdad I think we discussed about having a generic opener function that can take a file and return either a TTFont or a TTCollection object?

Yes, volunteers.

**Comment by anthrotype** [comment]
I copied the `numFonts` attribute with e7494cb

I'll open a separate issue for the open function
