### ISSUE TITLE
feature request: add `fonttools diff` to compare fonts with ttx

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1190]
I often find myself using ttx in combination with some diffing tool, so much that I wrote a `ttdiff` shell function that takes two fonts (and optionally a list of table tags), and redirect the output of ttx to `diff` (pipes it to `colordiff` to get nice colors and `less` for pagination): 

https://gist.github.com/anthrotype/6c3dce176314ec6ffb116b0f8561bee0

I guess many of us have their own variant of this. So I wonder, should we add a new sub-command, `fonttools diff` that uses python to do the same, so it works everywhere fonttools work and not just in a unix shell?

I think this is a nice first-time-contributor kind of PR. Any takers?

**Comment by khaledhosny** [comment]
I use `vim -d` instead of `diff`, so if this can allow me to choose the diffing program, that would be super cool :wink:

**Comment by anthrotype** [comment]
I was thinking more about using python own difflib for the diffing instead of an external program, for portability.. But I imagine it's gonna be much slower than the standard diff or vimdiff or similar programs. 
You know, the more I think about it, the more I think it may not be worth it, and a shell snippet just works fine. At least it does for me, as I don't work from a Windows command prompt.
But then sometimes I wish I can tell someone else "compare these fonts" without me having to tell them how to set up their shell, install this or that, and so forth.

**Comment by anthrotype** [comment]
I'm sure someone is thinking, "why just textual diff, we are in python so let's compare the objects themselves and print out differences in a structured way"...
That'd be cool too, but it's a completely different thing and a bit more involved I believe. 

Just for reference, here is module to recursively compare python objects:
https://github.com/seperman/deepdiff
https://pypi.python.org/pypi/deepdiff

**Comment by chrissimpkins** [comment]
Thoughts about a separate, single repository to collect fonttools based scripts (Python, shell, and others) under open licensing?  It would be useful to have a single repository where the scripts could be easily referenced for direct use or modification based upon project-specific needs.  I'm sure that there are many scripts out there that can be generalized and would be extremely helpful to others who share similar needs.

**Comment by anthrotype** [comment]
I feel that's a bit out of scope. (And sorry I'm not volunteering to support another repository).

**Comment by chrissimpkins** [comment]
My point was that there is a significant amount of functionality based on this library out there but not a simple way to identify and learn from it.  This thread is an example of that.  I'm sure that there are many scripts based on fonttools that are sequestered away in subdirectories of repositories or sitting on local boxes that could be very useful to others.  My suggestion is simply for someone/anyone to create an approach that permits others to easily find them.  They already exist and there would be no need to reinvent the wheel for those who have the same needs. They would also serve as targeted documentation of the library around specific 'problems' so that it is easier to modify and extend the source for new issues.  Clearly, I understand the time issue and am not volunteering anyone's time to maintain this, nor do I see it as the library authors' responsibility to invest any time in it.  It's just a suggestion for an approach that could help to reduce the learning curve with fonttools and serve as a broad form of project documentation based upon actual community implementations that are contributed to the repository from the community.  My spin in this pitch is that it actually eliminates documentation work for you :) 

2 cents. It would be useful to me and likely to others to see the trove of scripting that others out there have.

**Comment by justvanrossum** [comment]
We have the `Snippets` folder in the repo. I think Cosimo's shell script could also go there (very cool btw). Why not collect more stuff there? I don't really see the need for a new repo.

**Comment by chrissimpkins** [comment]
That would be fantastic Just.

**Comment by behdad** [comment]
I think a diff module makes sense, and it can be smarter than just plain diff.  But yeah, start it as a Snippet and see where it goes.

**Comment by moyogo** [comment]
We should start installing Snippets.

**Comment by davelab6** [comment]
+1 to filling out /Snippets

**Comment by anthrotype** [comment]
> We should start installing Snippets.

no, otherwise they would not be "Snippets". When something is deemed useful/good enough to be merged as a module in the main Lib, then it will be installed along with it. 

And we don't want to add further console scripts like `pyftsubset`, `pyftmerge`, etc. otherwise we pollute the user's `bin` folder with too many of them. All new future console-script functionalities should be implemented as new sub-commands for the `fonttools` script, the only one that should stay (besides the venerable `ttx` itself).

**Comment by chrissimpkins** [comment]
> We should start installing Snippets.

> When something is deemed useful/good enough to be merged as a module in the main Lib, then it will be installed along with it.

There are priorities at odds here.  I've pitched this elsewhere.  Let's see if there is any traction here.  Is there a way to support an interface spec to out of repo Python source that fonttools will execute in some fashion as subcommand 'extensions'?  This eliminates the need to maintain this extension source for the authors here, makes the installation of the source optional for users so that it does not pollute their `bin` with default fonttools installs, and opens up the possibility for the development of many tools that are designed to a spec defined here, based on the fontools library, and can be installed and used through a fonttools executable?  The onus of testing these projects falls upon whoever develops the tool and the onus of confirming that it is tested and usable falls upon the user who installs the extension.  These would not be fonttools author responsibilities.  fonttools provides a well tested approach to link developers of source that is not of general use and does not meet criteria for inclusion as a default fonttools distributed executable with users who need such tools in select circumstances.  Is something along those lines even possible to implement?

**Comment by behdad** [comment]
> Is there a way to support an interface spec to out of repo Python source that fonttools will execute in some fashion as subcommand 'extensions'?

That was part of what I had in mind for the 'fonttools' command. But I cannot summarize the benefits of such a thing. "python -m" is not that much harder to type.

The `Lib/fontTools/__main__.py` has this:
```
        # TODO Handle library-wide options. Eg.:
        # --unicodedata
        # --verbose / other logging stuff

        # TODO Allow a way to run arbitrary modules? Useful for setting
        # library-wide options and calling another library. Eg.:
        #
        #   $ fonttools --unicodedata=... fontmake ...
        #
        # This allows for a git-like command where thirdparty commands
        # can be added.  Should we just try importing the fonttools
        # module first and try without if it fails?
```

Doing this however then opens up possibility of namespace pollution, where someone else might implement a command extension that we might later want to use, or two people providing the same subcommand...

**Comment by chrissimpkins** [comment]
Could you enforce PyPI packages for the extensions, harness pip for installs/upgrades, and create a common PyPI package naming scheme?  

fonttools-[extensionname]

This gets you unique names for extensions, the ability to define what command name you would use for them (could use a prefix or suffix to avoid conflicts that you would use down the road, e.g., fonttools-coolthing becomes `fonttools ext-coolthing`, and searchable fonttools extension packages through PyPI.   MkDocs does something similar to this with their themes for their Python tool.

**Comment by behdad** [comment]
I'll leave it to Cosimo, others, to figure out.

**Comment by chrissimpkins** [comment]
+1 fonttools diff command.  Sorry for the diversion Cosimo.

**Comment by moyogo** [comment]
>> We should start installing Snippets.

>no, otherwise they would not be "Snippets". 

Sure, then a fonttools diff shouldn’t be in Snippets.

**Comment by typoman** [comment]
I use this to find the differences between the two fonts. It gives me a compact diff for most cases. Not sure if it can be used for fonts that are very different, it's only useful for finding small changes:
```py
from fontTools.ttLib.ttFont import TTFont
from fontTools.misc.testTools import getXML
import difflib

def _truncateDiffLines(lines):
    return [line for line in lines if not line.startswith(" ")]

def fontToolsDiff(f1Path, f2Path):
    f1 = TTFont(f1Path)
    f2 = TTFont(f2Path)
    d = difflib.Differ()
    log = [f"\n{'#'*20}  {'Start of TTX diff'}  {'#'*20}"]
    for tag in f1.keys():
        d1 = getXML(f1[tag].toXML, f1)
        try:
            d2 = getXML(f2[tag].toXML, f2)
        except KeyError:
            log.append(f"table {tag} not found in {f2Path}")
        if d1 != d2:
            log.append(f"{'*'*20}  {tag.upper()}  {'*'*20}")
            diff = d.compare(d1, d2)
            log.append('\n'.join(_truncateDiffLines(diff)))
    log.append(f"{'#'*20}  {'End of TTX diff'}  {'#'*20}\n\n")
    return '\n'.join(log)
```

**Comment by justvanrossum** [comment]
In the meantime https://pypi.org/project/fdiff/ was made by @chrissimpkins, it's awesome!

**Comment by chrissimpkins** [comment]
> In the meantime https://pypi.org/project/fdiff/ was made by @chrissimpkins, it's awesome!

Happy to fold all/some of this functionality into fonttools if it is desirable here.

**Comment by behdad** [comment]
fdiff seems to do this perfectly fine. So it's either:

- Close this as not planned, (preferred)
- Import fdiff verbatim, (no reason really)
- Make "fonttools diff" invoke fdiff (redundant)
- Make fdiff provide module fonttools_diff, and make fonttools cmdline find fonttools_* when invoked with "fonttools *" (might be security risk).

**Comment by behdad** [comment]
I'm tempted to adopt `fdiff` as `fonttools diff`. If we do, we should default to the external `diff` command instead of Python `difflib`. The latter is way too slow for large files / diffs.

**Comment by justvanrossum** [comment]
FWIW, at some point I wrote `fbdiff`, to get a superquick overview of which tables are different. That can save a lot of time as it doesn't require dumping to xml. Feel free to grab that, too, if people find it useful. https://github.com/justvanrossum/fbdiff.

**Comment by anthrotype** [comment]
> I'm tempted to adopt fdiff

+1 (Chris said he'd be "happy to fold") 

> If we do, we should default to the external diff command

we should let it be configurable, not sure if fdiff already supports that

**Comment by anthrotype** [comment]
>  at some point I wrote fbdiff

we could have both :)

**Comment by justvanrossum** [comment]
`fbdiff`s behavior could be behind an option in the main diff tool.

**Comment by behdad** [comment]
`fdiff` as it is requires the following extra packages: `rich`, `aiohttp`, `aiofiles`.  The aio ones probably can be made optional. Rich maybe also.

**Comment by behdad** [comment]
> `fdiff` as it is requires the following extra packages: `rich`, `aiohttp`, `aiofiles`. The aio ones probably can be made optional. Rich maybe also.

I also want to, if easy, make it run `less -R` on the output by default if it's to the console, like `git diff` does. Thoughts?

**Comment by anthrotype** [comment]
yeah you can check `if sys.stdout.isatty()`

**Comment by behdad** [comment]
Is there interest in keeping the following options, or drop them?
```
  --head HEAD          Display first n lines of output
  --tail TAIL          Display last n lines of output
```

Also, maybe:
```
  --nomp               Do not use multi process optimizations (default: on)
```
we'd just use MP if available.

And as I said, I'll make the default to use external diff which is much faster.

**Comment by behdad** [comment]
I made `aiohttp` optional. The rest I think we should leave as is. The full list is rather long. Comments?

https://github.com/source-foundry/fdiff/blob/master/requirements.txt

**Comment by justvanrossum** [comment]
Maybe consider dropping the remote support altogether?

**Comment by behdad** [comment]
> Maybe consider dropping the remote support altogether?

I'm fine with that, though font engineers might find it useful comparing to their github fonts. You're right that a good chunk of deps are because of the remote, but seems like all are pulled by aiohttp, which I already made optional.

I'll clean up and merge into a fonttools PR and submit for review, then we can decide.

**Comment by behdad** [comment]
I'm working on it in https://github.com/behdad/fdiff

I made all dependencies optional.

**Comment by behdad** [comment]
Here's a roadmap of what I suggest as the next steps:

- [x] Do the git surgery to integrate my tree into a fonttools PR,
- [ ] Make the external diff the default. It requires running `diff -u` and detect failure and fallback to diffLib,
- [ ] Currently the whole thing is too slow. I think the following logic should work: if GlyphOrder of the two fonts is the same, just compare each table's binary and dump to XML  and diff only those tables that are different...
- [ ] Add `--summary` to just list tables that are different, ala `fbdiff` https://github.com/justvanrossum/fbdiff
- [ ] At that point, remove the `rich` dependency, which is just used to show a "Processing..." progress bar.
- [ ] Implement the `less -R`.

**Comment by behdad** [comment]
Following up in PR https://github.com/fonttools/fonttools/pull/4007

**Comment by behdad** [comment]
Merged. Yoohoo. To the memory of @chrissimpkins who wrote `fdiff`.

**Comment by anthrotype** [comment]
Thanks Behdad!
