### ISSUE TITLE
[ttx] AssertionError while decompiling gvar table

### ISSUE THREAD

**Issue by BoldMonday** [fonttools/fonttools#1306]
The following AssertionError occurred when using ttx to dump a variable font hinted in VTT:
```
ERROR: An exception occurred during the decompilation of the 'gvar' table
Traceback (most recent call last):
  File "/code/fonttools/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 385, in __getitem__
    table.decompile(data, self)
  File "/code/fonttools/lib/python2.7/site-packages/fontTools/ttLib/tables/_g_v_a_r.py", line 111, in decompile
    numPointsInGlyph, sharedCoords, axisTags, gvarData)
  File "/code/fonttools/lib/python2.7/site-packages/fontTools/ttLib/tables/_g_v_a_r.py", line 229, in decompileGlyph_
    sharedTuples, data, 4, offsetToData)
  File "/code/fonttools/lib/python2.7/site-packages/fontTools/ttLib/tables/TupleVariation.py", line 555, in decompileTupleVariationStore
    tableTag, axisTags, tupleData, pointDeltaData))
  File "/code/fonttools/lib/python2.7/site-packages/fontTools/ttLib/tables/TupleVariation.py", line 598, in decompileTupleVariation_
    len(points), tupleData, pos)
  File "/code/fonttools/lib/python2.7/site-packages/fontTools/ttLib/tables/TupleVariation.py", line 433, in decompileDeltas_
    assert len(result) == numDeltas
AssertionError
Dumping 'gvar' table...
```
I'm happy to supply a copy of the font file in question if necessary.

**Comment by anthrotype** [comment]
That would be great. Please sent it to my cosimo (at) anthrotype.com email, thanks

**Comment by anthrotype** [comment]
Interesting. The assertion error is raised while decompiling the gvar deltas for two empty space glyphs, uni0020 and uni00A0, only varying horizontally along the width axis.

Looking at the glyf table of the font before and after passing through VTT, I noticed that a new contour point (0, 0) is being added by VTT to those two empty glyphs, whereas they previously contained no outline data.
If I dump the gvar table as binary data before and after VTT, and I diff the results, they are identical, meaning that VTT didn't change the gvar table. I did change the glyf table though, by adding the hinting instructions and that (0, 0) point to the space glyphs. 

In the function that decompiles the gvar TupleVariationStore we need to pass the total number of points for each glyph, which is the 4 phantom points + the number of contour points (or + the number of components for composite glyphs). In the case of uni0020 and uni00A0, this count is 5 instead of 4 after VTT has added the extra point. Because of this, the decompileDeltas_ function is attempting to decompile more deltas than required and thus the assertion error is raised correctly.

The fonttools code is correct. VTT should either not add the extra point to the empty glyphs, or if it does need to do that for its own thing, it needs to recompile the gvar table to take into account the additional points, otherwise it is no longer is sync with the modified glyf table.

I'm going to close the issue as there is nothing fonttools can do with such broken fonts. Please send the bug report to someone at Microsoft.

**Comment by BoldMonday** [comment]
Thank you very much for the detailed report @anthrotype. I will pass this on to Mike Duggan.
