### ISSUE TITLE
[ufolib] Allow UFOZ only for UFO3

### ISSUE THREAD

**Issue by benkiel** [fonttools/fonttools#1364]
To aid tools and provide a clean break, we should only allow UFOZ for UFO3 and on. This should have come up in the UFOLib work, but it was an assumption that was held but not expressed, as this is an addition originally planned for UFO4 (ish).

**Comment by benkiel** [comment]
To further clarify "clean break" — yes, there isn't a technical reason that UFOZ couldn't apply to UFO1/2, but two things:

1. This is an addition, and only needing to assume that UFOZ == UFO3+ is nice
2. Because UFO2 was much more lax about data types, ingesting a UFO2 into a UFO3 application means some background cleanup needs to happen, which is best done by reading parts of a UFO, but one can't do that with a UFOZ (well, easily), so it would be nicer to tool makers if we just made it explicit.

Apologies for not thinking this through in ufoLib before the merge.

**Comment by justvanrossum** [comment]
I'm not sure I agree. Your #2 raises the question: if such cleanup is needed _before_ data is sent to ufoLib, doesn't this suggest a weakness in ufoLib?

The vfb2ufo tool has been capable of writing UFO2+zip as .ufoz since (at least) 2015. And my shallow experiments show that these are just perfectly readable with fontTools.ufoLib. I'm not saying this is an important use case -- not at all even -- but it already works, and I don't really see a reason to prevent this from working.

**Comment by anthrotype** [comment]
> it already works, and I don't really see a reason to prevent this from working.

Which was the reason why I didn’t put that version >= 3 check.
But if you prefer to restrict to UFO3 and above I don’t mind.

**Comment by khaledhosny** [comment]
Closing per comments above.
