### ISSUE TITLE
Upload recent fonttools to pypi repository

### ISSUE THREAD

**Issue by vitalyvolkov** [fonttools/fonttools#140]
At the moment If user want to use fonttools from setup.py scripts he needs to define in dependency_links external url to github. That argument is deprecated and using it is a bad practice. 

It will be good if fontTools will be up-to-date in pypi repo https://pypi.python.org/pypi/FontTools

Note that there are 2.4 version but I suggest to increase it to 2.5 :)

Cheers

**Comment by aginiewicz** [comment]
I would also like to know when it will be available at PyPi - also, is 2.5 first release with python3 support, or it isn't there yet? I wasn't able to find anything about 2.5 in changelog - and going trough list of commits would take a lot of time.

(disclaimer: I would like to review those information, especially the most important changes to see if and how I should update the https://www.archlinux.org/packages/community/x86_64/python2-fonttools/, thanks)

**Comment by behdad** [comment]
Yes, 2.5 supports Python 3.

**Comment by pettarin** [comment]
@behdad Thank you for your awesome work on this project!

@behdad @davelab6 : I just want to bump this issue up, as having it on PyPI would make life easier to a lot of people. [Full disclosure: including a project of mine ( https://github.com/pettarin/glyphIgo ) where I would like to use fonttools lib (`subset.py` in particular) instead of fontforge lib.]

**Comment by behdad** [comment]
Do we have anyone volunteering to maintain PyPI entry?  What do I need to do?

**Comment by pettarin** [comment]
The PyPI page https://pypi.python.org/pypi/FontTools lists users `just`, `xen`, `pabs`, `davelab6` as Owners of the package. Assuming you want to keep releasing with the `FontTools` PyPI package name, they, and only they, can upload a new release of `FontTools` to PyPI.

Since there is a `setup.py` file in this repo root directory already, to upload a release as a new PyPI package release one of the PyPI package Owners (or Maintainers) just has to run:

`$ python setup.py sdist upload -r pypi`

(I am not a PyPI expert, I see the `setup.py` file has been recently modified by @anthrotype , so I guess it should be working properly with the above command.)

If you (behdad) plan to keep working on this repo, it would make sense if you become a PyPI package Owner (or Maintainer) and then run the above command every time you want to upload a new release. In such a case, you must:

1. register a personal PyPI account ( https://pypi.python.org/pypi?:action=register_form );
2. ask the package Admin (Just van Rossum) to give your account the Owner (or Maintainer) role for `FontTools`.

**Comment by davelab6** [comment]
Just let me know the usernames to add as owners and I'll add you

**Comment by isnowfy** [comment]
just run `python setup.py sdist upload`

**Comment by behdad** [comment]
@davelab6 Can you please be responsible for pypi of fonttools?  I can tag releases as you request, but don't have time to do anything else about this.

**Comment by davelab6** [comment]
Okay, sure :) https://pypi.python.org/pypi/FontTools now has the v2.5

**Comment by anthrotype** [comment]
the latest tagged 2.5 release is from Sep 24, 2014. It would be nice to tag a new one since we are at it.

**Comment by behdad** [comment]
Ok, how about we land woff2 work, let things stablize a bit, and aim for new release (call it 3.0?) around the end of the month?

**Comment by davelab6** [comment]
Sounds good. It was straightforward; I needed to create a few (empty) hook files in `.git` that setup.py required, and a `~/.pypirc` containing

```
[distutils]
index-servers=pypi

[pypi]
repository = https://pypi.python.org/pypi
username = davelab6
password = ahem

[server-login]
username = davelab6
password = ahem
```

Then with them in place, I just ran 

    python setup.py sdist register upload

and it appears to work.

**Comment by behdad** [comment]
Just send a pull-request if there's any of that that should go upstream.

**Comment by pettarin** [comment]
I just want to thank you all for this awesome project and for making it available via PyPI!

**Comment by davelab6** [comment]
> Just send a pull-request if there's any of that that should go upstream.

Yes, I thought to do that when I made the pypi push, but git doesn't see any of those files I made, only something that seems like it will be regenerated:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Lib/fonttools.egg-info/

nothing added to commit but untracked files present (use "git add" to track)
$
```

**Comment by anthrotype** [comment]
@davelab6 what are these "hook files in .git that setup.py required"? And why exactly are they required?

**Comment by davelab6** [comment]
To create them, I ran
```
cd ~/src/github.com/behdad/fonttools/.git;
touch .git/description;
touch .git/info/exclude;
touch .git/hooks/applypatch-msg.sample;
touch .git/hooks/commit-msg.sample;
touch .git/hooks/post-update.sample;
touch .git/hooks/pre-applypatch.sample;
touch .git/hooks/pre-commit.sample;
touch .git/hooks/pre-push.sample;
touch .git/hooks/pre-rebase.sample;
touch .git/hooks/prepare-commit-msg.sample;
touch .git/hooks/update.sample;
```

Thus:

```
tree;
.
├── COMMIT_EDITMSG
├── FETCH_HEAD
├── HEAD
├── ORIG_HEAD
├── config
├── description
├── hooks
│   ├── applypatch-msg.sample
│   ├── commit-msg.sample
│   ├── post-update.sample
│   ├── pre-applypatch.sample
│   ├── pre-commit.sample
│   ├── pre-push.sample
│   ├── pre-rebase.sample
│   ├── prepare-commit-msg.sample
│   └── update.sample
├── index
├── info
├── logs
├── objects
├── packed-refs
└── refs

**Comment by anthrotype** [comment]
I know what's inside the .git folder, I was simply asking what does it have to do with uploading the package to pypi.

**Comment by davelab6** [comment]
I have no idea why `python setup.py sdist register upload` required the files :)

**Comment by behdad** [comment]
The .sample files definitely don't make any sense.

**Comment by davelab6** [comment]
> how about we land woff2 work, let things stablize a bit, and aim for new release (call it 3.0?) around the end of the month?

Have things stabilised? :)

**Comment by behdad** [comment]
Yes.  Ready to tag 3.0?!

**Comment by davelab6** [comment]
Ready when you are boss! :)

**Comment by behdad** [comment]
https://github.com/behdad/fonttools/releases/tag/3.0

I wonder if we should add a NEWS file as well.

**Comment by davelab6** [comment]
I made a note to upload v3.0 to pypi after the dust settled; nothing came up, so I've now pushed the 3.0 version just now

**Comment by behdad** [comment]
Is this fixed now?

**Comment by behdad** [comment]
I believe so.
