### ISSUE TITLE
"Supersplit" mode to split _g_l_y_f.ttx files into 1-file-per-TTGlyph?

### ISSUE THREAD

**Issue by davelab6** [fonttools/fonttools#153]
The 'split' mode of TTX, with one table per file, is useful for version control systems, and where a single TTX file can be megabytes of text. 

However, the `Font._g_l_y_f.ttx` file can still be huge. 

In contrast, the `UFO` and `SFDir` formats have one file per glyph.

So I suggest a 'supersplit' mode where there is one `<TTGlyph>` element per file. 

The files could be named in part with the [UFOv3 glyphname-to-filename convention](http://unifiedfontobject.org/versions/ufo3/conventions/#common-user-name-to-file-name-algorithm), eg, `Font._g_l_y_f.A_.ttx`

**Comment by RoelN** [comment]
Bumping this.

In the mean time, what is the way to extract PNG images from am sbix table? I can iterate over the strikes (`for strike in font['sbix'].strikes:`) but I'm a bit clueless on how to proceed.

What's the best way to find out these things without asking? There aren't any "let play with the sbix table" docs out there for TTX/FontTools, right?

**Comment by Jolg42** [comment]
@RoelN I did that not so long ago, here is the script https://gist.github.com/Jolg42/f22676fdfba6dbfe4589aa30f0326fb4

**Comment by anthrotype** [comment]
@RoelN I'm afraid we don't have much documentation for the library modules yet, but feel free to ask anytime!

The `ttx` command has `-z` option to specify "a bitmap data export option for `EBDT`" (and `CBDT`), so one can pass `-z extfile` and save the bitmaps to external files.
However, this doesn't work with `sbix` table yet.

If somebody wants to give it a try, it'd be glad to review a PR.

**Comment by RoelN** [comment]
@Jolg42 Fantastic, thanks! That's very helpful.

@anthrotype Thanks for the invitation to ask. I'll play around with @Jolg42's script and hope to make some time for a PR in the near future!

**Comment by anthrotype** [comment]
I guess a script like @Jolg42's could be added to the fonttools/Snippets folder, if you like. I see it's using python2-only idioms, so one should make it py2.py3 compatible first. PR anyone?

**Comment by Jolg42** [comment]
@RoelN You're welcome!
@anthrotype 👍 No problem with that, but I am not an expert in Python so I can't help for making it compatible...

**Comment by RoelN** [comment]
I don't mind giving that a shot. I also have some other small example scripts I could dust off!

**Comment by anthrotype** [comment]
https://github.com/bamidei/fonttools/blob/feb4c0d2ed67dc714d42a8d4dece5d0ab019eed9/Lib/fontTools/ttLib/__init__.py#L303-L316

@bamidei I noticed a strange thing with this `tablePath` variable. You set it to a string if either ``splitTables or (splitGlyphs and tag == `glyf`)``, however you only actually make use of this `if splitTables`, otherwise in the splitGlyphs case you throw it away.

This also means that when one passes -g option to ttx, _without_ also passing -s option, then the split-glyphs ttx files will not also contain the tag `_g_l_y_f` in their filenames, but they will just be a concatenation of font name + glyph name. I find this a bit weird. 

What do you think if we were to make splitTables implicitly True whenever splitGlyphs is also True?

I mean, glyphs are usually in the hundreds, unlike tables which are a few compared to the latter.
If one is willing to get so many split-glyphs ttx files, they may likely also be ok with having each tables split in its own file; it's just going to be a few additional files.

This way we would fix the above mentioned inconsistency and the split-glyphs ttx filenames will always contain the font name + the parent table tag (_g_l_y_f) + the glyph name itself.

**Comment by bamidei** [comment]
I agree with your thoughts here.  I have only used split glyphs together
with split tables and it is reasonable to think that others would also use
the feature in this way.  Making the update that you suggest will fix the
strangeness you mention if they are not used together.

Please let me know if you'd like me to make a new PR with this suggested
change.

Thanks,
 Bill

**Comment by anthrotype** [comment]
@bamidei any news?

**Comment by bamidei** [comment]
@anthrotype I've been occupied with a few other urgent things.  I'll have some time in the coming weeks where can do this.  I was also thinking about changing the glyph file names at the same time.  Are you familiar with licensing terms for the Robofab library?  Their default algorithm for glyf filenames is here: http://nullege.com/codes/search/robofab.tools.glyphNameSchemes.glyphNameToShortFileName

It wouldn't be difficult to port this into the glyf table implementation which we have if the licensing isn't prohibitive.  Please LMK.

**Comment by miguelsousa** [comment]
@bamidei don't use that algorithm; it's not robust enough. Use UFO 3's instead https://github.com/unified-font-object/ufoNormalizer/blob/master/src/ufonormalizer.py#L1590

**Comment by anthrotype** [comment]
@bamidei I had to revert your patch because I needed to cut a release today and didn't want to ship something incomplete that required changes.
I have moved your code to a separate branch on the upstream fonttools repo, called "split-glyphs"
https://github.com/fonttools/fonttools/tree/split-glyphs

You can rebase your work on that branch and send new PRs targeting that instead of master branch (which now no longer contains that code). Take your time, I have no rush to implement this. Thanks

**Comment by bamidei** [comment]
@anthrotype Cool.  Thank you for allowing me the time to make these changes - I apologize i wasn't able to get to this quicker as I've been working to wrap up a few other things before end of year.

I did now get the opportunity to make the update and you can see the new PR against the branch you've created here: https://github.com/fonttools/fonttools/pull/1132

Thanks again - and Happy Holidays!
  Bill
