### ISSUE TITLE
[varLib.mutator] Support partial VF instances

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1537]
The current fontTools.varlib.mutator module can fully instantiate a variable font into a static font at a given location along all the axes.

The Google Fonts team is interested in adding support for generating "partial" instances: i.e one wants to keep `wght` axis but pin the `wdth` axis to a specific location, either the default or a custom one,  dropping all the variation data relating to the pinned axes.
Or alternatively one may want to restrict the range (min and/or max) of an axis, producing a new VF with possibly smaller file size.

We have created a new branch `partial-instancer` in here where we pushed a new module called `fontTools.varLib.partialInstancer` (the name may change, I'm thinking just "instancer" sounds better). It's is based on the mutator module and has a similar interface. When it's complete, potentially it could subsume the functionality of mutator, since the partial instancing can be seen as a more general problem.

The module is still in early stages and can currently only pin-and-drop gvar variation data. Limiting axis ranges is not supported either. We shall probably focus on implementing the axis dropping and pinning first for the rest of the variation tables, as that appear to be a relatively easier problem than limiting ranges, and one that guarantees some size reduction.

Feel free to chime in with suggestions or comments. I'll keep you updated with the progress.

**Comment by behdad** [comment]
I suggest we break this operation down to separate operations that can be chained together.  That way the code would be much easier to reason about.  I suggest implementing the following:

- Dropping an entire axis.  This is simplest: any deltaset that has a non-zero peak for the said axis is just dropped completely.

- Instantiating an axis to a particular value.  The previous operation is a special-case of this one.  In this operation, any deltaset that interacts with the axis will get its deltas multiplied by the scalar support of the axis at the desired instantiation point for the deltaset's tent.  If the scalar is 0, drop the deltaset.  If it's 1, leave as is, otherwise multiply the values by it.

- Limit min/max of an axis.  For each deltaset that participates in the axis, if the deltaset's tent is fully outside new min/max of axis, drop it.  If the tent is fully inside the new range, keep it (just scale the tent min/peak/max to the new normalized axis).  If the tent overlaps but also extends beyond new min/max, it becomes interesting.  I'll address that separately in the following comment.

- Move the base location.  This is harder in the general case and to be done later, separately, if ever.

**Comment by behdad** [comment]
Imagine we want to change maximum of 'axis' from 1.0 (normalized, always 1.0) to X.  Now imagine we have a deltaset with min/peak/max of A<B<C such that A<=X<C.  Then do the following:

Divide A,B,C by X to get new normalized values.  We now expect that A<=1.0<C.  Now, two cases:

- if the peak falls outside:  Ie. 1.0<B.  Then scale deltaset by (1-A)/(B-A) and then set B and C to 1.0.

- if the peak falls inside: If C <= 2.0, keep everything.  The format allows for encoding coordinate values in the [-2,+2) range.  +2 is not supported but we can store +1.9999999 instead of it.  So, just keep the tent as is, extending beyond the axis maximum.

- if the peak falls inside and C > 2, we need to chop the tent overlap shape into two deltas, because the shape of a triangle with part of one side cut off cannot be represented as a triangle itself.  It can be represented as sum of two triangles.  This increases font file but is doable.

**Comment by anthrotype** [comment]
Thanks Behdad.

About 2. "Instantiating an axis at a particular value", besides multiplying the deltas by the scalar support of the pinned axis at the desired instantiation point (and remove the pinned axis ie. set its peak to 0 for a that region); when a region's axes only contain the axis we want to pin, then we also need to apply (add) these scaled deltas to the default tables so that their contribution is reflected in the default instance after the pinned axis is removed from the font. Because I think you can't have a region where all axes at 0 peak (i.e. where deltas are "always on"). I actually tried that, and got weird results across implementations.
Does that make sense to you?

**Comment by behdad** [comment]
You are right.

Re 0 peak, they disable the axis indeed.  At design time we thought we made sure that at axis default locations, the contribution of all deltas is zero and as a result / design goal, the base instance is the same as the base font without variation tables.  HarfBuzz for example, short-circuits and avoid delta calculations if all axes are default.  However, as we discovered later (and you also did), if a deltaset has no participating axis, it should always be enabled.  That's something we did not consider, and is not widely tested currently.

**Comment by behdad** [comment]
So yeah.  If after removing some axes, no axis is left in the delta, it should be folded into the neutral.

**Comment by anthrotype** [comment]
After removing some axis in the partial instancing, there may be many regions whose "tents" are now exactly overlapping. For example, say we have two regions `{"wght": (0, 1, 1)}` and `{"wght": (0, 1, 1), "wdth": (0, 1, 1)}`, and we remove the 'wdth' axis; we are then left with two regions with exactly the same axis support (in this case `{"wght": (0, 1, 1)}`).
Naturally one would like to sum the deltas from such overlapping regions and only keep a single merged region.
However, in gvar's TupleVariation there can be inferred points (i.e. IUP deltas) therefore I cannot simply add potentially `None` deltas with the ones from another overlapping tuple; I first have to interpolate the inferred points (run the `iup_delta` function), sum the deltas from the overlapping tuples, finally re-run `iup_delta_optimize` on the merged tuple.

I wonder if there's a better solution?

I run some tests with and without merging these overlapping tuples after partial-instancing.
For example, these are the `gvar` table sizes of NotoSans-VF.ttf (that has both weight/width axes), partially instantiated at `wght=300`, when the resulting overlapping tuples are:

1) not merged: __284726__ bytes
2) merged, not re-optimized: __172384__ bytes
3) merged, re-optimized: __171222__ bytes

The IUP delta optimization seems to make less of a difference than the merging of the overlapping tuples.

**Comment by behdad** [comment]
Since you already have code for it, do the whole thing?  Maybe only re-optimize if the originals had any None in them?  Ie. don't IUP-optimize if the original was (on purpose) not IUP-optimized.

**Comment by anthrotype** [comment]
Sgtm

**Comment by anthrotype** [comment]
i'm leaning towards have an option to re-optimize.
Simply checking in any None is in the deltas for a specific tuple in a specific glyph doesn't communicate well 'purpose' to me. Couldn't it be that for that specific tuple (before merging with overlapping tuples) it was more efficient to not do the IUP_delta but then after merging IUP_delta would be more efficient?

**Comment by behdad** [comment]
In theory yes. But as you need the IUP optimization is tiny anyway. I'm thinking about fonts made with IUP disabled. Didn't you add an option to fontmake for that?

**Comment by twardoch** [comment]
I have a feelong that it somehow is related to https://github.com/fonttools/fonttools/issues/1570

**Comment by anthrotype** [comment]
The first batch of partial-instancer is merged into master (#1628), supports levels 1 and 2 only. Level 3 is planned later for Q3.

(for the 'level' definitons see https://github.com/fonttools/fonttools/issues/1537#issuecomment-474983825)

**Comment by anthrotype** [comment]
We can close this now that #1753 got merged. Perhaps we can open a separate issue for the level-4 (i.e. moving the default location) instancing.

**Comment by samboy** [comment]
Thanks for this. Here’s how I have made an instance of Bitter variable (available at https://fonts.google.com/specimen/Bitter )

```bash
fonttools varLib.instancer Bitter-VariableFont_wght.ttf wght=450
```

I then moved the created `Bitter-VariableFont_wght-instance.ttf` to `Bitter-450.ttf`

**Comment by Mark2Mark** [comment]
Chiming in here to ask if there’s already something in the pipe for Level 4 "Moving the default location"?

Not sure if it should try to find the location within the subset, closest to the original input default location. Or if it maybe rather just a need user parameter to determine where the new default should go. Or a combination of both.

**Comment by behdad** [comment]
> it should try to find the location within the subset, closest to the original input default location.

By default it should do that, yes.

**Comment by anthrotype** [comment]
We haven't implemented Level 4 "Moving the default location" yet.
I don't understand what you mean by "it should try to find the location within the subset, closest to the original input default location".

Right now the instancer input is a dictionary keyed by axis tags and containing either single values or a (min, max) tuple for an axis range. I imagine in the future it could take a 3-tuple that also specifies a new default, i.e. (min, default, max).

**Comment by Mark2Mark** [comment]
To specify, I meant, if you subset a variable font that has 2 axes originally, but the subset will only have one of the axes, what will happen with the origin location if that one originally sits on the dropped axis? You know that the origin needs to be moved (you talked about it before) so this was just one thought about how/where to move it to.

**Comment by davelab6** [comment]
With #2728 and recently #2886 , can this issue be closed?

**Comment by anthrotype** [comment]
yes.. isn't it already closed?
