### ISSUE TITLE
[subset] AssertionError when using --desubroutinize

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#1590]
Running the following command on the attached font, raises an `AssertionError` exception:
```
$ pyftsubset --glyphs='*' --desubroutinize LibertinusSerif-Regular.subset.otf 
Traceback (most recent call last):
  File "/bin/pyftsubset", line 10, in <module>
    sys.exit(main())
  File "/lib/python3.7/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/lib/python3.7/site-packages/fontTools/subset/__init__.py", line 2834, in main
    subsetter.subset(font)
  File "/lib/python3.7/site-packages/fontTools/subset/__init__.py", line 2638, in subset
    self._prune_post_subset(font)
  File "/lib/python3.7/site-packages/fontTools/subset/__init__.py", line 2621, in _prune_post_subset
    retain = table.prune_post_subset(font, self.options)
  File "/lib/python3.7/site-packages/fontTools/subset/cff.py", line 457, in prune_post_subset
    self.desubroutinize()
  File "/lib/python3.7/site-packages/fontTools/subset/cff.py", line 484, in desubroutinize
    decompiler.execute(c)
  File "/lib/python3.7/site-packages/fontTools/subset/cff.py", line 390, in execute
    psCharStrings.SimpleT2Decompiler.execute(self, charString)
  File "/lib/python3.7/site-packages/fontTools/misc/psCharStrings.py", line 299, in execute
    rv = handler(index)
  File "/lib/python3.7/site-packages/fontTools/misc/psCharStrings.py", line 357, in op_hintmask
    hintMaskBytes, index = self.callingStack[-1].getBytes(index, self.hintMaskBytes)
  File "/lib/python3.7/site-packages/fontTools/misc/psCharStrings.py", line 1061, in getBytes
    assert len(bytes) == nBytes
AssertionError
```

Not sure if this is a font or subsetter bug, but it happens only when `--desubroutinize` is used.

[LibertinusSerif-Regular.subset.zip](https://github.com/fonttools/fonttools/files/3121374/LibertinusSerif-Regular.subset.zip)

**Comment by behdad** [comment]
Maybe @blueshade7 can take a look?

**Comment by blueshade7** [comment]
This line of code in `_DesubroutinizingT2Decompiler` looks suspicious:
```
	stop_hintcount_ops = ("op_hstem", "op_vstem", "op_rmoveto", "op_hmoveto",
							"op_vmoveto")
```
Maybe `op_hintmask` and `op_cntrmask` instead of `op_hstem` and `op_vstem`? @readroberts

**Comment by behdad** [comment]
> This line of code in `_DesubroutinizingT2Decompiler` looks suspicious:

Agreed.

**Comment by readroberts** [comment]
The idea is to notice if when we do not need a count of hints. The hint count is needed only for determining how many bytes is in a hint mask. If we see any of the ops in stop_hintcount_ops, then we know that we either never need, or no longer need, to be be counting hints. The list is correct. If you see op_hstem instead of op_hstemhm, there will no be a hint mask. If we see a move-to, we are done with hint counting anyway. If we see a hint mask, then that is taken case of by the hint mask op. There is clearly some bug in this area - maybe cntrmask is not correctly handled. I can look at this when I am next back at work Tues AM.

**Comment by behdad** [comment]
Is `hstem` vs `hstemhm` distinction observed in reality?

**Comment by blueshade7** [comment]
Now I see the purpose of `stop_hintcount_ops`. The charstring in question contains `cntrmask` but no `hintmask` while hints are declared by `hstem` and `vstem`. Type 2 CharString Format spec does not say hints for `cntrmask` must be declared by `hstemhm` and `vstemhm`. So the font is valid and defeating the assumption of the logic that when `hstem` is seen, stems need not counted.
```
[1]={
  -298 -2 33 583 33 62 96 hstem
  6 96 4 85 4 96 vstem
  cntrmask[1C]
  191 122 rmoveto
  -106 callsubr
  4 635 rmoveto
  -107 callsubr
  -189 hmoveto
  -107 callsubr
  endchar
}
```
Called subroutines contain no hintmasks.

**Comment by readroberts** [comment]
The hstem vs hstemhm distinction is enforced by the Adobe autohinter, and required by the spec. I have never seen a case which broke this. However, I see that Ariza is quite right that no such restriction is stated in the T2Charstring spec for cntrmask. I think this was an oversight, but since the spec has been around since 1998, It hardly seems right to change it now. I agree that the code should be changed to always count hints.

**Comment by blueshade7** [comment]
I am not insisting we should always count hints. It would simplify the logic though. We can certainly stop counting when we see rmoveto, hintmask, etc. I am not sure which is better: a simpler logic or some execution time saving (when Python is slow, every saving count or not worth the effort?).

**Comment by readroberts** [comment]
The main point is to stop executing all charstrings, even if they have already been de-subroutinized, as soon as the logic knows that counting hints is no longer necessary. I changed the 'stop counting' op list to be the move operators and the two mask operators.
