### ISSUE TITLE
Float yMin value: required argument is not an integer

### ISSUE THREAD

**Issue by editkid** [fonttools/fonttools#1604]
If a font file has a float value in `yMin`—and I assume equally in `xMin`, `xMax` or `yMax`—it will fail to save with the error `required argument is not an integer` ([`fontTools/misc/sstruct.py in pack at line 75`](https://github.com/fonttools/fonttools/blob/3.40.0/Lib/fontTools/misc/sstruct.py#L75), fonttools v3.40.0).

Trace:
```
fontTools/misc/sstruct.py in pack at line 75
fontTools/ttLib/tables/_h_e_a_d.py in compile at line 69
fontTools/ttLib/ttFont.py in getTableData at line 651
fontTools/ttLib/ttFont.py in _writeTable at line 633
fontTools/ttLib/ttFont.py in _save at line 212
fontTools/ttLib/ttFont.py in save at line 173
```

Variables at point of error:
```python
formatstring = ">llIIHHQQhhhhHHhhh"
elements = [
    65536, 
    65601, 
    1208942685, 
    1594834165, 
    3, 
    1000, 
    3551183604, 
    3640213847, 
    -132, 
    -170.009, 
    788, 
    835, 
    0, 
    3, 
    2, 
    0, 
    0
]
```

As you can see the value `-170.009` would trigger the error. If integers are expected then rounding should probably be applied.

**Comment by justvanrossum** [comment]
The question is where rounding should be applied.

If I look at the code in fonttools itself that usually provides these values, I see that rounding is done by the caller.

In your case, which code was responsible for calculating the font bounding box?

**Comment by editkid** [comment]
Good question! In our case the data is read from a font file I believe. It goes something like:
```
from fontTools.ttLib import TTFont

font = TTFont(path)
# Here some naming table data is adjusted, nothing to do with bounding box...
font.save(path)
```
This works on most files that we run through it, but a few have the `yMin` float issue. Does that mean our source font file is invalid, and we should correct its `yMin` (and other related metrics) before attempting to save?

**Comment by justvanrossum** [comment]
Hm, since the code that I looked at does do proper rounding, it's a bit of a mystery. Can you provide exact steps to reproduce?

**Comment by editkid** [comment]
Yes, luckily I have a [test version of the failing font](https://github.com/fonttools/fonttools/files/3160519/test-font.otf.zip) (with a testing licence and limited character set) that reproduces the issue. 

To reproduce with the above linked file:
```
font = TTFont("/path/to/test-font.otf")
font.save("/path/to/output.otf")
```

**Comment by justvanrossum** [comment]
Thanks, can reproduce.

The issue is that the CFF FontBBox contains float values:

`<FontBBox value="-132 -170.009 788 835"/>`

And those values are used to populate the head table upon compile. I don't think it is illegal for FontBBox to contain floats, so we indeed need to do some rounding. Probably here:

https://github.com/fonttools/fonttools/blob/ffc98baa0f28af7c4d4c173cca9f01b8c9baac14/Lib/fontTools/ttLib/tables/_h_e_a_d.py#L66

**Comment by editkid** [comment]
Thanks for confirming. And yes, I was looking at that very line you linked, also—seems like an appropriate place.

**Comment by editkid** [comment]
One question, which I don't have the knowledge to answer, is whether numbers should be rounded here; or otherwise further carried through as floats all the way downstream.

**Comment by anthrotype** [comment]
We need to round because head table can only contain integers for the font bounding box values, unlike the CFF FontBBox.
I suggest using `fontTools.misc.arrayTools.intRect` function, which takes the floor/ceill thus guaranteeing the rounded rectangle is not smaller than the original.
Would you like to work on a pull request for that?

**Comment by editkid** [comment]
Sure! On it.
