### ISSUE TITLE
[varLib.instancer] Should CFF2 be converted to CFF

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#1615]
If yes, should it be the optional, and what would be the default.

Regardless of the answer, what would be the “canonical” way to convert `CFF2` table to `CFF`?

**Comment by khaledhosny** [comment]
Here is my (totally ignorant) attempt to convert `CFF2` table to `CFF`:

```python
cff = font["CFF2"].cff
font["CFF "] = newTable("CFF ")
font["CFF "].cff = cff
del font["CFF2"]

cff.major = 1
cff.minor = 0
cff.fontNames = [instance.postScriptFontName]
```

It doesn’t work of course, the resulting `CFF` table has no `CharStrings` (in the TTX dump) at all.

**Comment by anthrotype** [comment]
`fontTools.varLib.cff` module contains a `convertCFFtoCFF2` function, I guess you're looking to reverse that process somehow. 
@readroberts may be able to be more specific about this, as he wrote that code.

**Comment by readroberts** [comment]
This is because the CFF2 table has several structural differences from a CFF table, and simply changing the major version does not fix all of them. 

A major one is that you either have to either add the info required by a CID font to the TopDict - Region,Order, Supplement (use Adobe-Identity1-0), or convert it to a name keyed font by removing the FDSelect and FDArray, and moving the Private Dict to the TopDict. In both cases you will need to add a TopDict.charset. I may have missed something, this is certainly most of the work needed.

**Comment by behdad** [comment]
Basically just start by getting a general understanding of the differences and pull the dictionary and inspect it and write the converter.  No magic here. Use Identity ROS if possible or make a named CFF.  Remember to fix post table if needed.

**Comment by behdad** [comment]
`varLib.mutator` is deprecated. The same should happen in `varLib.instancer` though.

**Comment by behdad** [comment]
Fixed in https://github.com/fonttools/fonttools/pull/3506

Just left https://github.com/fonttools/fonttools/issues/3512 which I'll do soon.

**Comment by behdad** [comment]
> A major one is that you either have to either add the info required by a CID font to the TopDict - Region,Order, Supplement (use Adobe-Identity1-0),

Somehow if I keep the FDSelect and FDArray, but don't add ROS, it kinda works (at least with HarfBuzz). But if I add identity ROS, it doesn't. Debugging more.
