### ISSUE TITLE
Rules substitution when using glyph as component

### ISSUE THREAD

**Issue by juandelperal** [fonttools/fonttools#1778]
Hi there,
I have this rule:

```xml
<rule name="t.t.rule-Weight_90_214">
    <conditionset>
        <condition name="Weight" minimum="90" maximum="214"/>
    </conditionset>
    <sub name="t.t" with="t.t.rule-Weight_90_214"/>
</rule>
```

The question is:
- is it possible also to affect those glyphs that uses `t` as a component? (ŧťţțẗṭṯ)
- or do I need to create new glyphs and rules for each case?

**Comment by justvanrossum** [comment]
> is it possible also to affect those glyphs that uses t as a component? (ŧťţțẗṭṯ)

No, substitutions cannot affect base glyphs in composite glyphs.

> or do I need to create new glyphs and rules for each case?

Indeed, yes.

**Comment by juandelperal** [comment]
Great, thanks

**Comment by behdad** [comment]
This is slightly problematic since Superpolator, etc, do substitute all uses of the component, whereas built fonts don't...

**Comment by justvanrossum** [comment]
> This is slightly problematic since Superpolator, etc, do substitute all uses of the component, whereas built fonts don't...

What do you mean exactly? The way I read https://github.com/fonttools/fonttools/blob/master/Doc/source/designspaceLib/readme.rst#83-rules-and-generating-static-ufo-instances, glyphs may get renamed, but component refs should be fixed so that the composite glyph does not change appearance. @LettError?

**Comment by anthrotype** [comment]
Just is correct

**Comment by behdad** [comment]
> What do you mean exactly? The way I read https://github.com/fonttools/fonttools/blob/master/Doc/source/designspaceLib/readme.rst#83-rules-and-generating-static-ufo-instances, glyphs may get renamed, but component refs should be fixed so that the composite glyph does not change appearance. @LettError?

I confess I don't fully understand that wording.  But happy that the two / three of you think this is addressed.  Thanks for checking.

**Comment by justvanrossum** [comment]
> I confess I don't fully understand that wording

Yeah, esp. that first sentence is confusing.

**Comment by LettError** [comment]
I’m open for changes to the text. Swapping the components is only relevant for exporting to static ufo. I understand it was not ideal.

**Comment by behdad** [comment]
Okay I think I understand this better now.  Let me try to explain what I understand:

If a rule replaces eg a two-story `a` with a one-story `a`.  Then a user would naturally expect accented characters with `a` as base (eg. `á`) to also switch shape.  That's the least-surprise action.

However, the above wouldn't work with variable fonts, because the rule is implemented using GSUB and swapping glyph indices, whereas components in precomposed characters are implemented using `glyf` table.

Now if I understand correctly, designspace documentation was changed to standardize on the undesirable solution instead, so at least there's uniformity.

Is that closer to the state things are?  Thanks.

**Comment by justvanrossum** [comment]
I don't think the intended behavior has changed.

The least-surprise action you describe would actually lead to surprises: you can't know whether the accent position for the two-story `a` is correct for the one-story `a`.

**Comment by LettError** [comment]
> If a rule replaces eg a two-story a with a one-story a. Then a user would naturally expect accented characters with a as base (eg. á) to also switch shape. That's the least-surprise action.

That’s not how it works. The single story **a** can have different metrics and different vertical size. There is no guarantee that it would fit, so that is not now the mechanism needs to work. I know because it tried it in an earlier pre-variable version of rules and it’s not very useful.

In non-var gsub, if a glyph is swapped by another, it does not affect the appearance of any glyphs that use it as a component. So, if a glyph is not specifically mentioned in a rule, it should not change appearance when the rule is active. 

The described behavior is specifically for exporting static instance ufos that should appear (as much as possible) as a variable font at the same location. Typing **a** in such a ufo, you would expect to see the **a.single**. So that means there is some swapping needed for kerning and features.

This may not be the best solution for exporting ufos from variable fonts as things get more complex. But it is how things worked before variables came along. 

What’s the bee in your bonnet?

**Comment by behdad** [comment]
Thank you all. Glad to hear this is done consistently. I just had a memory that a user reported their expectation not matching what varLib output did and it stuck in my mind as something unfortunate. No action needed from my point of view.

**Comment by juandelperal** [comment]
Great, thanks for the explanation.

Anyway, in the case mentioned above (replacing a t, pretty similar as in Gill sans) I have the same width, kerning groups and anchors position.
What do you think about adding an optional (disabled by default) parameter for also swapping components. It could be in the `rule` or in the `sub` element I guess?

I don't know it that is even possible.

**Comment by justvanrossum** [comment]
It's not possible in ttf or otf.
