### ISSUE TITLE
CFFFontSet.convertCFFToCFF2() vs. varLib.cff.lib_convertCFFToCFF2()

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#1835]
We seem to have to implementations for converting `CFF` table to `CFF2`, one in `CFFFontSet` and seems to be unused (and untested?) and one in `varLib.cff`. Any idea what is the difference between the two and if we can use the `CFFFontSet` one in varLib?

**Comment by anthrotype** [comment]
I was also wondering today about this. Any news?

**Comment by josh-hadley** [comment]
No. Started investigating this a while back when I first took this assignment, but ran into some blocks. I was trying to establish whether both things do the same thing or "close enough" but wasn't able to get that going easily and got onto more urgent matters.

@anthrotype do you have a suggestion for how to compare the results of both? I was discussing privately with @khaledhosny and came up with a simple script (basically just decompile a CFF, pass to both methods) but each one failed, for different reasons.

**Comment by anthrotype** [comment]
One thing I noticed is that, after converting a CFF table with any of these two functions, the resulting CFF2 charstrings still contain the width as first token and thus are invalid.

Because of this, attempting to draw them onto a pen (which uses the T2OutlineExtractor) will then fail with the AssertionError about "CFF2 CharStrings must not have an initial width value".

I also noticed that fontTools.varLib.cff module contains a [CFFToCFF2OutlineExtractor](https://github.com/fonttools/fonttools/blob/74867c6ddbb09c929141fb1db9bda29ae7576824/Lib/fontTools/varLib/cff.py#L435-L446) that -- as the docstrings say -- "is used to remove the initial width from the CFF charstring without trying to add the width to self.nominalWidthX, which is None".

I just wanted to convert a CFF font to CFF2, but it doesn't seem that fonttools currently exposes an API for that that works end-to-end.

How does one go about converting a T2CharString that was originally contained in a CFF 1.0 table, to one that can be stored in a valid CFF2 table -- thus dropping width, endchar and return ops -- but _without_ having to draw the charstring onto a new T2CharStringPen?

Drawing onto a new T2CharStringPen and finally call `pen.getCharStrings()` kind of works, provided I override the charstring objects' `outlineExtractor` attribute to this above-mentioned `CFFToCFF2OutlineExtractor`, which ignores the widths.

The problem with doing that is that this also unpacks all the subroutines as well, and I would like to keep them, if the input CFF1 has them. Also this redrawing approach means the specialized drawing commands need to be recomputed, whereas I'd like to keep the charstring unchanged and only drop the width.

Somehow I'd need to make a custom decompiler but I am not sure how to best to that.

**Comment by anthrotype** [comment]
Ah! To only drop the initial width from a T2CharString program, I figured I could modify the `specializer.programToCommands` function like below, then roundtrip the program->commands->program while setting ignoreWidth=True:

```diff
diff --git a/Lib/fontTools/cffLib/specializer.py b/Lib/fontTools/cffLib/specializer.py
index 1d2f4b73..7dade86d 100644
--- a/Lib/fontTools/cffLib/specializer.py
+++ b/Lib/fontTools/cffLib/specializer.py
@@ -37,7 +37,7 @@ def programToString(program):
        return ' '.join(str(x) for x in program)


-def programToCommands(program, getNumRegions=None):
+def programToCommands(program, getNumRegions=None, ignoreWidth=False):
        """Takes a T2CharString program list and returns list of commands.
        Each command is a two-tuple of commandname,arg-list.  The commandname might
        be empty string if no commandname shall be emitted (used for glyph width,
@@ -107,7 +107,8 @@ def programToCommands(program, getNumRegions=None):
                                numArgs = len(stack)
                        if numArgs and (numArgs % 2) ^ parity:
                                width = stack.pop(0)
-                               commands.append(('', [width]))
+                               if not ignoreWidth:
+                                       commands.append(('', [width]))

                if token in {'hintmask', 'cntrmask'}:
                        if stack:
```

This seems to work for my use case. Maybe I can send a PR to add this. Though I am not 100% this is the right place for this.
