### ISSUE TITLE
fontTools.encodings.MacRoman - used by anything?

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#1919]
The only references to MacRoman in the repository are:

* `fontTools/encodings/MacRoman.py` itself.
* comments in the test files

Nothing imports it, nothing seems to use it inside fontTools - does anything outside fonttools use it? Can it be removed?

**Comment by typemytype** [comment]
don't remove it

**Comment by anthrotype** [comment]
still, for our future selves, it would be good to write some comment inside that file to explain why it is there and what outside of fonttools is using it for.

**Comment by simoncozens** [comment]
I'm still working on the encodings doc PR so will add it in there. If anyone (@typemytype) wants to tell me what sort of things it is actually used for that will help!

**Comment by justvanrossum** [comment]
1. RoboFont used to have an option to use MacRoman as the (basis for) the glyph order. I forgot why it did that.

2. It's simply a nice reference for this encoding, in terms of glyph names, and how they may have been used in legacy fonts.

3. Like with `t1Lib`, the fact that something is not otherwise used in fonttools itself should never be a reason to even consider removing it. This stuff has been around forever, and there's no way of knowing whether client code may break if we do remove it. I'm fine with labeling this "legacy", if that makes documenting this easier.
