### ISSUE TITLE
Make TTFont and other objects pickleable by implementing __reduce__

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1962]
For lazy objects it should `ensureDecompiled()`; for our list-like types, for ttFont, etc.

**Comment by behdad** [comment]
Or `__getstate__` for some should be enough.

**Comment by behdad** [comment]
Implementing `__reduce__` also makes `copy()` and `deepcopy()` to work as well.

**Comment by anthrotype** [comment]
I think the problem is only the SFNTReader which holds a reference to an unpickled file object when TTFont is loaded with lazy=False. Normally, with lazy=None (default) or with lazy=False, a TTFont can be pickled because we only store a copy of the input file's data in an in-memory BytesIO.

We already implemented a custom `__deepcopy__` for SFNTReader to handle the lazy=True case:

https://github.com/fonttools/fonttools/blob/db26cf804e3380b5e9caed3a33d640b8e8a54835/Lib/fontTools/ttLib/sfnt.py#L125-L147

To make TTFont (and all children objects) pickleable, we only need to make the SFNTReader pickleable.
The rest of the lazy objects should just work.
