### ISSUE TITLE
Can I convert to woff with zopfli at TTFont?

### ISSUE THREAD

**Issue by black7375** [fonttools/fonttools#2064]
**Related Topic**
#491

**Describe**
I'm trying to convert the font using `TTFont`.
It works fine.
```python
from fontTools.ttLib import TTFont

font = TTFont( SOURCE_PATH )
font.flavor = "woff"
font.save( TARGET_PATH )
```

But..
There is no way to use `zopfli` in document [ttFont Doc](https://rsms.me/fonttools-docs/ttLib/ttFont.html).
What can I do?

**Comment by chrissimpkins** [comment]
Here is the approach that is being used in ttx:

https://github.com/fonttools/fonttools/blob/0b413be45a92bb75e64362c1e38309f41d06cafd/Lib/fontTools/ttx.py#L278-L292

I think that if you set `sfnt.USE_ZOPFLI = True` before your `font.save([PATH])` step that SFNTWriter should use zopfli rather than the zlib package?

https://github.com/fonttools/fonttools/blob/0b413be45a92bb75e64362c1e38309f41d06cafd/Lib/fontTools/ttLib/sfnt.py#L175-L189

**Comment by anthrotype** [comment]
Chris is correct, although I dislike that approach of modifying a global variable. Pity I didn't get the chance to fix that yet.

**Comment by black7375** [comment]
@chrissimpkins 

Thanks for telling me a good way.
If I have enough time, I will consider writing a PR.

**Comment by chrissimpkins** [comment]
#2066
