### ISSUE TITLE
Travis CI Github integration setup

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#2070]
Not sure if this is a temporary technical glitch or not, but I can't seem to be able to do things like stop or restart a Travis CI build, or access the Travis repository settings, I'm getting this error when I try

> Oh no! Your permissions are insufficient to access this repository's settings

I don't think I've changed anything on my Github's side. My github username anthrotype still features as Admin in the repo github settings.

This makes me wonder if this is the time we finally move over to Github Actions as our CI provider..

**Comment by anthrotype** [comment]
temporary glitch indeed, sorry for the spam.

**Comment by anthrotype** [comment]
probably unrelated but I just saw this in the fonttools organization's list of "installed Github Apps":

![image](https://user-images.githubusercontent.com/6939968/94457344-53fca100-01ac-11eb-8413-20b39e7993a0.png)

there's a pending request by @miguelsousa about authorizing "Travis CI" as Github Apps for the organization.
I don't know what that means, and how that is different from the setup we currently have.

Is that a new way of setting things up between Travis and Github? I haven't been following much on that lately.

**Comment by alerque** [comment]
I can see the details, but I'm guessing the request is *probably* from `travis-ci.com` and you're probably running on `travis-ci.org`. The former used to be paying customers only and the latter was OSS projects. For years now they've been slowly deprecating the OSS silo and mixing them in with their regular platform. It's pretty simple but not automatic because you have to re-authorize the project on the new domain and push the button on their site to migrate across.

**Comment by behdad** [comment]
Should be closed?
