### ISSUE TITLE
pyftsubset: Keep featureVariations

### ISSUE THREAD

**Issue by typefacts** [fonttools/fonttools#2085]
Hi, 
is there a way to keep GSUB’s featureVariations and the corresponding lookups?

My code:
`pyftsubset font.ttf --recommended-glyphs --notdef-outline --layout-scripts='DFLT,latn' --layout-features='kern' --unicodes-file=Trial_unicodes.txt --glyphs-file=Trial_names.txt --recalc-timestamp --name-IDs='*' --name-legacy --name-languages='*' --ignore-missing-glyphs --ignore-missing-unicodes`

Thanks in advance!
Christoph

**Comment by justvanrossum** [comment]
Wild guess: are you sure it doesn't get killed by `--layout-features='kern'`? You may want to include `rvrn` there, or whichever feature you use for feature variations.

**Comment by typefacts** [comment]
Yes, I use rvrn, and this indeed did the trick. 🤭 Thanks a lot, Just!!

**Comment by anthrotype** [comment]
"rvrn" should be in the list of features that are kept by default. If you use `+=` instead of `=`, e.g. `--layout-features+='kern'`, the subsetter will _add_ "kern" to the list of features that are kept by default. You can do `--layout-features=?` to see the full list of default features.
If you use `=` it will _only_ keep the specified features (in your example, only `kern`, thus dropping `rvrn` among others).

**Comment by typefacts** [comment]
Thanks a lot, Cosimo! I had read this in `--help` but somehow I went for `--layout-features-=` with all default ones but kern and rvrn first, which didn’t work.
With `--layout-features='kern,rvrn'` it works like I wanted: Only `kern`and `rvrn`left.
