### ISSUE TITLE
missing release artifact for 4.18.0

### ISSUE THREAD

**Issue by chenrui333** [fonttools/fonttools#2121]
👋  it looks the `fonttools-4.18.0.zip` missing in the latest release? Just double check to make sure if that is intended.

**Comment by anthrotype** [comment]
Is that what you were looking for https://pypi.org/project/fonttools/#files

We switched to a different CI workflow and no longer uploading the dist packages to the GitHub Release, since we are already uploading them to the canonical place where these are expected to be found (by pip), which is the Python Package Index.

**Comment by chenrui333** [comment]
I see, thanks for pointing out the direction.
