### ISSUE TITLE
[varLib] warn when using rvrn substitution for glyphs without codepoint?

### ISSUE THREAD

**Issue by madig** [fonttools/fonttools#2168]
Given how `rvrn` is misdesigned to go first instead of last, it can as far as I understand only sensibly be used for glyphs with a Unicode codepoint, i.e. something that is not the result of another substitution. Maybe varLib should log a warning about this when encountering an input glyph without a codepoint and suggest to either use `rclt` or manually write out the variation substitution chains in the feature file?

**Comment by justvanrossum** [comment]
While I agree that `rvrn` is close to useless for real use, I have since learned that it's pure existence is due to the specced behavior: without that, there would be no `rvrn` at all, as the remaining behavior can be done via `rclt` or `rlig`. (Paraphrasing John Hudson, who explained it to me patiently while I was still foaming with rage :) )

That said, maybe indeed such a warning would be good.

(Note that `rclt` still doesn't work in most Adobe apps, another thing worthy of some foaming rage.)

**Comment by madig** [comment]
Cosimo doesn't like it:

> the compiler is doing something that is correct, but uselesss
> the assessment of usefulness is for a linter to judge
> and warnings are ignored 99% of the time
> i'm not saying that someone should check for these things
> i'm arguing that fonttools is not the right place
> a submodule of fonttools that is concerned about building feature variations tables should not be concerned with other piece of data in other tables like cmap
> it's the reponsibility of something higher up in the chain to check for such consistency
> the output from featureVars is valid
> nothing to warn about at that level
> i'm concerned that we bloat fonttools code unnecessarily with checks and warnings and stuff
> or requirements that input font contain a valid cmap before being able to build a feature variations table
> why?
> what if I have a half-built font, empty, containing only a glyphOrder 
> I won't be able to run featureVars without a cmap?

**Comment by justvanrossum** [comment]
I agree with Cosimo.

**Comment by madig** [comment]
Ok :(

**Comment by chrissimpkins** [comment]
fontbakery?

**Comment by madig** [comment]
Already done in a certain PR in a certain secret repo.
