### ISSUE TITLE
Issues on pyftsubset --text

### ISSUE THREAD

**Issue by McChickenNuggets** [fonttools/fonttools#2256]
Having issue running the code below, and get a warning.
```
pyftsubset PingFang-SC-Regular.ttf --text="1234567890" --output-file="PingFang-Num.tty"
```
WARNING: meta NOT subset; don't know how to subset; dropped

**Comment by behdad** [comment]
We don't subset the `meta` table in the font. If you don't care about that table being dropped from the subset, you are fine with the warning. If you want subsetter to just pass it through unmodified, pass `--no-subset-tables+=meta` to the command line.

We don't subset it because it lists supported languages, and modifying that based on text retained is non-trivial.

**Comment by orynider** [comment]
Were is pyftsubset included in the release or in this repository ?

I need to call it from PHP . 10x

**Comment by behdad** [comment]
Call `fonttools subset` instead.
