### ISSUE TITLE
Removal of .Format in 4.22 causes Attribute Errors

### ISSUE THREAD

**Issue by kaydeearts** [fonttools/fonttools#2271]
Within the [AFDKO ttxn tool](https://github.com/adobe-type-tools/afdko/blob/develop/python/afdko/ttxn.py) as well as other internal tools, we use the `.format` attribute to identify & handle specific formats of lookup types. For instance, in [ttxn.py buildClasses()](https://github.com/adobe-type-tools/afdko/blob/3a83d6e760f1dfd275c4f8c98ed771189ed11882/python/afdko/ttxn.py#L1709), a list of otTables.Lookup objects is traversed, looking at each Lookup object’s SubTable. These SubTable objects can be various subst objects.
When we attempt to distinguish how to handle these subtable objects, [we need the format](https://github.com/adobe-type-tools/afdko/blob/3a83d6e760f1dfd275c4f8c98ed771189ed11882/python/afdko/ttxn.py#L1715) to be able to do so. Currently, we have [AttributeErrors](https://github.com/adobe-type-tools/afdko/runs/2363337573#step:6:17880) for multiple ttxn.py tests after `format` [was removed in this PR.](https://github.com/fonttools/fonttools/pull/2238)
We have other internal tools that use `.format` in a similar way.

Can `format` be added back or is there another attribute/method we can use?

**Comment by anthrotype** [comment]
fonttools v4.22 removed `.Format` attribute from the following tables: Coverage, ClassDef, SingleSubst, LigatureSubst, AlternateSubst, MultipleSubst. The reason being that the attribute was redundant since these tables are decompiled into a python object where the underlying encoding differences that may characterise various formats are abstracted away, so it doesn't matter when you encounter one whether it's format 1 or 2 or whatever. The format is automatically chosen at compile time depending on the content/structure of the data in each table. Basically you don't have to worry about it.
Your code is not doing anything based on the Format for these specific tables where we dropped the attribute (because even before there wasn't anything special about the formats). Where are unconditionally getting `subtable.Format`, you may as well do `getattr(subtable, "Format", 1)` (or any other number) and nothing will change in your code.

**Comment by kaydeearts** [comment]
@anthrotype Thank you for your response! We resolved it with a similar workaround where we check class attributes for specific lookup types, and choose the handler based on that. No more issues with `format` removal now.
