### ISSUE TITLE
Different way of solving quadratic equations

### ISSUE THREAD

**Issue by madig** [fonttools/fonttools#2329]
https://www.poshenloh.com/quadraticdetail/

Maybe this can be used for the quad stuff in `fontTools/misc/bezierTools.py`?

**Comment by behdad** [comment]
That's not a different way of solving quadratic equation. Just a different way to explain them. I'm not sure different from what though...

At any rate, our code does the same:

  https://github.com/fonttools/fonttools/blob/f64f0b42f2d1163b2d85194e0979def539f5dca3/Lib/fontTools/misc/bezierTools.py#L621-L651

which is expected, since there's only one way to solve a quadratic equation.

**Comment by madig** [comment]
Damn! I was hoping this could be exploited to simplify the calculation somehow. Oh well.
