### ISSUE TITLE
Size to be increased.

### ISSUE THREAD

**Issue by dorythefish-kim** [fonttools/fonttools#2397]
In ttLib.tables._k_e_r_n.KernTable_format_0.compile(),

The size for 'rangeShift' is too small for some fonts in CJK (e.g., [NotoSarifCJKkr](https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifCJKkr-hinted.zip)).

It is recommended to increase the size as in

```
data = struct.pack(
	">HHHI", nPairs, searchRange, entrySelector, rangeShift)
```

**Comment by behdad** [comment]
Can you elaborate please?

**Comment by jmkim0913** [comment]
Sorry for this late reply.

I was trying to rename some fonts as described in [this article](http://www.fontgeek.net/blog/?p=343).
But I found that some fonts like [NotoSarifCJKKr](https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifCJKkr-hinted.zip) cannot be compiled due to an error in [/Lib/fontTools/ttLib/tables/_k_e_r_n.py](https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/ttLib/tables/_k_e_r_n).

The reason was the bit size letter in line 167,

`data = struct.pack(
	">HHHH", nPairs, searchRange, entrySelector, rangeShift)`

The letter for `rangeShift`, `H` in `">HHHH"` was small to process big Serif CJK fonts.
After it was changed to `">HHHI"`, it works well.

Hope this helps.

**Comment by behdad** [comment]
> After it was changed to `">HHHI"`, it works well.

You can't do that as the format of the table specifies 'H'. That is, it will break the kerning table.

However, see this comment:
https://github.com/fonttools/fonttools/blob/42e4d66184be1acda05bed1896da6d61c084835e/Lib/fontTools/ttLib/tables/_k_e_r_n.py#L50-L52

We need to add the counterpart to that to the compile side; basically just clamp the nPairs to 0xFFFF. Does this patch fix it?
```diff
diff --git a/Lib/fontTools/ttLib/tables/_k_e_r_n.py b/Lib/fontTools/ttLib/tables/_k_e_r_n.py
index f3f714b2..8fb6debc 100644
--- a/Lib/fontTools/ttLib/tables/_k_e_r_n.py
+++ b/Lib/fontTools/ttLib/tables/_k_e_r_n.py
@@ -161,7 +161,7 @@ class KernTable_format_0(object):
                                len(data) - 6 * nPairs)
 
        def compile(self, ttFont):
-               nPairs = len(self.kernTable)
+               nPairs = min(len(self.kernTable), 0xFFFF)
                searchRange, entrySelector, rangeShift = getSearchRange(nPairs, 6)
                searchRange &= 0xFFFF
                data = struct.pack(
```

**Comment by jmkim0913** [comment]
Yes it works ! Thank you.

**Comment by behdad** [comment]
@justvanrossum @anthrotype WDYT about this change?
