### ISSUE TITLE
[subset] Decompose removed glyphs that are used as components in ttf

### ISSUE THREAD

**Issue by kosbarts** [fonttools/fonttools#2428]
Is there an implemented way to decompose a glyph that is set to be removed when it is used as a component in another glyph in a ttf? 

For example I have a Greek Gamma that I use as a component for the Cyrillic Ge and when I subset a Cyrillic ttf only version the Gamma is kept.

**Comment by anthrotype** [comment]
if the removed glyph is only used once as component in a composite glyph, then it could make sense to decompose and remove it altogether, but you'd probably only save a couple bytes (basically the header of the component glyph). Otherwise, keeping it as component (while removing it from cmap or GSUB) is better, the glyph can't be accessed directly by any other means (except indirectly by component reference) so it shouldn't bother you.

**Comment by kosbarts** [comment]
@anthrotype yes it makes sense. Thanks.
