### ISSUE TITLE
PyPI doesn't deliver latest version

### ISSUE THREAD

**Issue by lemzwerg** [fonttools/fonttools#2451]
[0dc2f820bd54dbe772e289ffa38b96e4d2ed1602]

If I do
```
pip3 uninstall fonttools
pip3 install fonttools
```
to install the latest version, I currently get version 4.27.1.  However, the latest tag in the git repository is 4.28.1.

IIRC, releasing a new fonttools version includes an automatic upload to PyPI, so I'm reporting this here – maybe the upload failed, or the related script has problems.

**Comment by anthrotype** [comment]
Hey Werner!

We do upload automatically, in fact it's there https://pypi.org/project/fonttools/4.28.1/

you probably are using python 3.6, which is reaching EOL end of this year. Since 4.28 we now require python 3.7 or greater (#2417).
Pip is installing the latest compatible version available on PyPI, which for 3.6 would be in fact 4.27.1.

**Comment by anthrotype** [comment]
the decision to drop 3.6 is in line with what other similar python projects are doing (e.g. numpy). it was discussed here https://github.com/fonttools/fonttools/issues/2350

I did also update the README as well, which mentions 3.7 as required python version. I hope this is not a problem for you

**Comment by lemzwerg** [comment]
Ah, ok.  Thanks for the explanation.
