### ISSUE TITLE
pyftmerge breaks fonts that support the same character

### ISSUE THREAD

**Issue by dscorbett** [fonttools/fonttools#2475]
Merging fonts sometimes doesn’t work when the source fonts support the same non-common-script character. This happens both with 4.28.4 and with 4.28.4 plus #2473 (as of that PR’s commit `8a76455`).

```console
$ curl -LOs https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansGrantha/NotoSansGrantha-Regular.ttf
$ curl -LOs https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansTamil/NotoSansTamil-Regular.ttf
$ pyftmerge NotoSansTamil-Regular.ttf NotoSansGrantha-Regular.ttf
$ mv merged.ttf taml-gran.ttf
$ pyftmerge NotoSansGrantha-Regular.ttf NotoSansTamil-Regular.ttf
$ mv merged.ttf gran-taml.ttf
$ hb-shape --ned --no-positions -u 0BAA taml-gran.ttf
[patamil]
$ hb-shape --ned --no-positions -u 0BAA gran-taml.ttf
[pa_tamil]
```

If the Tamil font comes first, the glyph is `patamil`. If the Grantha font comes first, the glyph is `pa_tamil`, which breaks any Tamil lookups that expect `patamil`. Both fonts include both glyphs, but each font only ever uses one of the glyphs.

A solution might be to canonicalize the glyphs to a single glyph. For example, if Noto Sans Grantha is specified first, the canonical glyph would be `pa_tamil`. `patamil` would be discarded entirely and anything in Noto Sans Tamil that refers to `patamil` would be changed to refer to `pa_tamil`.

**Comment by behdad** [comment]
The way this is supposed to work in the merger, and given that you don't get a warning, is that, since the two scripts use different script tags, the merger adds GSUB rules to one of the scripts to map one glyph to the other in one of those scripts. But I cannot make it work....

2 hours later...

okay found the bugs. PR coming.

**Comment by behdad** [comment]
With that PR:
```
behdad:ttf 0 (main)$ hb-shape -u 0BAA merged.ttf --script taml
[patamil=0+778]
behdad:ttf 0 (main)$ hb-shape -u 0BAA merged.ttf --script gran
[pa_tamil=0+778]
```

**Comment by behdad** [comment]
> A solution might be to canonicalize the glyphs to a single glyph.

I like to move towards this if the glyphs have identical rendering (in this case they do). One issue with it is that some of our lookup representations need reshuffling if glyph order changes. However, I think we can ignore that since our `Coverage` compiler knows how to deal with out-of-order glyphs as a known hack by using format2.

**Comment by satbyy** [comment]
Thanks! PR https://github.com/fonttools/fonttools/pull/2476 fixes this issue for Tamil/Grantha with test string ப்பிபீபுபூவு. Both cases are rendered identically (as expected)

![image](https://user-images.githubusercontent.com/17479988/146377720-516fe01d-d727-433b-80d7-472992bfd6e3.png)
