### ISSUE TITLE
[subset] Add --subroutinize / --resubroutinize

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#283]
Based on:

 https://github.com/googlei18n/compreffor
 https://github.com/samfishman/fonttools/commits/subroutinization

Also, probably add desubroutinize to cffLib level.

**Comment by behdad** [comment]
> Also, probably add desubroutinize to cffLib level.

Such that we can use it from compreffor itself:

  https://github.com/googlei18n/compreffor/issues/1

**Comment by anthrotype** [comment]
yes, we need to move the desubroutinize code in the cffLib, away from the subset module. Compreffor currently uses the subsetter to decompress the CFF table, by passing the 'desubroutinize' option, but the subsetter does many more things than just desubroutinizing, therefore skewing the results. I spent one hour trying to figure out why I was getting different file sizes if the --decompress option was set. The reason was not the CFF table, but everything else...

**Comment by behdad** [comment]
@anthrotype After you are back from vacation, are you possibly interested in tackling this? Thanks! :)
