### ISSUE TITLE
Color fonts getting different appearance in Firefox and Chrome

### ISSUE THREAD

**Issue by santhoshtr** [fonttools/fonttools#2938]
I have a color font with two layers, each layer having a gradient. Chrome and Firefox used to give expected result, but recently noticed that Chrome applies the same gradient to both layers. The issue is illustrated below:

Font file:
https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram-Color/ttf-color/Nupuram-Color.colrv1.ttf

Firefox version 108(Correct rendering):
![image](https://user-images.githubusercontent.com/161672/209373184-8bad7ddb-fdcb-4793-b6d1-af9290391dd4.png)

Chrome version 108(Broken rendering)
![image](https://user-images.githubusercontent.com/161672/209373349-8d67e075-803b-4e4b-a872-2abc46229b68.png)

Both can be tested by using https://smc.gitlab.io/fonts/Nupuram/tests/, select Nupuram Color from drop down

The code that use fontTools.colorLib builder  is at https://github.com/santhoshtr/nupuram/blob/master/tools/build_color_v1.py

I would like to know if this is a chrome bug or my incorrect usage of colorlib builder?

**Comment by santhoshtr** [comment]
I just tried blackrenderer and it is giving output same as Firefox(ie, correct rendering).

**Comment by behdad** [comment]
HarfBuzz gets the right rendering also, except that it's clipped, perhaps because the font has wrong clipbox.

**Comment by behdad** [comment]
cc @drott

**Comment by matthiasclasen** [comment]
the font has no clipboxes at all, so we just get the extents of T, ignoring T.shadow

**Comment by santhoshtr** [comment]
I can confirm that adding a dummy clipbox like this resolves the issue for Chrome:

```diff
-font["COLR"] = builder.buildCOLR(colrv1_map)
+font["COLR"] = builder.buildCOLR(colrv1_map,  clipBoxes={
+                "a": (0, -500, 1024, 1024)
+            },)
```

But this is a dummy clipbox just for a single glyph. If that can change the whole behavior of chrome, I suspect it is an implementation issue in Chrome? From the documentation, I see clipbox is optional.

**Comment by drott** [comment]
> https://smc.gitlab.io/fonts/Nupuram/fonts/Nupuram-Color/ttf-color/Nupuram-Color.colrv1.ttf

Using the font from this URL, not reproducible in Chrome 108.0.5359.125 (Official Build) (64-bit) (cohort: Stable) 
and test content:

```
<style>
@font-face {
font-family: nupu;
src: url(Nupuram-Color.colrv1.ttf);
}
body {
background-color: darkgray;
}
div {
font-family: nupu;
font-size: 120px;
}
</style>
<div>സംഘർഷം</div>
```

![image](https://user-images.githubusercontent.com/1021784/210212613-632a7947-5e8e-4a43-8035-b3a0441cb718.png)

Is this the font with the ClipBoxes added? If yes, and the issue persists when the ClipBox is removed, please file an issue at crbug.com and attach the font and ideally html test content with which you see the undesired behavior.

**Comment by santhoshtr** [comment]
@drott , I had added clibpoxes to latest version. I will file a bug with the previous version that has the issue

**Comment by santhoshtr** [comment]
Closing this ticket as it is tracked in Chromium

**Comment by anthrotype** [comment]
I'd like to leave this open to see if we can find some workaround to this Chrome bug. 

In that bug, @drott wrote

> The reason seems to ben an incorrect bounds check at the end of the font file where the ColorLine objects are stored. If ClipBoxes are used, they may be placed after the ColorLines in the font file - which avoids things getting blocked by the bounds check.

Maybe fontTools.colorLib.builder could add an empty ClipList at the end of the COLR table with the numClips count set to 0, even when no clipBoxes are provided in the input data. But I need to check if this actually works around this or not.

**Comment by khaledhosny** [comment]
Does a short-lived bug like this one worth the trouble?

**Comment by drott** [comment]
> Does a short-lived bug like this one worth the trouble?

Good question - maybe we shouldn't cast this bug into an implemented workaround elsewhere. 

> Adding an empty ClipList doesn't fix this

Using for example the `otexplorer` binary, did you check what's exactly at the end of the COLR table? The bug is in reading the `ColorLine` while at the same time checking that the reading cursor does not cross the end of the table. But the error in calculating that might have been the size of one (Var)ColorStop - 1. That would be in line with your observation, that there has to be something a bit larger there, like a dummy ClipBox. But yes, up to y'all on whether that's worth implementing a work around. Another workaround could be not place ColorLines at the end but something else, if there is anything else that can be placed variably.

**Comment by anthrotype** [comment]
all COLRv1 fonts generated with fontmake (that use glyphsLib to convert Glyphs.app's specific color gradient definitions to fontTools-compatible paint definitions) will display this bug, because glyphsLib currently does not compute clipboxes and leaves them omitted. Blaka Ink is one of them, for example: https://fonts.google.com/specimen/Blaka+Ink

I am leaning towards just changing glyphsLib to always compute the ClipBoxes, like nanoemoji does..
