### ISSUE TITLE
No handlers could be found for logger "fontTools.ttLib.tables._n_a_m_e"

### ISSUE THREAD

**Issue by BoldMonday** [fonttools/fonttools#2980]
Recently this sentence started to pop up in my Terminal when compiling fonts using `makeotf`:
```
No handlers could be found for logger "fontTools.ttLib.tables._n_a_m_e"
```

I'm running the latest version of afdko (3.9.3) with fonttools (4.38.0).

**Comment by anthrotype** [comment]
an application (makeotf) that uses a library (fontTools) that uses the logging module has to configure logging (e.g. at the least, call logging.basicConfig()), otherwise the logging messages would have no handler. In Python2 that meant they would be ignored, in python3 there's a fallback handler (that prints to stderr with that initial warning message about no handlers being found) which gets registered whenever logging hasn't been configured.
It's all in the logging stdlib docs, not our bug and nothing the library itself can do, configuring logging is responsibility of an application.

**Comment by anthrotype** [comment]
I recommend that you file this over to the afdko repository.

**Comment by BoldMonday** [comment]
Thanks for the reply. Issue filed at https://github.com/adobe-type-tools/afdko/issues/1609
