### ISSUE TITLE
[designspace] Representing avar2 mappings in designspace documents

### ISSUE THREAD

**Issue by Lorp** [fonttools/fonttools#3049]
The [avar2 spec](https://github.com/harfbuzz/boring-expansion-spec/blob/main/avar2.md) is defined, the need for the new format has been demonstrated with various use cases [[video](https://www.youtube.com/watch?v=j7unMVZOcaw) / [slides](https://docs.google.com/presentation/d/1jLiUvh4PoYz2sw0T0Fygj2HoMrBhmJQuGgAmoMc_Sns/edit#slide=id.p
)] including much smaller binary size for usable parametric fonts, and a few [fonts are being tested](https://lorp.github.io/samsa/src/samsa-avar2.html). However it remains difficult to make avar2 fonts since there is no high-level method to generate an avar2 table.

**The following draft spec represents avar2 mappings in .designspace documents — when implemented it will enable avar2 fonts to be built much more easily.**

* [**Proposal for representing avar2 mappings in designspace documents**](https://github.com/harfbuzz/boring-expansion-spec/blob/main/avar2-in-designspace.md)

Reviews appreciated!

**Comment by anthrotype** [comment]
Thank you Laurence! I finally read that document, and here's my initial comments.

> The avar2 use-case classes already identified (distortion, parametric, HOI, fences) are not representable in the “sources/masters” style. We need to allow the min, peak, max style of variation region specification.

could you elaborate on this a bit, or make an example? it's not immediately clear why, at a first read. I mean, surely having access to "full-power OT variation math" might be desirable per se, but because it diverges so much from the DesignSpace's current approach for the other variable data, I think we should clarify why the latter doesn't work for avar2 and the latter requires more low level control on the region definitions. I'm not arguing that that's not true, just would like to understand better why this is the case.

> Represent avar2 in absolute user coordinates

"user" coordinates mean those from fvar. But isn't avar2 supposed to happen _after_ avar1, by which (normalized) user coordinates are turned into (normalized) internal coordinates? So, if avar1 mappings are present, the input to avar2 cannot be considered to be in user coordinates any more, I believe. I think both the input and output of avar2 should be considered to be in internal, design-space coordinates, as mapped by avar1 mappings if present; if there aren't any, then user == design coordinates so that distintion doesn't matter.

> The <input> element contains one or more <dimension> elements and thereby defines a variation region

The `<dimension>` element is currently used to define "locations", i.e. a point identified by a (full) set of axis coordinates in the variation space. You're proposing to also use "dimension" to describe the triangular "tents" that comprise the "regions" within which delta-sets are applicable, by adding two optional minimum/maximum attributes. In your examples you only seem to be using these minimum/maximum attributes for the map _input_, never in the _output_ set of dimensions. Is that because in the latter section they do not actually make sense, because the expected "output" of avar2 maps is always supposed to be a point (or plane, or whatever multi-dimensional thing is beyond that, when the set of dimensions omits some axes)?
Should we use a different element name from "dimension" to make explicit where such a definition of "region" makes sense or not (if at all)?

> ... equivalent to the <map> mappings of avar1, except that in avar2, the delta may cause the value to cross over the default.

I recommend providing an example of an avar1-equivalent avar2, one that also demonstrates this ability to 'cross over'.

> Allow axis tag as well as axis name.

this would diverge from existing pattern that is used for cross-referencing between DS elements by their name (effectively used as the unique id of an element). Why isn't the `name` attribute sufficient for this and using `tag` would be beneficial? Nobody prevents one from assigning the same value to both axis name and tag.

**Comment by Lorp** [comment]
Thanks Cosimo for the comments.

>> The avar2 use-case classes already identified (distortion, parametric, HOI, fences) are not representable in the “sources/masters” style. We need to allow the min, peak, max style of variation region specification.

> could you elaborate on this a bit,

I think I’d reframe it as these two questions:

1. Are the 4 identified use cases in general representable using “masters” style?
2. Are all possible use cases representable using “masters” style?

I don’t know the answers, but my proposal assumes NO to both. Perhaps someone who understands better than I do how varLib translates sparse masters into deltas can answer this.

>> Represent avar2 in absolute user coordinates

> "user" coordinates mean those from fvar. But isn't avar2 supposed to happen after avar1, by which (normalized) user coordinates are turned into (normalized) internal coordinates …

Good question. I actually copied avar1’s \<map in using 16.16 coordinates for input and output (rather than 2.14 as is actually the case). I imagine input and output in user space rather than normalized space in order to help human .designspace readers/writers. The coordinates I’m using in avar2 are implicitly those transformed by avar1, even if a null avar1 will be most common. Are there cases where user space doesn’t make sense?

> The \<dimension\> element is currently used to define "locations" … Should we use a different element name from "dimension"…

Trying hard to reuse avar1 vocabulary, I’m very likely abusing the \<dimension\> element for \<input\>, maybe also for \<output\>. Certainly open to new suggestions.

> I recommend providing an example of an avar1-equivalent avar2, one that also demonstrates this ability to 'cross over'.

Good point, I’ll work on that.

>> Allow axis tag as well as axis name.

> this would diverge from existing pattern that is used for cross-referencing between DS elements by their name (effectively used as the unique id of an element). Why isn't the name attribute sufficient for this and using tag would be beneficial?

No strong feelings, but I sometimes want to change axis name without changing axis tag, in which case I’d edit the name just once in its \<axis\> definition. But it sounds like out of scope for an avar2 proposal.

**Comment by Lorp** [comment]
In email discussion, @behdad and @twardoch disliked the retention of the avar1 \<map\> element, and @behdad suggested \<mappings\> instead. I rather like the concept that the avar1 element rises up a level, corresponding to its ability to map all axes. But no strong feelings.

**Comment by justvanrossum** [comment]
I would also like to raise my concern for wanting to represent arbitrary variation math at the low level of the ItemVariationStore. Those data types are designed for efficient rendering, not necessarily for higher level representation.

Perhaps region/tent-based data structures can represent certain configurations that are impossible to represent as a sources-based approach, but I'm not convinced those cases (if they exist) need to be represented in the first place.

In my mind, the concepts are divided like this:
1. regions/tents/deltas are renderer-oriented and low level
2. abolute sources at singular locations within a variation space are authoring-oriented and high(er) level

Designspace currently firmly sits at the high(er) level, and I think it should be possible to represent avar2 in that way, too.

This *may* prevent some region/tent-based configurations to be (easily) representable, but I think designspace's higher-level appraoch has generally been an advantage rather than a shortcoming, despite of the fact that it cannot (fundamentally) represent *everything* that the binary can.

**Comment by behdad** [comment]
For code that generates avar2, see eg.:
https://github.com/aliftype/raqq/blob/2b9f363ee0095ad4b68b61524da74320bbaa2ac6/scripts/build.py#L445

**Comment by behdad** [comment]
I'm implementing this slowly, at least the part generating from XML to avar2 table directly, in:
https://github.com/aliftype/raqq/pull/15/files

**Comment by Lorp** [comment]
Those following this issue may appreciate @simoncozens’ recap [*Userspace and designspace - a note to self*](https://simoncozens.github.io/userspace-and-designspace/) of the various ways coordinates are represented in a designspace document.

**Comment by Lorp** [comment]
The implemented syntax uses a \<mappings\> element containing any number of \<mapping\> elements, but is otherwise the same as described above. Here is the documentation of the designspace \<mappings\> element, as implemented in fontTools:

[designspaceLib: Document XML structure: 2.2.3 \<mappings\> element](https://fonttools.readthedocs.io/en/latest/designspaceLib/xml.html#mappings-element)
