### ISSUE TITLE
Reversing interpolation compatible outlines should produce compatible outlines when outputImpliedClosingLine=True

### ISSUE THREAD

**Issue by rsheeter** [fonttools/fonttools#3093]
A subpath (sequence of drawing commands starting with a move and containing no other move) is interpolation compatible with another subpath iff both use the same drawing commands in the same order. 

For example, move, curve, close (MCZ) is compatible with all other MCZ sequences.

It should not matter:

* What the values of the associated points, if any, are
* Whether we interact with the curve as a point stream, drawing command stream (context-aware drawing commands, e.g. a quad has two points, implicitly starting at the current position), or segments (self-contained drawing commands, e.g. a quad has 3 points rather than implicitly using current as the first)

Reversing paths shouldn't cause them to become interpolation incompatible. https://gist.github.com/rsheeter/cef6cf71fa9e519c94f9f0d23906e5de demonstrates a case where this appears not to be the case.

**Comment by behdad** [comment]
I think this is legit. Suggest this patch:
```diff
diff --git a/Lib/fontTools/pens/reverseContourPen.py b/Lib/fontTools/pens/reverseContourPen.py
index a3756ab17..16c3f0209 100644
--- a/Lib/fontTools/pens/reverseContourPen.py
+++ b/Lib/fontTools/pens/reverseContourPen.py
@@ -62,7 +62,7 @@ def reversedContour(contour, outputImpliedClosingLine=False):
         if closed:
             # for closed paths, we keep the starting point
             yield firstType, firstPts
-            if firstOnCurve != lastOnCurve:
+            if firstOnCurve != lastOnCurve or outputImpliedClosingLine:
                 # emit an implied line between the last and first points
                 yield "lineTo", (lastOnCurve,)
```

**Comment by rsheeter** [comment]
I'm mildly aggravated you fixed it faster than I could type the issue up 😂

**Comment by anthrotype** [comment]
Sorry but I don't agree with the change proposed in #3094. We even reverted this very same change only a couple of months ago, and @behdad concurred with me: https://github.com/fonttools/fonttools/pull/2995 (he even merged that PR).
 
As I have tried to explain in https://github.com/googlefonts/fontations/issues/370, the two contours from Rod's gist are in fact incompatible when one looks at them as either list of points or list of segments. This is because the first contour `"M0,0 C1,1 2,2 3,3 C4,4 5,5 0,0 Z"` contains only two curve segments (or 6 points), whereas the second one `"M0,0 C1,1 2,2 3,3 C4,4 5,5 6,6 Z"` actually contains three segments (2 curves and a final closing line implied by Z, thus 7 points).

```python
>>> from ufoLib2.objects import Glyph  # this would work exactly the same in defcon, fontParts, even robofab!!!
>>> g1 = Glyph()
>>> pen = g1.getPen()
>>> pen.moveTo((0, 0))
>>> pen.curveTo((1,1), (2,2), (3,3))
>>> pen.curveTo((4,4), (5,5), (0,0))  # last point == move; closePath is no-op
>>> pen.closePath()
>>> assert len(g1.contours[0].points) == 6  # 2 curve segments, 6 points in total
>>> g1.contours[0].points
[Point(x=0, y=0, type='curve', smooth=False, name=None, identifier=None),
 Point(x=1, y=1, type=None, smooth=False, name=None, identifier=None),
 Point(x=2, y=2, type=None, smooth=False, name=None, identifier=None),
 Point(x=3, y=3, type='curve', smooth=True, name=None, identifier=None),
 Point(x=4, y=4, type=None, smooth=False, name=None, identifier=None),
 Point(x=5, y=5, type=None, smooth=False, name=None, identifier=None)]
>>> g2 = Glyph()
>>> pen = g2.getPen()
>>> pen.moveTo((0, 0))
>>> pen.curveTo((1,1), (2,2), (3,3))
>>> pen.curveTo((4,4), (5,5), (6,6))  # last point != move; closePath adds implied closing line
>>> pen.closePath()
>>> assert len(g2.contours[0].points) == 7  # 2 cubic curves + 1 line segment, thus 7 points in total
>>> g2.contours[0].points
[Point(x=0, y=0, type='line', smooth=False, name=None, identifier=None),
 Point(x=1, y=1, type=None, smooth=False, name=None, identifier=None),
 Point(x=2, y=2, type=None, smooth=False, name=None, identifier=None),
 Point(x=3, y=3, type='curve', smooth=True, name=None, identifier=None),
 Point(x=4, y=4, type=None, smooth=False, name=None, identifier=None),
 Point(x=5, y=5, type=None, smooth=False, name=None, identifier=None),
 Point(x=6, y=6, type='curve', smooth=False, name=None, identifier=None)]
```

The two only appear to be compatible when looking at them as sequence of drawing pen commands, and importantly only when leaving the closing line in the second contour implied.

If you want to make two interpolatable contours where both contain two curves and one line, and the latter line collapses onto itself with zero length in the first contour, then you need to make the closing line explicit _in both_, e.g.:

"M0,0 C1,1 2,2 3,3 C4,4 5,5 0,0 L0,0 Z"
"M0,0 C1,1 2,2 3,3 C4,4 5,5 6,6 L0,0 Z"

> move, curve, close (MCZ) is compatible with all other MCZ sequences

No, because closePath only adds a closing line when the last on-curve point != move point. When last is == move then the closing line does _not_ get added. This is the way the fonttools pens that deal with converting between points and segment-oriented drawing commands have worked since the begininng, we can't just wake up on day and change it without major headaches.

It's not just FontTools that interpret it this way. E.g. take the popular [kurbo](https://github.com/linebender/kurbo) Rust library (by our very own Raph):

```rust
use kurbo::BezPath;

let mut c1 = BezPath::new();
c1.move_to((0.0,0.0));
c1.curve_to((1.0, 1.0), (2.0, 2.0), (3.0, 3.0));
c1.curve_to((4.0, 4.0), (5.0, 5.0), (0.0, 0.0));
c1.close_path();

let segments: Vec<_> = c1.segments().collect();
assert_eq!(segments.len(), 2);
println!("{:#?}", segments);
/*
[
    Cubic(
        CubicBez {
            p0: (0.0, 0.0),
            p1: (1.0, 1.0),
            p2: (2.0, 2.0),
            p3: (3.0, 3.0),
        },
    ),
    Cubic(
        CubicBez {
            p0: (3.0, 3.0),
            p1: (4.0, 4.0),
            p2: (5.0, 5.0),
            p3: (0.0, 0.0),
        },
    ),
]
*/

let mut c2 = BezPath::new();
c2.move_to((0.0,0.0));
c2.curve_to((1.0, 1.0), (2.0, 2.0), (3.0, 3.0));
c2.curve_to((4.0, 4.0), (5.0, 5.0), (6.0, 6.0));
c2.close_path();

let segments: Vec<_> = c1.segments().collect();
assert_eq!(segments.len(), 3);   // <= no longer 2, as there's an extra line!
println!("{:#?}", segments);
/*
[
    Cubic(
        CubicBez {
            p0: (0.0, 0.0),
            p1: (1.0, 1.0),
            p2: (2.0, 2.0),
            p3: (3.0, 3.0),
        },
    ),
    Cubic(
        CubicBez {
            p0: (3.0, 3.0),
            p1: (4.0, 4.0),
            p2: (5.0, 5.0),
            p3: (6.0, 6.0),
        },
    ),
    Line(
        Line {
            p0: (6.0, 6.0),
            p1: (0.0, 0.0),
        },
    ),
]
*/
```

I don't remember where this rule about closePath actually comes from, but it's too entrenched by now and I would be very very wary to make such a change because I'm sure there is a lot of code out there that relies on this.

**Comment by anthrotype** [comment]
An `outputImpliedClosingLine` parameter only makes sense for the `PointToSegmentPen`, that is, the converter pen that translates from list of points to sequence of segment-oriented pen drawing commands, e.g. as used to draw UFO glyphs with a FontTools segment pen; and not _also_ in the `SegmentToPointPen` (converting segment pen drawing commands to points), as proposed in #3094.

The decision there is whether to emit a final explicit lineTo for a closed path, or leave it implicit. By default, this is omitted when when last point != starting point _unless_ the last point is of type "line" and has the same coordinates as the start point of the closed contour. In the latter case (and no matter whether `outputImpliedClosingLine` option is True or False) the PointToSegmentPen will always emits an _explicit_ closing lineTo to prevent this duplicate last point to be dropped by `SegmentToPointPen` (which treats the last point of a closed path as the starting point when the two overlap one another).

When I undid behdad's change in https://github.com/fonttools/fonttools/pull/2995, I explicitly added tests that verified that the outputImpliedClosingLine parameter had no effect on the number of points (or segments if you prefer) actually present in a contour after it gets reversed by ReverseContourPen. See the following test cases which pass the same input contour through the pen, only parametrizing the outputImpliedClosingLine False/True, the result does not change after reversal, there are still only two curves before and after, and that's by design and how it should be!

https://github.com/fonttools/fonttools/blob/85c80be6b693b035ba7f716e703f8e69afb00de5/Tests/pens/reverseContourPen_test.py#L138-L167

Rod's PR https://github.com/fonttools/fonttools/pull/3094/ touched exactly that very test and made it so that after reversal the contour contains an extra line segment but when outputImpliedClosingLine=True.

But that parameter is meant to simply make what was implicit explicit, not change the contour itself, the number of segments or points.

**Comment by Lorp** [comment]
This may be a tangential point, but with variable CFF2 fonts one should understand that all `rrcurveto` operators add 3 points to the contour, *even when that curve is the last part of the contour*. This means that a simple Bézier circle approximation, represented as 12 points in your font editor and in UFO, turns into 13 points inside the rasterizer. There is an implicit zero-length `rlineto` from the final point of the curve to the contour’s start point. In static fonts, there are no consequences. In variable, compilers must ensure that both the first and last curve point are moved to the same locations, so that the implied `rlineto` remains zero-length. Typically the two deltas are different since deltas accumulate around the contour.

**Comment by anthrotype** [comment]
If kurbo was not enough, I also made a little program that uses Inkscape's lib2geom to parse an SVG path into its own Geom::PathVector, count the number of segments in each subpath, reverse them using built-in Path::reversed() and asserts the number of segments does not change after reversal, finally print both original and reversed as svg path string.

https://github.com/anthrotype/2geom-toy

Here is its output with the two example contour from Rod's gist. Note how the number of segments is different:

```
$ ./reverse_path 'M0,0 C1,1 2,2 3,3 C4,4 5,5 0,0 Z'
Sub-path #0 has 2 segments and is closed
Original: M 0 0 C 1 1 2 2 3 3 C 4 4 5 5 0 0 z
Reversed: M 0 0 C 5 5 4 4 3 3 C 2 2 1 1 0 0 z

$ ./reverse_path 'M0,0 C1,1 2,2 3,3 C4,4 5,5 6,6 Z'
Sub-path #0 has 3 segments and is closed
Original: M 0 0 C 1 1 2 2 3 3 C 4 4 5 5 6 6 z
Reversed: M 0 0 L 6 6 C 5 5 4 4 3 3 C 2 2 1 1 0 0 z
```

Notice also how if I add an explicit closing line before Z, it doesn't change anything, same number of segments like before:

```
$ ./reverse_path 'M0,0 C1,1 2,2 3,3 C4,4 5,5 6,6 L0,0 Z'
Sub-path #0 has 3 segments and is closed
Original: M 0 0 C 1 1 2 2 3 3 C 4 4 5 5 6 6 z
Reversed: M 0 0 L 6 6 C 5 5 4 4 3 3 C 2 2 1 1 0 0 z
```

**Comment by anthrotype** [comment]
another gist showing how the two contours from the example would be deemed incompatible when drawn as is onto UFO glyphs and compiled interpolatably with ufo2ft, even before/without involving the ReverseContourPen:
https://gist.github.com/anthrotype/743e35caa217cb6fb555666c9f52f768

**Comment by behdad** [comment]
Rod and I chatted about this more, and I think there's a solution that might make everybody happy.

Currently when we reverse a contour, we start at the start-point of the original contour and reverse the direction. The first segment to add (or not) is the implied line-to by the closepath.

What if we instead start from the last-point of the original contour and reverse direction. Then the implied closepath line-to of the original contour will become the implied closepath of the new contour. Problem solved.

**Comment by rsheeter** [comment]
Vigorous thumbs up, ^ is better than both options we have on the table currently. I'll try it out when I have some free time.

**Comment by rsheeter** [comment]
@anthrotype the implication of this proposal is the start point will change. Does that break anything?

**Comment by anthrotype** [comment]
As I said, the problem is _not_ the reverse operation, it's a more fundamental disagreement on the definition itself of a closed path. For Rod, _every_ closed path must end with a (possibly degenerate) line segment. It's like we are saying "from tomorrow all closed contours will gain a +1 bonus point for free, courtesy of the SVG spec".

**Comment by anthrotype** [comment]
> the start point will change. Does that break anything?

It would modify all fonts in production if we were to implement that by default so I would say yes, it would be breaking.
And it would not change the fact that those two contours would be incompatible, doesn't matter in which direction you see them.

**Comment by rsheeter** [comment]
The intended result is that:

1. The intuitive definition of interpolation compatible holds
1. We do not add extra points

That seems like a pretty good outcome to me. I understand it would _modify_ fonts but it's not clear to me it would _break_ them?

**Comment by anthrotype** [comment]
I'm afraid so I'll have to repeat myself as I run out of arguments, apologies for that.
There is currently no issue with the ReverseContourPen itself. It works fine and retains the same number of segments and keeps the starting point; if fed multiple contours that were interpolation compatbile before, they will continue to be so.
The issue here is not the contour reversing algorithm, but the very definition of what constitutes a closed contour. For fonttools, UFO, and all the font editors that I know of, this is sequence of adjacient curve or line segments, where the end point of one is the starting point of the next, and where the last segment's end point coincides with the contour's starting point, not in the sense that they are distict overlapping points, but in the sense that they are the very same point. (Think of act of dragging the end of the last segment onto the starting point of an open contour, and two points seamlessly fuse into one). There is no "implied" closing line in this definition. The last segment (i.e. the one whose end point also coincides with the starting point of the closed contour) needs not be a line, it can well and often is a (cubic or quadratic) curve.
Only when expressing such closed contours as sequence of (segment-oriented) pen drawing commands (e.g. moveTo, lineTo, etc.), there arise the possibility of omitting the lineTo command for the last segment and have that be implied by the closePath command, but that is purely out of convenience but does not change the essential nature of the contour (the number of segments/points it really contains); if the last segment (whose end point coincides with starting point) is not a line, the closePath does nothing else except communicating the intent that the contour is closed, i.e. the last segment's end point _is_ the move point; if, on the other hand, the last segment is indeed a line, then it can be implied (omitted) and closePath closes off the contour with a line connecting the penultimate segment end point and the starting point; or it can be emitted explicitly and then the closePath is no-op, same as in the previous non-line case.
Rod is proposing to replace this definition of closed contour with one where the last segment is always a line, which sometimes has zero length. From this premise descends his conviction that his two example contours are interpolation compatible and fonttools should treat them as such.
I don't agree with this.

**Comment by rsheeter** [comment]
I think perhaps nuance is being lost wrt what I'm proposing. I'm suggesting that when presented via drawing commands, e.g. the pen interface, the only specs I have been able to identify - postscript/svg - seem to suggest you _should_ get the zero-length line. 

You can still eliminate unwanted points, but perhaps doing it blindly for all calls to close path on a pen isn't right, hence the churn and addition of things like always output implicit closing line to try to make it work nicely with interpolation.

**Comment by rsheeter** [comment]
Per f2f, the spec does appear to say to always emit it but that isn't helpful to fonttools due to implications on the point stream. We will explore always emitting the line, and using Behdad's revised reverse algorithm (only matters if you always emit the line) in fontmake-rs where the cost of doing something silly is much lower.
