### ISSUE TITLE
allow omissions of autogenerated values?

### ISSUE THREAD

**Issue by Pomax** [fonttools/fonttools#329]
Right now TTX will crash if values that it's going to be recomputing anyway are omitted. For instance, if I leave off the `checkSumAdjustment` field in the `<head>` table, TTX crashes, despite the fact that TTX will compute this for me based on the font it'll be writing to disk. 

It would be great if there was a compile flag like `-a` for `insert values that are recalculated by the compiler`, so that instead of a full `<head>`, we can write things like

```
  <head>
    <tableVersion value="1.0"/>
    <fontRevision value="1.0"/>
    <flags value="00000000 00001011"/>
    <unitsPerEm value="2048"/>
    <created value="Mon Aug 03 12:00:00 2015"/>
    <fontDirectionHint value="1"/>
  </head>
```

And leave the compiler to do the things it does best (but only when `-a` is specified, maintaining the current behaviour if that flag is not passed).

The same flag would reduce `<hhea>` for instance, by letting us not bother with `<reserved0>` etc elements, or anything else that has a spec-indicated default value.

**Comment by twardoch** [comment]
Yes, that would actually be wonderful. It would allow people to "author" the .ttx files independently. Especially for autogenerated values the current situation is strange, because you have to knowingly supply nonsensical values. Of course I'd still say that this is "tolerable" behavior. The thing about the .ttx format is that, as a general rule, its structure replicates the structure of SFNT tables. 

The ftx formats used by Apple, which are based on the 2001 discussions between Adobe, Apple and Microsoft ("OpenType in XML") went a slightly different path. I was part of those discussions back then, and the consensus of the group was to use attribute-heavy XML instead of element-heavy XML. The attribute-heavy XML approach conceptually allowed you to omit various aspects and only supply partial information. The element-heavy XML is different because the order of elements does matter. So the Apple/Microsoft format was, in the end, a bit more abstracted while .ttx is more low-level. I personally like .ttx for that reason — because it allows you to edit the .ttx "as if" you were editing the SFNT. 

Allowing omission of autogenerated or default fields would depart from this paradigm and would open more questions: what if we wouldn't want to just omit the strongly reserved or autogenerated fields but also some that may be supplied manually yet might also be autogenerated? It's a shift in paradigm behind how .ttx works. I'm not saying that what you're proposing is a bad idea. I see the benefits but I also see some places where caution is required. 

BTW, this request it to some extent similar (or overlaps a bit) with what I proposed: 
https://github.com/behdad/fonttools/issues/214

I think both you (here) and I (in issue #214) wish for a more "relaxed" mode of compilation, whatever that means.
