### ISSUE TITLE
OSS-Fuzz Integration

### ISSUE THREAD

**Issue by ennamarie19** [fonttools/fonttools#3542]
My name is McKenna Dallmeyer and I would like to submit fonttools to OSS-Fuzz. If you are not familiar with the project, OSS-Fuzz is Google's platform for continuous fuzzing of Open Source Software. In order to get the most out of this program, it would be greatly beneficial to be able to merge-in my fuzz harness and build scripts into the upstream repository and contribute bug fixes if they come up. Is this something that you would support me putting the effort into?

Thank you!

**Comment by behdad** [comment]
Hi McKenna,

Thanks for your interest. Someone has already done that:

  https://github.com/google/oss-fuzz/tree/master/projects/fonttools

However, it's not used, because FontTools Python code is not written to tolerate bad input and just bails with random exceptions across the codebase.

If you have a more useful way to fuzz something in FontTools, by all means, please submit a PR!
