### ISSUE TITLE
Support Type1 Multiple Masters

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#398]
Would it be hard to support reading Type1 Multiple Masters? It might be helpful for rescuing old font files, eg. for converting historic designs to UFO. See [Specification](http://partners.adobe.com/public/developer/en/font/5015.Type1_Supp.pdf) and  [Example font](http://www.lucasfonts.com/porno/). The sample font is not exactly “safe for work,” but I couldn’t find other freely downloadable MM fonts on the web. But afaik quite a few MM fonts were made in the 1990ies.

**Comment by twardoch** [comment]
It's not needed (and it's somewhat hard). Adobe's AFDKO is now open source (Apache 2), and allows instance generation from old MMs into Type 1, and subsequent conversion to OTF. No need to duplicate the effort, I'd say. 

But since you ask, I'm gonna soon post my "longer-term wishes list" aka "roadmap" for fontTools here soon :)

**Comment by twardoch** [comment]
See https://github.com/behdad/fonttools/issues/399

**Comment by behdad** [comment]
I'd say this is too much of a distraction.
