### ISSUE TITLE
[subset] Aggressive vs. conservative OTL feature code removal

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#43]
From Adam:

I'd like to elaborate on what I wrote in the
https://groups.google.com/forum/#!topic/fonttools/lCwa9N1NEIY
thread.

There is a bit of "chicken and egg" interaction between the specified glyphs and specified features.

Currently the pyftsubset tool does the following:
a) take the specified glyph list
b) take the specified OT feature list
c) form the target glyph list: expand the specified glyph list by adding to the specified glyph list the necessary component glyphs, and the GSUB variants required by the specified OT feature list
d) form the target OT feature list as a direct copy of the specified OT feature list
e) remove all glyphs not in the target glyph list
f) remove all features not in the target OT feature list

As I wrote some time ago, other subsetters (such as SIL Martin Hosken's ttfsubset, part of the Font::TTF Perl package) is more forgiving in terms of what OT Layout stuff to remove. ttfsubset will keep all feature code which is covered by the target glyph list while your subsetter will remove a lot.

More specifically, Martin Hosken's ttfsubset has a different step (d). While pyftsubset uses the specified OT feature list as the target feature list, ttfsubset will construct the target OT feature list by intersecting the original OT feature list with the target glyph list.

In other words:
- Behdad's pyftsubset performs "aggressive feature removal"
- Martin Hosken's ttfsubset performs "conservative feature removal"

In a revised implementation of pyftsubset, step (d) could be different (perhaps only when an option such as --preserve-other-features is specified):

d) form the target OT feature list: expand the specified feature list by adding to the specified OT feature list those rules, lookups and features which are covered by the target glyph set

This means that right now, in pyftsubset we have a "must" glyph list and a "must" feature list (specified by the user) PLUS a "may" glyph list (result from the expansion). What I'm requesting is that we have a must glyph list, a must feature list, a may glyph list AND a may feature list.

EXAMPLE 1

Consider a font where I have the glyphs: /A/B/C/D/a/b/c/d/a.smcp/b.smcp/c.smcp/d.smcp and I have the following feature definitions (using FEA syntax):

feature smcp {
  sub [a b c d] by [a.smcp b.smcp c.smcp d.smcp];
} smcp;
feature c2sc {
  sub [A B C D] by [a.smcp b.smcp c.smcp d.smcp];
} c2sc;

When I run pyftsubset and specify the glyphs to keep: /A/B/a/b/a.smcp/b.smcp (or just /A/B/a/b), and I specify the feature to keep "smcp", then I'll get a font which will have the glyphs: /A/B/a/b/a.smcp/b.smcp but will only have the feature definition:

feature smcp {
  sub [a b] by [a.smcp b.smcp];
} smcp;

while the "c2sc" feature will be dropped completely.

Martin Hosken's ttfsubset is smarter. It won't do the automatic expansion of the specified glyph list, so I have to explicitly tell it to keep the glyphs: /A/B/a/b/a.smcp/b.smcp, but after the subsetting, I'll get the same glyph set as from pyftsubset (/A/B/a/b/a.smcp/b.smcp), but I'll get the feature definitions:

feature smcp {
  sub [a b] by [a.smcp b.smcp];
} smcp;
feature c2sc {
  sub [A B] by [a.smcp b.smcp];
} c2sc;

In other words, since the target glyph list _does_ have all glyphs necessary to form a _sensible subset of the "c2sc" feature_, Martin Hosken's ttfsubset will retain a subsetted variant of the "c2sc" feature, while pyftsubset will drop "c2sc" completely because I didn't specify it explicitly.

EXAMPLE 2

Let's say I have a font that defines features such as "onum" and "pnum" which replace default figures with the appropriate variants, and it also has "lnum" and "tnum" that do exactly the reverse. In pyftsubset, if I specify to include the features "onum" and "pnum", then only those will be included, and "lnum" and "tnum" will be removed. In Martin's ttfsubset, all four features will be retained.

EXAMPLE 3

Let's say I have the glyph set: /a/b/a.ss01/b.ss01/a.ss02/b.ss02 and I have the feature code:

feature ss01 {
  sub [a b] by [a.ss01 b.ss01];
} ss01;
feature ss02 {
  sub [a b] by [a.ss02 b.ss02];
} ss02;
feature salt {
  sub a from [a.ss01 a.ss02];
  sub b from [b.ss01 b.ss02];
} salt;

With pyftsubset, if I want to keep the glyphs /a/b/a.ss01/b.ss01 and the "ss01" feature, I'll only get this:
feature ss01 {
  sub [a b] by [a.ss01 b.ss01];
} ss01;

In Martin's ttfsubset, if I specify to keep the glyphs: /a/b/a.ss01/b.ss01, I'll get this:
feature ss01 {
  sub [a b] by [a.ss01 b.ss01];
} ss01;
feature salt {
  sub a from [a.ss01];
  sub b from [b.ss01];
} salt;

Mind you, with pyftsubset, it's virtually impossible to get the (useful) result that ttfsubset produces, because, given the original character set, if I tell pyftsubset to keep the glyphs /a/b and to keep "ss01" and "salt" features, I'll get the original glyph set (including /a.ss02/b.ss02, which I actually don't want).

So Martin's ttfsubset will go beyond just following the specified features, it'll also retain feature code which is not explicitly specified by the user but IS covered by the target glyph set. In other words, ttfsubset operates more "synergetically". I hope you get the idea :)

Such "synergetic" operation would make sense in pyftsubset: if I tell pyftsubset that I want certain glyphs AND certain features, it should give me those glyphs and features but might ALSO give me other features which are covered by the glyph set I'm getting anyway. The thing is, if I also ask for those other features, then pyftsubset will keep expanding the requested glyph list "ad infinitum", so the subset will make less and less sense.

So my question to Behdad is: do you plan/consider to implement something like this, i.e. switch from "aggressive" to "conservative" feature removal? Or does it conflict with your implementation goals/principles for pyftsubset?

Followup:

> I _think_ --layout-features='*' should do what you are asking for.  Can you test?

Unfortunately, it does not do what I'm asking for. I'll send you an example. 

He then sent me the font files that I should have in my inbox.

**Comment by twardoch** [comment]
Another way to implement this would be a "--strict-glyphset" mode which simply enforces a specified glyphset. 

In this mode, all the options in the "Initial glyph set specification" section of the docstring would actually specify the FINAL glyph set. 

The options in the "Glyph set expansion" section of the docstring would have no effect (though the glyph set would still be expanded by including necessary component glyphs). 

The pruning of the OTL features would then be made so that only the rules that apply to the final glyph set are kept, and other rules are removed. 

I could live with that. I could run pyftsubset once on the original font using the normal mode where I'd specify a set of Unicodes and common features to keep (liga, ccmp, calt etc.). 

I'd then retrieve the glyph names of the subsetted font and remove the font. 

Then I would run pyftsubset again on the original font, this time in strict glyphset mode. I would supply the glyph names that I just retrieved PLUS the few extra glyph names such as "c_t" if I want to keep just one dlig ligature. 

As a result, I would get the glyphset and features identicsl to the first result PLUS the "c_t" glyphs AND the dlig feature with only the rule that subs c t by c_t. All the other dlig rules would be gone. 

Alternatively, even better, would be that it is done in one pass. Then, just one option were needed: --[no-]partial-features

If --partial-features is specified AND the user used --gids[-file] or --glyphs[-file], pyftsubset would ensure that any feature portions (from all features, not just those specified with --layout-features) which affect any glyphs specified in the desired glyphset are kept. 

So if I specify my glyphs as 
a b c d e f g h i j k l m c_t
specify --layout-features=liga and --partial features, pyftsubset will expand the glyphset to
a b c d e f g h i j k l m c_t f_i f_l
and keep the full "liga" feature (for f_i and f_l) and a partial "dlig" feature (only with the c_t rule, all other rules are removed). 

THAT really would be something!

**Comment by twardoch** [comment]
Another example where this would be useful: imagine a font which has a "locl" feature specified for many languages: Turkish, Romanian, Polish, Dutch etc. I'm making a subset where I want all letters of the Turkish alphabet AND the "i.TRK" glyph used in locl for Turkish (along with the appropriate locl rule for THAT glyph). But I don't want the Polish, Dutch etc. locl rules. 

So I should be able to specify a-z and i.TRK in my glyphset (using --glyphs) and say 
--layout-features='' --partial-features

I'd then get a font with a-z and the i.TRK glyph along with the "locl" feature that ONLY subs the i with i.TRK for Turkish.

**Comment by khaledhosny** [comment]
For the last use case, I think the subsetter should support specifying script / language and only keep lookups related to them, that would be a more general way to do it.

**Comment by twardoch** [comment]
Well, yes, that would be practical as well. Perhaps this was not the best example. But I wasn't making a point specifically about "locl". 

Maybe "salt" (stylistic alternates) is a better example. The "salt" feature gives access to a number of alternate glyph forms that may be complete unrelated. "salt" can provide the mappings eg: a -> a.salt, g -> g.salt, zero -> zero.salt, ampersand -> ampersand.salt. 

A user may be very interested in having s font that only gives him access to "ampersand.salt" but not the other ones. 

Also, --partial-features would be the best (or only) way to implement a glyph palette-based subsetting GUI tool. A user would be presented with a table with all glyphs contained in the font (glyph map, glyph palette). The user just clicks on (enables) the glyph cells they wish to retain in the subset, then initiates the subsetting. 

The tool takes then just the list of glyph IDs of the glyphs that need to be retained, calls the subsetter with that --gids list and the --layout-features='' --partial-features options. 

The resulting font has the requested glyphs (plus component glyphs if needed) and JUST the features that are needed to access those glyphs (and within the features, only the rules that pertain to the retained glyphs). 

Currently, achieving this is not possible (except with another subsetter like Hosken's ttfsubset but that one is often buggy). 

Also, this type of operation would be necessary if one were to implement the functionality described in 
https://github.com/behdad/fonttools/issues/214

**Comment by twardoch** [comment]
In short: I just want to feed in a desired glyphset (list of glyph names or IDs), and want the subsetter to subset all sfnt tables that it can subset to match that desired glyphset. 

I can have my custom code decide which glyphs I want using any methods I want, and I want to run the subsetter in an explicit way. 

The feature-driven glyphset expansion is nice but very often I don't want the subsetter to decide which glyphs I need because I already know which glyphs I need :) I just want it to do exactly what I tell it to do :D

**Comment by twardoch** [comment]
(And yes, last year I had to go through a very complicated process to build the Carlito fonts for Android. This functionality I'm requesting here would have helped me a lot, had it existed at the time.)

**Comment by ruud-v-a** [comment]
I have a use case where I know the exact text that will be displayed, so I can generate a list of glyph names that I need for that. At the moment, if I include glyphs for discretionary ligatures, the glyphs will be included in the final font (I can see them with `fontTools.inspect`, though they lose their name), but neither Firefox nor Chrome renders them. Setting `options.layout_features.append('dlig')` makes the discretionary ligatures work, but it also gives me glyphs that I did not ask for. It would be nice if there was a way to skip step **c** in the first post.

**Comment by khaledhosny** [comment]
You will still need the intermediate glyphs for the feature to work, because the `cmap` table maps characters to initial glyph IDs then the `dlig` feature maps them to the ligatures, if the initial glyph IDs are skipped there will be nothing to be substituted.

**Comment by ruud-v-a** [comment]
The intermediate glyphs are not the problem, I do include those. To give a concrete example, say I want to typeset the text “shell script”. My font has, among others, the following discretionary ligatures: st, ct, ip, it, sp, ch, sp, and sh. I ask for the following glyphs: s, h, e, l, c, r, i, p, t, s_h. (I don’t want the i_p glyph to be included.) So in addition to s_h, s and h are both specified separately. However, now I also get all of the other ligatures, because they are ligatures of glyphs that I specified, but they are not used for the text “shell script”. (Well, the i_p glyph is, but I wanted to exclude that one.)

**Comment by twardoch** [comment]
@ruud-v-a Exactly :)
