### ISSUE TITLE
Merge TrueType bytecode manipulation library

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#446]
This is work led by Patrick Lam (@patricklam), a professor at University of Waterloo.  Originally, Wenzhu Man (@wenzhuman) did a masters project and produced this document:

  https://uwspace.uwaterloo.ca/bitstream/handle/10012/9116/Man_Wenzhu.pdf

Later on, Pat recruited Eduardo Hauck (@ehauckdo) to continue the project.  Anyway, all the work is in their fork of fonttools.  We should review and merge this work, and then see what to do with it:

  https://github.com/wenzhuman/fonttools/commits/master

**Comment by patricklam** [comment]
There is also a paper under submission to the Compiler Construction
conference which describes a newer version of the work more briefly.

I'd like to polish the code a bit before getting it reviewed. Perhaps I'll
have time to do that next week. I do think it should be eventually merged.

**Comment by brawer** [comment]
Very interesting thesis!

@wenzhuman and @patricklam: Curious, have you considered doing your optimizations in Static Single Assignment form? Data flow analysis is _much_ easier when the program is in SSA representation, which is why SSA has become standard practice in compiler construction about 20 years ago. Now, it isn’t immediately obvious why one couldn’t compute dominance frontiers for TrueType, but of course you’ve must have thought much more about this. Was there a particular reason for _not_ using SSA?

Regarding the limitations in section 7.2 of the thesis: Curious, what is special about JROF, JROT and JMPR? Aren’t these just normal control flow instructions that end a basic block, similar to (for example) conditional branches in Java bytecode?

**Comment by patricklam** [comment]
Thanks Sascha. We also submitted a paper to Compiler Construction, which didn't get in this year; there'll be a resubmission in the future. The paper is attached.
[16.cc.fonts.pdf](https://github.com/behdad/fonttools/files/129867/16.cc.fonts.pdf)

There's not just upside to SSA form. Usually you would construct SSA after you have the three-address code in any case. And the problem (which people don't talk about so much, but which is real) is that when you try to manipulate the SSA form, you can easily break the invariants and produce invalid SSA. Most of the things you try to do with SSA form it turns out you can also do without SSA form.

We are using a structured representation of the bytecode, where if blocks are strictly nested. The jump instructions break that. The solution is probably to duplicate code.

**Comment by behdad** [comment]
BTW, see also: http://home.kabelfoon.nl/~slam/fonts/tticomp.html

**Comment by twardoch** [comment]
And http://xgridfit.sourceforge.net/ — for the sake of completeness.
