### ISSUE TITLE
missing attributes

### ISSUE THREAD

**Issue by typemytype** [fonttools/fonttools#447]
Building an `TTFont` in an object has missing attributes, like `CompCount` in `Ligatures`. Those are present when opening from disk. There should not be a difference in the API based on the source (read from disk or read from object)

Other required attributes, like `Format` in some tables/records are being deleted in `.postread()`. 

For example Tal's Compositor requires those attributes.

I understand that those attributes are most of the time extracted from existing data in the `TTFont` object. This is what most of the `.preWrite()` does.

Would it be an idea to make those attributes optional but still extract them when they are requested?

silly example:

``` Python
class Dummy(object):

    def __getattr__(self, attr):
        if not attr in self.__dict__:
            if attr == "CompCount":
                print "calculate CompCount"
                return 5
            elif attr == "Format":
                print "calculate Format"
                return 1
        return self.__getattribute__(attr)
```

and is there a list of those attributes that can be auto-extracted?

As already discussed a bit here https://github.com/typesupply/compositor/issues/7#issuecomment-97274458

thanks

**Comment by anthrotype** [comment]
> There should not be a difference in the API based on the source (read from disk or read from object)

Do you mean "reading from font file" vs "importing from XML"?
If yes, then this issue might be the same as https://github.com/behdad/fonttools/issues/141.
Basically, because of such missing attributes, it's impossible to import from XML and save to XML directly, without first having saved to TTF.

> is there a list of those attributes that can be auto-extracted?

Not that I know of.. But once we have such a list, then your solution would be the most appropriate.

**Comment by typesupply** [comment]
> Do you mean "reading from font file" vs "importing from XML"?

Not exactly. We've been experimenting with going ufo -> feaLib -> compositor. When we do this, compositor chokes because not all of the attributes are present in the GSUB objects. If we go ufo -> ufo2fdk -> makeotf -> TTFont -> compositor, everything is there. I'm pretty sure that this is happening because necessary attributes are only set during a load from file.

I don't think this is a feaLib issue. I think it's a issue much deeper in the ttLib GSU/GPOS objects.

I'll make a clean test case soon to show what we're seeing.

**Comment by anthrotype** [comment]
Oh, I see.
Then you could try to save the TTFont to a temporary file or stream, and then reload it from there, before passing it to compositor. The missing attributes should be recomputed upon saving.
But I understand this is not ideal.

**Comment by behdad** [comment]
Cosimo, we should fix this (and the related XML issue) next week.

**Comment by behdad** [comment]
FWIW you don't have to save the TTFont to a temp file, you can compile then recompile the table(s).  Like this:
https://github.com/behdad/fonttools/blob/462496ce327d58a1a72c23aafd339b2619536bb5/Lib/fontTools/mtiLib/__init__.py#L1106

**Comment by behdad** [comment]
I had to revert the last change.  Will finish it later.

**Comment by behdad** [comment]
This is hard and brittle to fix...
