### ISSUE TITLE
[feaLib] Do not de-duplicate lookups

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#448]
Currently, feaLib is merging lookups that have the same content in oder to make the resulting font smaller. However, this space-saving optimization changes the semantics of the resulting feature file: OpenType layout engines do not execute the lookups in order; instead, they sort lookups by numeric ID. Therefore, @behdad recommends to remove this optimization.

**Comment by anthrotype** [comment]
I just got bitten by this. I got unexpected behaviour when applying multiple features (in my case was frac and numr), because the order of the lookups in the compiled GSUB didn't match the order in which lookups had been explicitly defined in the feature file.
I wonder if it would be better to disable such an optimization...
BTW, does makeotf also do this?

**Comment by khaledhosny** [comment]
I think any optimization that changes the order of lookups is dangerous since the order often has important semantics and must be preserved.

**Comment by behdad** [comment]
Plus, the bytes are reused by compiler anyway...

**Comment by justvanrossum** [comment]
@anthrotype can you confirm your problem is solved by removing lines 463 to 469 from feaLib/builder.py?

**Comment by anthrotype** [comment]
yes, that's exactly what I did to fix it, but I wanted to check with others before committing anything. As far as I can tell, there seems to be unanimity to disable the optimization. I'm off at the moment, I can apply the patch tomorrow, or any of you can do it.

**Comment by justvanrossum** [comment]
Yeah, that optimization is definitely wrong.
