### ISSUE TITLE
TTFont() constructor always loads the entire file into memory

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#482]
@justvanrossum pointed out today, that reading the entire font into memory can be visibly inefficient, specially since we don't have any _sniffing_ api, so trying to load the font is the only way.

Indeed, we knew that we want to fix this later when we have proper options infrastructure, but just filing here so we keep track.  Maybe we can skip the read if lazy=True at least?

Independently, we should have sniffing API that returns font-type of a file.

**Comment by justvanrossum** [comment]
Later I realized it's not just sniffing I'm worried about: I wrote scripts that go through an entire library and finds and reports "problems" in light-weight tables, say, name table, head, OS/2. I'm pretty sure that would be noticably slower with today's fonttools.

**Comment by anthrotype** [comment]
Hi Just,

You must be referring to this commit:
https://github.com/behdad/fonttools/commit/356c92341140e7e0a0bce1e4c1ad2a61dc24aeb1

The reason we did that was to be able to save a TTFont to the same input file (overwrite): 
https://github.com/behdad/fonttools/issues/302

Sure, we could skip loading the whole font in memory when lazy==True, like @behdad suggests.

I'm not sure I understood the point about of the lack of *sniffing* api which would force us to try loading the entire font in memory. Are you perhaps referring to the `macUtils.getSFNTResIndices`? 

https://github.com/behdad/fonttools/issues/302

That occurs even before we wrap the file in a BytesIO stream.
Or maybe you mean in `fontTools.ttLib.sfnt.SFNTReader` class, where we do "sniff" the first four bytes in order to return either a generic SFNT or a WOFF2 reader?
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/sfnt.py#L31

Of course, I understand why we need a sniffing api in general (we could build on `guessFileType` function in ttx module). It's just I didn't get the connection with the loading-input-file-in-memory thing.

**Comment by justvanrossum** [comment]
The connection to sniffing was that I (perhaps naively) sometimes just attempt to create a TTFont() instance to see if a particular file is indeed a file TTFont can handle. But don't worry, the new 'lazy' behavior solves those needs and more.

**Comment by behdad** [comment]
Closing in favor of https://github.com/fonttools/fonttools/issues/2252
