### ISSUE TITLE
Subset SVG table with pyftsubset 

### ISSUE THREAD

**Issue by RoelN** [fonttools/fonttools#534]
It's noted in [this issue](https://github.com/behdad/fonttools/issues/376) that the subetter doesn't know how to subset the SVG table. It would be nice if it did as SVG fonts can use all the optimization they can get :)

Currently, I have to explicitly tell pyftsusbet to leave the SVG table alone, as per instructions in the mentioned issue, so that should change too:

```
pyftsubset --verbose --no-subset-tables+='SVG ' --drop-tables-='SVG '  my-test-font.otf  --text='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890ao123%‰€$¢£¥áâàäåãæçéêèëíîìïıñóôòöõøœšßúûùüýÿžÁÂÀÄÅÃÆÇÉÊÈËÍÎÌÏÑÓÔÒÖÕØŒŠÚÛÙÜÝŸ.,:;-–—•·...“‘’‘‚“”„‹›«»/\?!¿¡()[]{}†*&©®@#§+×=_°|'
```

**Comment by behdad** [comment]
You can't just do that since SVG docs have references to glyph ids in them.  If glyphIDs change (which does in subsetting unless you choose all glyphs), then the SVGs need to be rewritten.  That's not impossible.  Removing unused parts of the SVGs is harder.

**Comment by RoelN** [comment]
Ah, I see. I was working with a font that had one SVG doc per glyph, so it seemed simple. I suppose any subsetting should be done in the original font design software, or by hand.

**Comment by anthrotype** [comment]
The way I would go about this is:

1) Remove any svg document whose startGlyphID..endGlyphID range doesn't intersect the requested subset
2) For each remaining SVG document, start with the set of all "glyph{gid}" identifiers in the range covered by that svg document that also intersect our requested font subset. Parse the SVG document with etree, skip the sub-trees of the glyphs whose id is not in the set of ids to keep; expand this set by all the other element ids that are referenced (via `xlink:href` attribute) from anywhere inside the subtree we're traversing; keep a set of visited node ids, and continue traversing until no more elements in the set of ids to keep is unvisited;
3) make a new tree only containing elements whose id is in the set to keep; remove id-less elements unless contained within elements whose id should be kept; before removing an element, if any of its children needs to be kept, move these up as siblings; maybe also group top-level elements that are not `<g>` glyphs under a global `<defs>` at the top of the document.
4) renumber glyph indices, both the startGlyphID and endGlyphID of the svgDoc container, and the `id="glyphXX"` attributes inside it

**Comment by behdad** [comment]
That should work, yes. Now find someone to do it please. :))

**Comment by anthrotype** [comment]
In the OT-SVG spec, I read

> Note: Two or more records can point to the same SVG document. In this way, a single SVG document can provide glyph descriptions for discontinuous glyph ID ranges.

That's nice, as it could make subsetting a little easier since we wouldn't need to split SVG docs when subsetting makes the leaves gaps in the GID ranges: we can simply make several records with continuous ranges whose offset points to the same SVG document containing discontinuous GID ranges.

However the current implementation in `fontTools.ttLib.tables.S_V_G_`  duplicates these shared SVG documents while decompiling the SVG table, but without also trying to share the offsets upon compiling, so in the re-compiled table all records get unique offsets even when the pointed-to bytes may be identical.

I could fix that by building a cache or map of SVG docs to offsets as these are first seen and reuse the offsets for any following records that share the same SVG content.
Or I could rewrite the OT-SVG table as an otData-driven class (like the layout tables) and get the offset sharing for free...

**Comment by anthrotype** [comment]
We can finally subset OT-SVG fonts! 🥳 
It should work with simple fonts (with single color glyph per SVG document, like most of the OT-SVG fonts out there) as well as more complex ones with lots of cross-references.
Please test your fonts and send us bug reports. I'll make a release soon.
