### ISSUE TITLE
[Wish] "Dump tables as hex data" option in TTX

### ISSUE THREAD

**Issue by Arno-Enslin** [fonttools/fonttools#560]
There should be a "Dump tables as hex data" option in TTX.

My actual solution is, to temporarily rename some py files in fontTools\ttLib\tables\ with the help of batch files like these:

```
@echo off
call FDKvars

for %%f in (%tab%*_?_*.*) do (
if not %%~nf.py==C_F_F_.py if not %%~nf.py==_g_l_y_f.py if not %%~nf.py==_h_e_a_d.py if not %%~nf.py==_h_h_e_a.py if not %%~nf.py==_l_o_c_a.py if not %%~nf.py==_m_a_x_p.py if not %%~nf.py==_p_o_s_t.py if exist "%%~dpnf.pyc" del "%%~dpnf.pyc"
if not %%~nf.py==C_F_F_.py if not %%~nf.py==_g_l_y_f.py if not %%~nf.py==_h_e_a_d.py if not %%~nf.py==_h_h_e_a.py if not %%~nf.py==_l_o_c_a.py if not %%~nf.py==_m_a_x_p.py if not %%~nf.py==_p_o_s_t.py if exist "%%~dpnf.py" ren "%%~dpnf.py" "%%~nf.pyNotHex"
)
@echo most tables in Hex-Mode now
ping 127.0.0.1 -n 3 >NUL
```

and back to decompile mode:

```
@echo off
call FDKvars

for %%f in (%tab%*_?_*.*) do (
if exist "%%~dpnf.pyc" del "%%~dpnf.pyc"
if exist "%%~dpnf.pyNotHex" ren "%%~dpnf.pyNotHex" "%%~nf.py"
)
@echo all tables in Decompile-Mode now
ping 127.0.0.1 -n 3 >NUL
```

The TTX command for that would look like this

**TTX -s** (split all tables in decompile mode) **-thex** (except from the following ones, which you put out as hex data)

---

And if you want to split all tables in hex mode:

**TTX -s** (split all tables) **-hex** (in hex mode)

**Comment by anthrotype** [comment]
May I ask why you want to dump tables to ttx as hex data in the first place?
If you don't want to decompile some tables, then don't dump them (`-x`), or specifically dump only the tables that you wish to decompile (`-t`). Then you can merge (`-m`) the ttx files back into the original binary font.

If it's because you wish to convert your fonts to WOFF in a "lossless" mode, as you wrote in https://github.com/adobe-type-tools/afdko/issues/113, then we could find a better solution which doesn't require having to first dump a font to TTX and then recompile it to a different flavor.

**Comment by Arno-Enslin** [comment]
No. Woff is not the reason for this request:

A few years ago I had a font family, that TTX was unable to dump. But the GPOS table was missing in two of the fonts. But I have known, that kerning and Glyph order was the same in all styles of the family. Then I tried to make out, how TTX dumps the DSIG table as hex data. With success. I simply had to rename the py file in "fontTools\ttLib\tables", that is responsible for the dump of the GPOS table. I dumped the GPOS table with TTX as hex data and merged it into the font files, in which the GPOS tables was missing.

Maybe the GPOS table was corrupt. Maybe not. Maybe to complex for TTX. But the kerning of the repaired fonts worked in Indesign, Office and so on.

Except from that I don't trust in TTX for 100% with regard to it's abilities not to damage anything in fonts. So, sometimes I merge tables in as hex data.

**Comment by twardoch** [comment]
Arno, when I’m sure that the tables are “compatible” (in terms of glyph sets), I use the `sfntedit` tool from AFDKO, which can dump, delete and add SFNT font tables as pure binary chunks. Your request for a hex mode for ttx may be useful, but I think you can achieve most of what you wish by combining the use of `ttx` and `sfntedit`.

**Comment by Arno-Enslin** [comment]
Yes, but I assume, that it would be very easy (not for me) to modify TTX in that way, because it just had to ignore the py and pyc files in "fontTools\ttLib\tables". And the advantage is, that you can store the hex data of the one and the dumped data of another table in the same ttx file.

And another advantage: TTX is faster, if it hasn't to dump all tables. So you can dump only the tables that you want to edit. But the other tables are present as hex data in the same file. But note, that this does not work with all tables. There are tables, that ttx must dump, if you want to compile the ttx file.

**Comment by justvanrossum** [comment]
So the reason you want this feature is because some years ago TTX failed to dump a GPOS table. Or maybe the table was corrupt. And you don't 100% trust TTX. But you don't give us any leads or even reasons, so you're going by pure speculation at this point and are pretty much spreading rumors.

In short:
- If FontTools/TTX fails to dump a table, and the table is not corrupt, it's a bug and we should know about it
- If FontTools/TTX damages font data in any way, it's a bug and we should know about it.

Adding a hex feature is not helping any of this.

**Comment by twardoch** [comment]
@justvanrossum Indeed! I shall add that brute-force merging of even borderline corrupt tables into fonts, especially webfonts, is quite counter-productive, especially since the OT sanitiser library built into Firefox and Chrome will most likely reject such tables anyway. 

The fontTools developers have a great track record of fixing bugs, especially since the project moved to Github and is now cared for by a group of people. Therefore, I agree with Just — the best way to address the kind of problems Arno mentioned is to fix them rather than working around them, especially that it is actually very attainable.

**Comment by Arno-Enslin** [comment]
Till the bug is fixed, it helps. Except from that I had more arguments: The file sizes and the speed. **If that option is easily to add,** the I don't see any reason, why it not should be added. As I said: Most users would not make use of it. But I assume, that there are other options, which most users never have tried.

**Comment by twardoch** [comment]
I may have another reason for the kind of option Arno proposes, actually one of the reasons I sometimes use `sfntedit`: fontTools/TTX keys various glyph-related table entries by glyph name, which is mostly great but occasionally a limitation. It had happened to me a number of times that I had to move data between fonts with identical glyphsets where one had “development” glyph names in the `post` table while the other had “final” or no glyph names at all. 

This difference made the re-using the `.ttx` dumps incompatible between the fonts. In that case I myself did use `sfntedit` but had fontTools had such a “hex” option, I would have used that. 

I still wouldn’t consider this feature request a high priority, but I can think of “legitimate” cases where it would be of use.

**Comment by Arno-Enslin** [comment]
> I still wouldn’t consider this feature request a high priority

No indeed, it hasn't high priority. It is just a personal wish. And I naturally would prefer, if all important bugs become fixed first.

**Comment by HinTak** [comment]
Actually I added this feature to the Font Validator ( https://github.com/HinTak/Font-Validator ) a month ago and not pushed out to the public branch yet. The reason why I added this was that people was talking about Windows 10 starting to using the - antique?- Truetype "meta" table in new ways. So I extended the generic "unknown" table to support hex dumps, just so I can look at the non-OT table and see what's inside.
