### ISSUE TITLE
[feaLib] handling of mixed single and multiple or ligature substitutions

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#612]
If I have a feature like this:

```
feature isol {
 sub a by A;
 sub b by B C;
} isol;
```

feaLib will generate two lookups, a single substitution lookup and a multiple substitution one. But IMO it should have been a single multiple substitution lookup, as the first rule can be seen as a multiple substitution lookup with just one replacement glyph. The same happens when mixing single substitutions with ligature substitutions.

In many of my fonts this results in 10s of lookups which can slow the OpenType layout processing in some implementations. It does not help that the feature syntax does not provide any way to make this explicit, since the three different substitution subtypes use the same syntax.

It gets even worse with named lookups, a lookup like this will not even compile:

```
lookup isol0 {
 sub a by A;
 sub b by B C;
} isol0;
```

FontForge used to handle this gracefully and guess the right lookup type in these situations. I didn’t check with FDK does here.

**Comment by brawer** [comment]
Currently, it seems that feaLib and FDK produce identical output for these snippets. But of course that doesn’t mean they absolutely have to: feaLib could certainly make optimizations which makeotf doesn’t make, as long as everyone conforms to the published specification. However, it would add friction for font designers if a given feature file is accepted by some implementations but rejected by others.

Here’s the output from running makeotf v2.0.90 on the first example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="true" ttLibVersion="3.0">

  <GSUB>
    <Version value="1.0"/>
    <ScriptList>
      <!-- ScriptCount=1 -->
      <ScriptRecord index="0">
        <ScriptTag value="DFLT"/>
        <Script>
          <DefaultLangSys>
            <ReqFeatureIndex value="65535"/>
            <!-- FeatureCount=1 -->
            <FeatureIndex index="0" value="0"/>
          </DefaultLangSys>
          <!-- LangSysCount=0 -->
        </Script>
      </ScriptRecord>
    </ScriptList>
    <FeatureList>
      <!-- FeatureCount=1 -->
      <FeatureRecord index="0">
        <FeatureTag value="isol"/>
        <Feature>
          <!-- LookupCount=2 -->
          <LookupListIndex index="0" value="0"/>
          <LookupListIndex index="1" value="1"/>
        </Feature>
      </FeatureRecord>
    </FeatureList>
    <LookupList>
      <!-- LookupCount=2 -->
      <Lookup index="0">
        <!-- LookupType=1 -->
        <LookupFlag value="0"/>
        <!-- SubTableCount=1 -->
        <SingleSubst index="0">
          <Substitution in="a" out="A"/>
        </SingleSubst>
      </Lookup>
      <Lookup index="1">
        <!-- LookupType=2 -->
        <LookupFlag value="0"/>
        <!-- SubTableCount=1 -->
        <MultipleSubst index="0">
          <Substitution in="b" out="B,C"/>
        </MultipleSubst>
      </Lookup>
    </LookupList>
  </GSUB>

</ttFont>
```

For the second example, makeotf v2.0.90 rejects it (just like feaLib), printing this error: “Lookup type different from previous rules in this lookup block”.

**Comment by moyogo** [comment]
This might be related to a limitation in some font shaper.

Le sam. 28 mai 2016 20:15, Sascha Brawer <notifications@github.com> a
écrit :

**Comment by khaledhosny** [comment]
VOLT also creates such lookups, so I think it is unlikely that there is a problem in applying such lookups. Anyway, it shouldn’t be the compiler job to decide which kinds of lookups are allowed or not and currently the syntax does not provide any other way to handle such mixed lookups. Working around this is easy for single substitutions, but things gets complex for contextual substitutions that reference other lookups since splitting such a lookup into two will complicate things needlessly.

So the question now is, should we just do what FontForge did since the spec is silent about this (AFAICT) or raise the issue with AFDKO first?

**Comment by brawer** [comment]
@readroberts, what do you think? (See bug history for context).

**Comment by readroberts** [comment]
The current implementation of feaLib and the FDK are at least consistent.   A lookup can contain only one type of rule (excepting kerning) and mixed rules are handled only by isolating them in separate lookups. This can't be done in named lookups, since a named lookup can be only a single lookup.

I agree that the 'isol' feature example shows a case where it would be useful to deal with mixed rules by promoting single substitution rules to more complex substitution rules in order to avoid a proliferation of lookups,  and that this points to a need for a change in the feature file spec to support this. If anyone has any good ideas, let's hear them. I do not favor having to add something to each rule to force it be a particular type. I am a little leery of having the implementation silently change rule types.  My best idea so far is to add an attribute keyword for a feature or lookup that specifies the common substitution type to which all rules should be promoted, if possible.  The could be a new keyword/value pair like "preferredRuleType oneToMany;". Any rule than cannot be promoted to the preferredRuleType wold be handled by starting a new lookup, as with the current logic.

**Comment by khaledhosny** [comment]
I think a `lookuptype` keyword (similar to `lookupflag` can be introduced) and then any rule that can not be expressed in this type should cause an error. When such keyword is missing, then the current behaviour is assumed.

**Comment by khaledhosny** [comment]
Here is another case, so that all cases are considered.
```
lookup foo {
 sub a by A;
 sub b by B C;
} foo;

feature calt {
 sub c [a b]' lookup foo;
} calt;
```

With current FDK/feaLib, we will need two lookups which means duplicating the rule, and for complex substitution this can quickly complicate things greatly.

**Comment by behdad** [comment]
My preference is that the compiler silently chooses the right lookup type.  The font designer doesn't care how the substitution is done as long as it does exactly what they specify.

**Comment by brawer** [comment]
Well, a given feature file should either work across all compilers, or (in case of invalid input) every compiler should equally reject it. Without consistency across tools, font designers won’t be happy people. The problem is named lookup blocks, whose subtables must all have the same type. Should the following be valid? Depending on what lookup type the compiler happens to pick, the feature file becomes invalid or not. That’s why choosing lookup types isn’t just a silent optimization.

```
lookup foo {
  sub a by A;
  sub b by B C;
} foo;
```

Actually, just wondering: couldn’t this be handled by constraint resolution? In a first pass over a named lookup block, compilers would identify for each statement a set of potential lookup types. If the intersection of these sets becomes empty, compilers would reject the feature file as invalid. In a second pass, compilers would generate the subtables, using one of the lookup types in the intersection set. Apart from optimization, it wouldn’t really matter which lookup type the compiler has picked. — Admittedly, this would be a little complicated for compiler writers (basically, @readroberts and me). But we wouldn’t have to add new keywords to an already complicated language.

Whatever we do, I think it should be clearly decidable (without ambiguity) from the _language specification_ whether a given feature file is valid. Otherwise, we’ll have an interoperability nightmare.

**Comment by miguelsousa** [comment]
> The font designer doesn't care how the substitution is done as long as it does exactly what they specify.

Some font designers do care, and not being informed that something was changed or implemented in a certain way behind the scenes can lead to a lot of frustration when differences arise between what the designer/developer expected from the code and what results they're getting (on e.g. an app).

I'm all for un-complicating things that are simple, but I'm leery of tools that are too helpful because there will be times when they make the wrong assumptions/decisions and if the designer/developer grows accustomed to being shielded from understanding what and how the tool is doing for him/her, it will eventually become an unwieldy tool.

**Comment by behdad** [comment]
> Some font designers do care, and not being informed that something was changed or implemented in a certain way behind the scenes can lead to a lot of frustration when differences arise between what the designer/developer expected from the code and what results they're getting (on e.g. an app).
> 
> I'm all for un-complicating things that are simple, but I'm leery of tools that are too helpful because there will be times when they make the wrong assumptions/decisions and if the designer/developer grows accustomed to being shielded from understanding what and how the tool is doing for him/her, it will eventually become an unwieldy tool.

To me, it sounds like you are saying "designers have had bad experiences with bad tools in the past, so let's not make tools smart".  I disagree.  We should make great tools that simplify things for designers; I don't think we should expose more low-level details to designers.

**Comment by behdad** [comment]
> Actually, just wondering: couldn’t this be handled by constraint resolution? In a first pass over a named lookup block, compilers would identify for each statement a set of potential lookup types.

Yes, that's what Khaled and I have been suggesting.

**Comment by benkiel** [comment]
> To me, it sounds like you are saying "designers have had bad experiences with bad tools in the past, so let's not make tools smart". I disagree. We should make great tools that simplify things for designers; I don't think we should expose more low-level details to designers.

Another view: having this be explicit means that the designer can know what is happening with the lookup when they encounter an issue with a rendering engine/application and can work around possible bugs in said hypothetical engine/application. Much like useExtension: the designer can choose to use this if they want explicitly, knowing what it will mean for application support, rather than having it be applied automagically and then being left to wonder why something isn't working in an application.

**Comment by miguelsousa** [comment]
@behdad what @benkiel said

**Comment by behdad** [comment]
Only if figuring out "why it doesn't work in X app" was so simple :).

**Comment by LettError** [comment]
Automagical features tend to create a debt of understanding in the future.

**Comment by benkiel** [comment]
> Only if figuring out "why it doesn't work in X app" was so simple :).

A reason to not make it more complicated.

**Comment by khaledhosny** [comment]
I don’t see where is all the magic that is hidden from the user here:
```
feature foo {
sub a by A;
sub b by B A;
sub c by C;
sub d by D B A;
} foo;
```

The lookup above is clearly multiple substitution lookup, with some entries substituting to a single glyph. There is no more magic here than FDK deciding to split this into 4 lookups behind the type designer’s back. IMO the fact that FDK does not support such multiple substitution lookups is a bug/limitation since it does not provide any other way to have such a perfectly legit OpenType lookup.

**Comment by khaledhosny** [comment]
And FDK feature syntax is full of magic being done, like this feature:
```
feature liga {
 sub f i by f_i;
 sub f f i by f_f_i;
} liga;
```

Which will be silently reorder by FDK.

**Comment by brawer** [comment]
Yes, I think the intended semantics of [your snippet](https://github.com/behdad/fonttools/issues/612#issuecomment-225189334) is quite obvious. What I’m less sure about is how to amend the OpenType Feature File specification, so that it’s unambiguously clear to compiler writers that your snippet is valid syntax—even when it’s part of a named lookup block. Maybe @readroberts sees a way for writing this down in the spec?

**Comment by miguelsousa** [comment]
> Which will be silently reorder by FDK.

Are you sure?

**Comment by khaledhosny** [comment]
This is clearly written in [the spec](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#5.d), and I tried it with makeotf before posting to be sure.

**Comment by miguelsousa** [comment]
I didn't know it was in the spec and neither was aware that makeotf worked that way :grinning:
