### ISSUE TITLE
designspace with non-standard axis can't be called with varlib.main()

### ISSUE THREAD

**Issue by LettError** [fonttools/fonttools#701]
- designspace with non-standard axis can't be called with main()
- **varlib.build()** accepts an axisMap attribute which looks like it should be used to define non-standard axes. 
- but **main** calls build() without a map
- [line 357 defines its own standard axes](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/varLib/__init__.py#L357)

Why not just extract the axes from the designspace file?

**Comment by brawer** [comment]
Wait for https://github.com/LettError/MutatorMath/issues/57?

**Comment by LettError** [comment]
Fair enough :) I'll get that going.

**Comment by LettError** [comment]
Following up. DesignSpace files now have a way to record the dimensions, tag and names of axes. 

I have a [definition of the axis element in designspace files](https://github.com/LettError/designSpaceDocument#1-axis-element) + implemented in the DesignSpaceDocument object. 

* Example: axis definitions in a designspace in the Adobe Variable Font Prototype: [AdobeVFPrototype.designspace](https://github.com/adobe-fonts/adobe-variable-font-prototype/blob/master/RomanMasters/AdobeVFPrototype.designspace#L3)
* The RoboFont extension [designSpaceEditor](https://github.com/LettError/designSpaceRoboFontExtension) can create and edit designspaces with axes.

Both DesignSpaceDocument and the editor also support the **labelname** element [discussed here](https://github.com/LettError/MutatorMath/issues/57#issuecomment-257705255).

**Comment by anthrotype** [comment]
I think this is now fixed after #857 #864 #865. Please reopen if this is not the case.

**Comment by anthrotype** [comment]
now that we read 'axes' from the designspace, does `varLib.build` still need an `axisMap` keyword argument? Shouldn't we deprecate that and only read from the designspace?

Also, why do we allow `axisMap` argument to override values from the default `standard_axis_map`, but instead when reading `axes` from designspace the `standard_axis_map` always take precendence?

https://github.com/fonttools/fonttools/blob/ae58d38/Lib/fontTools/varLib/__init__.py#L303-L311

**Comment by anthrotype** [comment]
third question: what is that `('custom',  ('xxxx', 'Custom'))` entry in the `standard_axis_map`? Can we get rid of it?

**Comment by miguelsousa** [comment]
I can provide some answers since I worked on the recent changes.

1. The `<axes>` element is a relatively new addition to the **designspace** document format. Keeping `axisMap` will allow older files with masters/sources whose `<location>` include non-standard `<dimension>` names to keep working.

2. I can't speak for the handling of `axisMap`; I simply left it working the same way as before.
In regards to the handling of `axes`, the logic is:
* honor the order set by the **designspace** file;
* consider only the axis listed in the **designspace** file, nothing more;
* if a given axis in the **designspace** file is standard, it does not need to contain `<labelname>`; the label is instead sourced from `standard_axis_map`.

3. Not sure what `custom` is used for, but can probably be deleted.
I'll mention that there's [this `assert`](https://github.com/fonttools/fonttools/blob/ae58d38/Lib/fontTools/varLib/__init__.py#L321) now that won't let the process go forward if `master_locs` references a name that is not included in `axis_names`.
