### ISSUE TITLE
Cannot merge several Noto fonts for historic languages

### ISSUE THREAD

**Issue by xiangyexiao** [fonttools/fonttools#712]
I ran pyftmerge to merge the following six Noto fonts with other Noto historic fonts (in https://github.com/googlei18n/noto-fonts/tree/master/unhinted) and got some errors.
NotoSansGothic-Regular.ttf
NotoSansOsmanya-Regular.ttf 
NotoSansPhoenician-Regular.ttf
NotoSansBamum-Regular.ttf
NotoSansShavian-Regular.ttf 
NotoSansCuneiform-Regular.ttf

For example, you can run the following commands to reproduce the problem.

$ pyftmerge     NotoSansGothic-Regular.ttf NotoSansOgham-Regular.ttf 
$ pyftmerge     NotoSansInscriptionalPahlavi-Regular.ttf NotoSansOsmanya-Regular.ttf 
$ pyftmerge NotoSansAvestan-Regular.ttf NotoSansPhoenician-Regular.ttf
$ pyftmerge     NotoSansBamum-Regular.ttf NotoSansRunic-Regular.ttf
$ pyftmerge NotoSansSamaritan-Regular.ttf NotoSansShavian-Regular.ttf
$ pyftmerge NotoSansCoptic-Regular.ttf NotoSansCuneiform-Regular.ttf 

An example error message I got is:
Traceback (most recent call last):
  File "/Users/xiangye/.venv/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/Users/xiangye/.venv/lib/python3.5/site-packages/FontTools/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(_args, *_kwds)
  File "/Users/xiangye/.venv/lib/python3.5/site-packages/FontTools/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/Users/xiangye/.venv/lib/python3.5/site-packages/FontTools/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/Users/xiangye/.venv/lib/python3.5/site-packages/FontTools/fontTools/merge.py", line 508, in merge
    assert (table is not None and table is not NotImplemented), "Have duplicates to resolve for font %d but no GSUB" % (i + 1)
AssertionError: Have duplicates to resolve for font 2 but no GSUB

wondering whether the fonts or pyftmerge have issues.

**Comment by zjusbo** [comment]
The issue is triggered by the second font file in your command line, which does not contain GSUB table but has some duplicated glyphs with the first font file.

Specifically followiong fonts are not recommended to be put as the second parameter since they do not contain GSUB table,  
NotoSansOgham-Regular.ttf
NotoSansOsmanya-Regular.ttf
NotoSansPhoenician-Regular.ttf
NotoSansRunic-Regular.ttf
NotoSansShavian-Regular.ttf
NotoSansCuneiform-Regular.ttf

This problem can be solved by exchange the parameter order. Instead of pyftmerge A.ttf B.ttf, use pyftmerge B.ttf A.ttf

However, it is a bug in pyftmerge script I think, which needs to dig deeper to solve.

**Comment by behdad** [comment]
Thanks Bo.

When merging Noto, I suggest you keep NotoSansLGC as the first font in the list.  When hitting this problem, there are a few options to resolve it:

- Add GSUB for font without it.  We need to identify the script tag to use. AND it is only safe to do so if we know there is no script-specific shaping logic for that script.  In general, it's easiest to avoid this approach.

- Avoid needing a GSUB. We need GSUB when a character has glyphs in multiple fonts.  Most probably this is only relevant for space, period, comma, etc glyphs in these fonts.  If we can satisfy that the duplicate glyphs are identical or close, then we don't need to record a substitution.

I suggest you do the latter.  You can start by drawing the glyph to a recording pen `font.getGlyphSet()[glyphname].draw(pen)` and comparing the recordings as well as pen.width.  Something like that.

Or first, just identify which characters are involved. Also, I'm open to making this a warning initially.  We did that for another issue.  See 18b905b06d436ed961fcabe85001a668679d46f5

**Comment by zjusbo** [comment]
Thanks for the advice.

I tried your second suggestions and made this a warning and following are the duplicated glyphs the script found in merging. As you predicted, all of them are space, period, comma and simple symbols that are closed to each other. I think we can tolerant the difference and ignore these warnings. I'll submit a pull request to change it to a warning.

"When merging Noto, I suggest you keep NotoSansLGC as the first font in the list."
 - Can I assume this is because we want to make NotoSansLGC as the base font file, and append glyphs in other font files to it? By doing so, the indices of the glyphs in LGC (which are used frequently) is small. May I know what's the benefit of doing this? I guess it makes glyph searching in the font file faster?

"We need GSUB when a character has glyphs in multiple fonts"
 - It seems we do not overwrite the duplicated glyph with the new glyph directly but use GSUB to substitute it. Is it because overwriting the duplicated glyph in glyf table costs too much?

"I suggest you do the latter. You can start by drawing the glyph to a recording pen font.getGlyphSet()[glyphname].draw(pen) and comparing the recordings as well as pen.width. Something like that."
- Yeah, I believe it's a powerful comparing tool but I don't quite know how to use it. Alternatively, I built two webpages showing all unicode characters in a font to visually see the difference between characters in two fonts. Plus, I found this webpage is very helpful for viewing a font: http://bluejamesbond.github.io/CharacterMap/


Following are duplciated glyphs:

'uni0000' control
'uni000D‘ control
'uni00A0' control
'uni3001' 、 
'uni3002' 。
'uni3008' 〈 
'uni3009' 〉 
'uni300A' 《 
'uni300B'  》 
'uni300C' 「 
'uni300D'  」 
'uni300E' 『 
'uni300F’ 』
'uni3010' 【 
'uni3011'  】
'uni3014' 〔 
'uni3015'〕 
'uni3016'〖 
'uni3017'〗 
'uni3018' 〘 
'uni3019'〙
'uni301A' 〚
'uni301B' 〛
'uniFEFF' ZERO WIDTH NO-BREAK SPACE
'space'

**Comment by zjusbo** [comment]
Read the fonttools merge.py source code. Got some answers for previous posted questions, but still has some questions which are written in bold. 

> "When merging Noto, I suggest you keep NotoSansLGC as the first font in the list."

Some tables are using 'first' as their merging logic, which keeps the table in the first font and discard those in other fonts, such as prep, fpgm, cvt.
Some keys in tables are also using 'first' as their merging logic, like 'names' in name table, etc.

From my understanding, always using NotoSansLGC as the first parameter keeps the information in LGC font as much as possible in the result. **This is because NotoSansLGC font is more authentic and reliable.(?)**

> "We need GSUB when a character has glyphs in multiple fonts"

A glyph can be selected by the combination of codepoint and language tag. For example, <uni00A0, CN> may selects a different glyph than <uni00A0, JP>, though their codepoint is the same. Using GSUB table to substitute the glyph based on the language tag. **However, we have to drop extra duplicate glyphs in different fonts if their langSys tag are the same.(?)**

**Comment by brawer** [comment]
> we have to drop extra duplicate glyphs in different fonts if their langSys tag are the same

Well, what can a poor little merging tool possibly do when the user wants to merge two fonts where the same glyph looks different in the same language? But does it actually happen in practice with Noto? For which glyphs in what languagesystems?

**Comment by zjusbo** [comment]
> But does it actually happen in practice with Noto? 

Yes.

>  For which glyphs in what languagesystems?

Unfortunately, following fonts that will be mentioned does not contain GSUB thus does not have a language system tag..

'space' and ['uni00A0'](https://unicode-table.com/en/search/?q=00a0) are different in NotoSans-Regular and NotoSansEgyptianHieroglyphs-Regular with 532 and 500 advance width respectively. 
['000D'](https://unicode-table.com/en/search/?q=000d) in NotoSans-Regular and NotoSansLinearB-Regular. Advance width are 1044 and 532 respectively. 

['02cd'](https://unicode-table.com/en/02CD/) in NotoSans-Regular and NotoSansLisu-Regular  uni02CD#0:(GlyphCoordinates([(25, -156),(633, -156),(633, -301),(25, -301)]), [3], array('B', [1, 1, 1, 1])), uni02CD#1:(GlyphCoordinates([(150, 0),(150, 175),(818, 175),(818, 0)]), [3], array('B', [1, 1, 1, 1]))
The rectangle shape is similar but one is longer and the other is shorter. 


['3018'](https://unicode-table.com/en/3018/) in NotoSans-Regular and NotoSansYi-Regular. uni3018#0:(GlyphCoordinates([(1050, -100),(986, -200),(550, 45),(550, 1213),(986, 1458),(1050, 1358),(912, 1279),(912, -21),(670, 111),(792, 48),(792, 1210),(670, 1147)]), [7, 11], array('B', [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])), uni3018#1:(GlyphCoordinates([(1050, -100),(986, -200),(550, 45),(550, 1217),(986, 1462),(1050, 1362),(912, 1283),(912, -21),(670, 111),(792, 48),(792, 1214),(670, 1151)]), [7, 11], array('B', [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

The shapes are very very similar to each other except for a tiny offset of two or three control points.

These are just part of the duplicates glyphs with different shapes, full list is posted in a previous post in this thread. 

From my understanding, we should **make script table in GSUB required**, because the script tag helps us better handle the duplicates in font merging.

> Well, what can a poor little merging tool possibly do when the user wants to merge two fonts where the same glyph looks different in the same language?

From the description above, we know that all the duplicates in our Noto are symbols and punctuation, with slightly different shapes. It should be OK to keep the first glyph and drops the rest. However, our little merging tool could be **smarter** to handle this case. 
For example, if font A and font B both contain glyph comma ',' with slightly different shapes, and font A and B do not contain script tag that we can not fetch the correct glyph by language tag, we can still fetch the promising glyph by its context. Fetch the ',' from font B if ',' appears adjacent to some other characters in B, otherwise fetch ',' from font A. 

Ch and En both contains period with different shapes, using '.' when it's next to another English letter while using '。' when it's next to a Chinese character。

Probably it involves [contextual substitution](https://glyphsapp.com/tutorials/features-part-2-contextual-substitutions) concept.
Just my $.02
