### ISSUE TITLE
worrying size changes round-tripping, lost 10% of file size.

### ISSUE THREAD

**Issue by HinTak** [fonttools/fonttools#725]
Two fonts dropped about 10% of file size after going through ttx and back - without any message, etc.
again apologies this is with fedora's ttx.

```
-rw-rw-r--. 1 Hin-Tak Hin-Tak 6656004 Oct 27 00:20 cfmingeb-ttxed.ttf
-rw-rw-r--. 1 Hin-Tak Hin-Tak 2950628 Oct 26 23:47 cjsongeb-ttxed.ttf

-r--r--r--. 1 Hin-Tak Hin-Tak  7235272 May 21  2003 cfmingeb.ttf
-r--r--r--. 1 Hin-Tak Hin-Tak  3275360 May 21  2003 cjsongeb.ttf
```

I believe they were publicly available and free-use at some point in the past (judging from where I keep them), though I do not know where I got them from.

```
173907f1f3f4404d4617c9fa6318907a  cfmingeb.ttf
4f7c3c0b2b99648dcd8457b96614038b  cjsongeb.ttf
```

**Comment by HinTak** [comment]
I am using ttx to modify fonts to see why the old FontVal backend does not like them, so minimum change, and only including changes I made, is desired. Obviously with 10% size difference, just round-tripping, ttx is making a hell lot of hidden changes to the fonts.

**Comment by justvanrossum** [comment]
Check with `ttx -l` which tables shrank. My guess is GPOS and/or GSUB. Those are often compiled to a more compact form using smarter subtable data sharing. That can shrink such a table without changing any actual data.

**Comment by HinTak** [comment]
I did look at that - the bulk size change happens in the `glyf` table, which is exactly why it is worrying.

There are misc checksum and etc changes elsewhere too:

```
Listing table info for "cfmingeb.ttf":
    tag     checksum   length   offset
    ----  ----------  -------  -------
    OS/2  0xEA8CF466       86    60896
    cmap  0x3A623A44    30338    61100
    cvt   0xC3012103        8    60984
    fpgm  0x985CDCA2      100    60992
    glyf  0x37AF6A80  7084629   150640
    hdmx  0x00000000        8    61092
    head  0x31A7B1B6       54      236
    hhea  0x053D0007       36      292
    hmtx  0x00000004    59196      360
    loca  0x0A09DB90    59200    91440
    maxp  0x8302AB39       32      328
    name  0x44A527C0     1299    59556
    post  0xF52A97FF       32    60856
    prep  0x130002F8        8    60888

[Hin-Tak@localhost tests-at-Size10-newold]$ ttx -l ttxed/cfmingeb.ttf
Unknown file type: "ttxed/cfmingeb.ttf"
[Hin-Tak@localhost tests-at-Size10-newold]$ ttx -l ttxed/cfmingeb-ttxed.ttf 
Listing table info for "ttxed/cfmingeb-ttxed.ttf":
    tag     checksum   length   offset
    ----  ----------  -------  -------
    OS/2  0x69168CE8       86      360
    cmap  0x144261C7    30338    30248
    cvt   0x032101C3        8    60696
    fpgm  0xA7D95E93      100    60588
    glyf  0x7B0CA311  6535296   119904
    hdmx  0x000039D4        8    30240
    head  0xE87DBE08       54      236
    hhea  0x07FE0376       36      292
    hmtx  0xC2800000    29790      448
    loca  0xAC4292AC    59200    60704
    maxp  0x3AAB0282       32      328
    name  0x58F08E72      771  6655200
    post  0xFF982BF4       32  6655972
    prep  0xF8030112        8    60688

```

**Comment by justvanrossum** [comment]
Did you do a diff on the full ttx output of the glyf table? Perhaps in the original some coordinates were stored as two-byte words that would fit in a byte. There used to be some compile optimizations in the TT instructions, but I believe those are disabled by default these days. If there's no difference in the text dumps you can pretty much trust both versions are 100% equivalent.

**Comment by HinTak** [comment]
It is 3mb and 7mb font filles - the dumps are in the 40me and 80mb region, if I remember correctly. Didn't even want to keep them around for too long, let alone two versions and diff's. :-) .

**Comment by justvanrossum** [comment]
Well, if everything is ok then the (glyf) diff will be empty. And it may answer your question. Without that there's not much more we can do.

**Comment by justvanrossum** [comment]
I mean, you're "worrying" about changes, but unless we can either look at the diffs or the original ttfs, you're just spreading rumors, which doesn't help anyone.

**Comment by HinTak** [comment]
I do not want to spend time on it _now_ . Filing this is just a reminder to look at it later. 

As I said
``
I believe they were publicly available and free-use at some point in the past (judging from where I keep them), though I do not know where I got them from.
```

Somebody else can get hold of the files themselves. That's what providing the md5sums are for.

I'd prefer this to stay open, closing this just means I'd never come back to look at it.

Please leave this open.

**Comment by moyogo** [comment]
@HinTak I think you’re worrying about a feature instead of a bug here. Please close.

Roundtripping the glyf table only recalculates the bounding box for me (they are wrong in the original TTF, being either 0, 514 or 1024). For example, just look at .notdef, it’s bounding box is not 0,0,1024,1024.
```diff
-    <TTGlyph name=".notdef" xMin="0" yMin="0" xMax="1024" yMax="1024">
+    <TTGlyph name=".notdef" xMin="5" yMin="-204" xMax="1019" yMax="819">
```
Nothing else in the diff of the glyf table changes, meaning the glyphs represented are the same and the bounding boxes corrected. There also less padding, so that saves a few kilobytes as well.

The other changes in the other tables are related to the correct bounding boxes.
The hhea.numberOfHMetrics for the htmx records goes from 14799 to 96 because that’s what they actually should be. The htmx values remain the same, they are just packed properly.

**Comment by HinTak** [comment]
@moyogo That may be so. As I said, I believe the two fonts were free-use at some point in the past, judging from where I keep them, so it should be possible for somebody else to look at it properly.

Trying to make me spend time looking at it right now is not the way forward. I do not want to look at diffs and confirm or deny whatever speculations and guesses at this point in time.

**Comment by moyogo** [comment]
@HinTak I just looked at the font and reported what the diff shows. What else do you need?

**Comment by justvanrossum** [comment]
I've just finished roundtripping with `ttx -b` as I also found thee bbox issue. There are now zero differences in the glyf file. So the difference in size can only be padding and/or byte word differences. So, there is nothing to worry about and the issue can remain closed.

**Comment by HinTak** [comment]
@moyogo @justvanrossum : did you get hold of those two fonts from somewhere? With the md5sum's I mentioned?

**Comment by justvanrossum** [comment]
```
MD5 (cfmingeb.ttf) = 173907f1f3f4404d4617c9fa6318907a
MD5 (cjsongeb.ttf) = 4f7c3c0b2b99648dcd8457b96614038b
```

**Comment by behdad** [comment]
We do zero padding instead of 4-byte padding in glyf table.  It's also possible that the original font was built using a crappy packer.  If it seems to work, I trust ttx.

**Comment by HinTak** [comment]
--------------------------------------------
On Thu, 27/10/16, Just van Rossum <notifications@github.com> wrote:
 
 MD5 (cfmingeb.ttf) =
 173907f1f3f4404d4617c9fa6318907a
 MD5 (cjsongeb.ttf) = 4f7c3c0b2b99648dcd8457b96614038b
 

okay, thanks. Do you know where you got them from? The time stamp on mine are 13 years old, and I have lost track of where they came from.

**Comment by moyogo** [comment]
I also have
```
MD5 (cfmingeb.ttf) = 173907f1f3f4404d4617c9fa6318907a
MD5 (cjsongeb.ttf) = 4f7c3c0b2b99648dcd8457b96614038b
```

I googled the file names and got lucky.

**Comment by HinTak** [comment]
Thanks. 10% size change is quite worrying, and probably can be better documented. Or perhaps, have a zero-size/non-checksum-changing option. 

FWIW, the font splitter/merger python scripts in https://github.com/HinTak/Font-Validator/tree/embedding-ironpython/bin/scripting-examples don't change table sizes or checksum's. I'll possibly have to roll my own scripts on the task of doing minimal changes. Cannot have ttx optimizing away - I need to preserve flaws in fonts while doing do :-).

**Comment by justvanrossum** [comment]
I also used google. The originals were indeed built with a crappy packer.

You can preserve the flaws if you don't go via the TTX format, but do whatever you need to do directly in Python, as long as you don't need to recompile the glyph data.

**Comment by justvanrossum** [comment]
The flaws we're talking about are repeated coordinates, that ttx properly packs using the repeat flag, but wasn't in the originals. That information is not retained in the XML format, as it is of no importance to the semantics of the data.

**Comment by HinTak** [comment]
Unfortunately what I am after, is more or less a glyph contour/hinting-instruction fuzzer - i.e. a fuzzer that changes the individual glyphs in specific ways. So recompiling glyph data is needed, and sometimes with intentionally bad/ambiguous/wrong semantics... that ttx does any extra work at all, even if totally legitimate and valid, is quite undesirable. And if ttx checks semantics, that's even worse... :-). crap is good...

**Comment by justvanrossum** [comment]
It is not doing extra work, it is doing work that is needed when compiling coordinates to binary, and it's just doing it better than whatever it was those fonts were built with. FontTools/TTX is about making complex binary data usable. The binary data is not usable. Decompiling the binary data to usable coordinates loses some aspects of the binary form by definition. So if you are messing with coordinates, you're losing this information. However, this "information" is completely irrelevant, and it is ridiculous to even want to retain it through decompilation.

The packing we're talking about is trivial. It can hardly be called an optimization, it is simply packing the coordinates in the way the TT specification prescribes. There is not really much (if any) room for interpretation there. FontTools does the exact same thing as most other TT compilers out there, so most of the time it will give the exact same binary data. But not if the original compiler was written sloppily, as is obviously the case with these fonts.

TTX doesn't "check semantics". Maybe I formulated it badly. What I'm trying to say is that whichever way you pack the coordinates into binary (efficiently, like ttx does, or inefficiently), the coordinates that the binary data actually represents are not in *any way different*.

> So recompiling glyph data is needed, and sometimes with intentionally bad/ambiguous/wrong semantics..

Well, then you just have to write your own glyph compiler, because this makes no sense whatsoever in day to day use of TTX. 

I suggest you read the TT spec about how coordinates are stored inside the `glyf` table. Maybe you'll understand that relying on how exactly the coordinates are packed is a fairly insane thing to want to do.

**Comment by lemzwerg** [comment]
Hin-Tak's wish is not unreasonable – having a *real* font fuzzer needs a certain amount of infrastructure to put the data into the right places.  The brute-force methods as used by normal fuzzers (for example, the one run by google, testing FreeType continuously since more than a year) spend an incredibly amount of processing time to generate invalid input – I mean input that doesn't pass the most basic font consistency tests.  Perhaps 99.99% of the input files are useless, being rejected in a very early state inspite of the fact that at least google's `libFuzzer` uses a suite of valid fonts as starting files that get distorted to create new input data.  Note that the fuzzer still finds bugs in FreeType; the lack of efficiency is compensated by its very long running time.

It is tempting to rely on a framework like TTX to create intentionally invalid files, but I agree with Just that it is the wrong tool due to the many sanitizing and optimizing passes built into the program.

**Comment by justvanrossum** [comment]
Thanks for that explanation. I must admit that I wasn't familiar with the term "fuzzer" in this specific meaning. Indeed, FontTools/TTX tries very hard to make correct fonts, and is really not suitable for intentionally creating incorrect fonts.

**Comment by HinTak** [comment]
Yes, Werner summarized the problem with general file fuzzer quite well - they generate piles of invalid fonts which do not pass the most rudimentary checks. It takes an incredible amount of computing time/resources with the general file fuzzing approach to explore rarely-used code paths and the darker corners of font engines.

I managed to "fuzz" some fonts to get at a few specific corner cases, by inserting PUSHW's randomly in the hinting instruction stream. (perhaps POP's would do also). This approach has its limits as the font engine soon aborts due to stack overflow/underflow. This also applies to hinting only, and not contours.
