### ISSUE TITLE
versions

### ISSUE THREAD

**Issue by typemytype** [fonttools/fonttools#767]
DrawBot and RoboFont users complain about a pop up prompting to install git when launching the latests version of the apps.

I suspect `_version.py` is requesting it, this feels a bit over engineered  :)

**Comment by justvanrossum** [comment]
The prompt is actually about installing the OSX dev tools. I'll hope to reproduce it tomorrow, and will try to determine whether it is indeed caused by _version.py.

**Comment by anthrotype** [comment]
Hold on. You have to install fonttools in a regular way, not just editable or using pth before you package up your py2app, else the _version.py will be the dynamic one that is meant for git source control, instead of the static one that's generated upon install.

**Comment by anthrotype** [comment]
You first need to do `pip install -v .` from the fonttools source directory. Then you can run your `setup.py py2app` so that py2app will copy the fonttools package that was installed in your python environment, instead of grabbing it straight from the git repository in your PYTHONPATH.

Another option is to do `python setup.py build` and have py2app copy the generated `build/lib/fontTools` package.

Please let me know if that works for you.

**Comment by justvanrossum** [comment]
And we're back to square one with the version discussion :(

**Comment by anthrotype** [comment]
please do not reopen this discussion now.
The correct way to install a python package is... to install by having the installer generate the package metadata.
As I said, It is easy for other application developers bundle fonttools.
They could even simply unzip the source distribution, or the `.whl` package (you can rename it `.zip` and extract the content).

I just opened up the Robofont.app package and, indeed, the `Contents/Resources/lib/python2.7/fontTools/_version.py` is the wrong one.

**Comment by justvanrossum** [comment]
I understand you don't like to reopen the discussion, but to me this is another proof that the version system is brittle. It tries to do too much too smartly. I don't like how it enforces one way of "correct" deployment, or rather, how it weirdly fails when deployment wasn't done "correctly".

**Comment by anthrotype** [comment]
Ok, let me recap.

versioneer computes the package version from the git metadata, so it only works when it is inside a git repository.

When you create a distribution, or run setup.py install, pip install etc., versioneer generates a static _version.py module containing just strings, so git is not required.

py2app works by looking at all the package imported in your python code and copy them inside the .app bundle. If you PYTHONPATH contains the fontTools git repository, py2app copies its content inside your app, but without the .git folder, hence breaking things.

The solution is to make sure that a static version of fontTools package, ie. one that was built or installed, is found by py2app, rather than the git repository. There are also ways of specifying the search path in which py2app should look for packages to bundle.

I hope now things are more clear.

**Comment by justvanrossum** [comment]
I understand how you made it work. I just don't agree with how you made it work.

**Comment by justvanrossum** [comment]
As in: the other solution is just put a static version in the code like we always had.

**Comment by anthrotype** [comment]
We did already put "a static version in the code":
https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/__init__.py#L12

That should give you the best approximation possible for the latest tagged version, even if a redistributor has bundled the package in a way that makes it impossible to give a precise answer.

A RuntimeWarning is what should be emitted, and that's there for good reasons.

If versioneer is raising an exception instead, then I can look into ways to handle that nicely.

**Comment by typemytype** [comment]
this means git is a requirement for fontTools, please add to the requirements...

Nevertheless this is good or bad practice, forcing users to install git is not so nice. 
This prompt must appear for users who which to install fontTools without having git.

**Comment by anthrotype** [comment]
No, I'm not adding git to the requirements! How can you even clone the git repository without git?!

I just installed the latest Robofont.app, I unlinked by homebrew git and `sudo mv /usr/bin/{git,_git}` so that git is no longer in my path.

When I start Robofont.app I don't get any pop-up message or error in the output window. If I import fontTools and print it's __version__, I get "3.2.3" which is nice and clean, despite the wrong _version.py has been copied.

If you give me more details I can try reproduce and help you debug the issue.

But again, I invite you to think about the difference between a development environment, where tools like git must be available for the development to take place, and the user environment (which Robofont.app belongs) where your library should be installed in the standard way instead of just copied off a git repository.

**Comment by anthrotype** [comment]
I'll update the README with instructions on how to bundle fonttools in your app.

**Comment by anthrotype** [comment]
@typemytype @justvanrossum 

is this the warning message that your users are getting?
http://apple.stackexchange.com/questions/161648/how-to-use-gcc-or-git-without-installing-xcode

```
xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command   line developer tools.
```

I still can't reproduce it, maybe tomorrow I'll try on a clean machine without Xcode installed.

**Comment by justvanrossum** [comment]
No, that is not the message. It's an actual dialog that people actively have to dismiss. It may only be happening on 10.11 or up or 10.12. If I'm lucky, I'm meeting students today with a setup in which this thing is triggered.

Yes, it's good to think about the difference between development and deployment, but fonttools should not push it's preferred way of deployment through user's throats. Look, you've created something that causes a problem where there wasn't a problem before. It needs to be fixed. And therefore I reopened the discussion.

So let me recap the requirements for version info inside fonttools:
- to be able to uniquely identify which release is being run, if it's an actual release
- if the version that is being run is *not* a release (ie. in-between from git), identify that that is the case, but nothing more. It is absolutely **not** necessary to have a git commit identifier embedded.

The current solution is overly complicated, and, as evidenced by this issue, unnecessarily brittle. (I mean seriously, do we need **500 lines of code** for a version number? A version number!)

What I want to happen for a release `"A.B.C"` is this:
- bump `fontTools.version` and `setup.py` to version `"A.B.C"`
- tag release
- git commit
- do release stuff: tarballs, zips, wheels, eggs, PyPI, whatever.
- bump `fontTools.version` and `setup.py` to version `"A.B.C+"` (The case "this is not a release")
- git commit

A script that does all this will surely be simpler and easier to maintain than `_version.py`.

**Comment by anthrotype** [comment]
Ok Just, I surrender. 🏳
You're right, it's not worth keep arguing about this thing.
I'll revert to a static version string as you suggested.
Really sorry for all the trouble.

**Comment by justvanrossum** [comment]
Thanks Cosimo. Sometimes we need to keep things as simple (and possibly stupid) as possible.

Btw. here is a screenshot of the message. Sorry, it's Polish :) It says something like "would you like to install XCode/dev tools, because it appears you're trying to use git". Apparently, on this computer, the same message appears everytime "save" is done in Glyphs, so there may be some fonttools involved there, too (could be an extension, though).

<img width="578" alt="screenshot" src="https://cloud.githubusercontent.com/assets/4246121/21177036/ab8d5aa6-c1e9-11e6-95ab-303dbaa83dc9.png">

**Comment by anthrotype** [comment]
[FontTools 3.3.1](https://github.com/fonttools/fonttools/releases/tag/3.3.1) is out.

**Comment by twardoch** [comment]
I actually ran into a different kind of "dependancy hell" myself when I 
was trying to hack around fontTools. I applaud your efforts, Cosimo, but 
I agree with Just & Frederik that versioneer was a bit over-engineered. 
Many thanks for reverting to static!
A.

**Comment by anthrotype** [comment]
No problem.
TBH, I preferred the setuptools_scm method over the versioneer one, as the former doesn't attempt to run a git subprocess at import time, but stores the computed string inside the package meta-data. The problem with it was that:
- the package metadata is not copied over by py2app/pyinstaller, etc. (wrongly so, IMO);
- developers who install-editable have to reinstall, or manually refresh the metadata using the `egg_info` command, every time they git pull.
For some this was a bit too much. Anyway, I'm glad we finally all agreed!
