### ISSUE TITLE
[T2CharStringPen] Rounding coordinates?

### ISSUE THREAD

**Issue by mashabow** [fonttools/fonttools#769]
Currently, [T2CharStringPen](https://github.com/fonttools/fonttools/blob/fcd697a328b439165b3e9d04904eb73f065b6838/Lib/fontTools/pens/t2CharStringPen.py#L78) always rounds glyph coordinates and casts to int, but it does not seem a good idea. I think we should remove this behavior, or make it optional.

cf. TTGlyphPen (#526)

**Comment by anthrotype** [comment]
Yes. It was like that in the original ufo2fdk package by @typesupply.

I agree we should make the rounding optional, but am not sure if we should also change the current default, as others might be relying on that behaviour.

(Although that's not a big deal if we communicate it in the changelog and bump the version).

**Comment by anthrotype** [comment]
@behdad shall I make rounding optional in T2CharStringPen, or keep rounding on by default for backward compatibility, and make non-rounding optional?

**Comment by behdad** [comment]
> @behdad shall I make rounding optional in T2CharStringPen, or keep rounding on by default for backward compatibility, and make non-rounding optional?

This is relevant in the context of:

https://github.com/googlei18n/ufo2ft/issues/24

While having option to not round is useful in theory, my gut feeling is that a tolerance parameter is more useful.  Integers take 1 or 2 bytes for most common numbers to encode.  A float takes five.  So we should not blindly round-all or not-round-all numbers.  Something like a tolerance allows for a more granular encoding.   tolerance=0 results in no rounding.  tolerance>=.5 means rounding.  Numbers in between result in some rounding and not others.

The reason I didn't implement this before is that I'm not sure if that's a useful, or best, heuristic.  For example, if a control-point vector is large, say, has a length > 100 units, then rounding never makes a visible difference.  Whereas if its length is really short, then rounding might be more visible, with very thin fonts.  That's why I wanted to get Read's test font (which he sent me) and then experiment and find a better heuristic.  The theory I just sketched suggests that rounding or not should also be dependent on the absolute length of the vector or number at hand, not just the distance to closest integer.

Anyway, that's why I have not fixed that other issue yet, because I think some in-depth research is needed to come up with good defaults that don't bloat fonts but improve accuracy for most common cases.

**Comment by LettError** [comment]
It might be useful to consider an option for rounding some categories of points like corners, anchors, components, vertical and horizontal lines, but allow more resolution for points where it matters like angled tangent points, short control points and so on. But I don't know if that is an option in t2.

**Comment by justvanrossum** [comment]
I'm not sure all this is a job for fonttools. In general, fonttools doesn't have the information needed to decide what to round and what not. To me, that's clearly font editor territory. So in that sense, a "don't round" option may be good enough.

A tolerance-rounding mechanism may make sense, too, though, so at least values like 10.0001 can be easily avoided. Unless we decide that's also the responsibility of the font editor.
