### ISSUE TITLE
Is landscape.io worthwhile?

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#788]
Or should I remove it?

**Comment by behdad** [comment]
And, I should make it email fonttools-dev instead..

**Comment by brawer** [comment]
I'd vote for remove.

**Comment by moyogo** [comment]
+1 for remove.

**Comment by anthrotype** [comment]
I rarely look at it, but having it there, muted, won't do any harm I think.

I would like to set up a proper linter such as flake8, and make PRs depend on it going green, but the problem is that half of the existing codebase won't pass the test either.
Unless we tune the linter configuration to our liking.

I'd say we keep landscape on, as a reminder to fix the formatting/code style problem.

**Comment by behdad** [comment]
Ok I disabled email. Leaving as is.
