### ISSUE TITLE
XML format does not retain LookupType for lookups with no subtables

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#789]
Eg, we currently can only encode:
```
<Lookup index="1" empty="1"/>
```
the LookupType is implied by the type of the subtables.  If there's no subtable, we don't record lookup type and roundtripping changes it (probably to zero).

**Comment by behdad** [comment]
The problem is not limited to XML.  I made LookupType a computed member in otData machinery.  Which means its value is ignored and written by subtables.  If there are no subtables, we write 0.  Need to reconciliate that.

**Comment by behdad** [comment]
Maybe we should NOT ignore LookupType attr and just make sure it matches the subtables.

**Comment by twardoch** [comment]
I think explicit enumeration of the LookupType in the XML is useful.

**Comment by moyogo** [comment]
This warrants a minor version bump.

**Comment by anthrotype** [comment]
> This warrants a minor version bump.

I agree. It's easy now to cut a release:

```bash
$ python setup.py release --sign --minor 
$ git push --follow-tags
```

The only manual task left is updating the changelog, i.e. adding new entries at the top of `NEWS`, which should be done immediately before tagging a release.

It would be nice to ask contributors to also write a short sentence in NEWS, describing the content of their patch. This can be the same as the commit message, or if that's too technical, a summary of it. The changelog is meant for users of the library rather than fellow developers; the latter can read the git log, while users may not be know/be interested in the internal details.

Of course, I can take care of updating the changelog before a new release, but I think that having the same person who writes a patch also write its changelog entry would be better. As the latter usually has a better knowledge of the reasons/implications of that patch than I can gather from briefly looking at code.

This would also speed up the release process.

**Comment by twardoch** [comment]
I think the Github wiki is a good place for collecting release notes as the process of writing stuff there is less formalized, there are no pull requests etc.

**Comment by behdad** [comment]
I have some more work around XML stuff coming soon, and will update release notes after.

**Comment by anthrotype** [comment]
> I have some more work around XML stuff coming soon, and will update release notes after.

Thanks. In the meantime, I run `bumpversion minor` so the current version is `3.5.0.dev0` when installing from git source.
The pre-release suffix is dropped when doing `python setup.py release`.

I also partly updated the changelog, though we still need entries for:

- [ ] #790 
- [ ] #792

**Comment by behdad** [comment]
Updated changelog.

**Comment by anthrotype** [comment]
Thanks Behdad, I'm going to tag 3.5.0 soon. Unless you have something else you wish to push first.
@brawer?

**Comment by brawer** [comment]
I hope to have `cvar` done by end of this week.

**Comment by anthrotype** [comment]
great, thanks Sascha. Release can wait.

**Comment by davelab6** [comment]
On Dec 30, 2016 7:30 PM, "Adam Twardoch" <notifications@github.com> wrote:

I think the Github wiki is a good place for collecting release notes as the
process of writing stuff there is less formalized, there are no pull
requests etc


I'm feeling some deja vu here, but, I recommend avoiding the github wiki, I
think it is annoying to have a second git repo with docs; and very little
is gained ux wise since github introduced direct web based editing of all
files in regular repos.

PRs aren't required for project members and if not a project member then
your contribution ought to be reviewed.

Instead I suggest adding a note about the need to include a changelog
update to REQUIREMENTS.TXT and perhaps adding a test to be run on PRs to
see if the changelog is updated....

**Comment by behdad** [comment]
Easy everyone...  First keep it simple.  Second, having to write ChangeLog brings back ancient memories.  Either we should autogenerate ChangeLog from git log (I do that in HarfBuzz and other projects), or, a high-level summary of big and user-facing changes should be put in NEWS, in which case not every commit should touch it.

My bikeshed-detector has been buzzing more frequently than I like recently ;).

**Comment by anthrotype** [comment]
I don't think NEWS should become an auto-generated mirror of `git log`; I'd prefer to keep it as it is is now, i.e. like Behdad put it:

> a high-level summary of big and user-facing changes

We just need to remember to update it when we make such changes.
