### ISSUE TITLE
CFF->TrueType

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#802]
Anyone wants to put together a snippet that uses cu2qu to convert an OpenType CFF to TrueType flavor?

**Comment by anthrotype** [comment]
something like this?
https://github.com/googlei18n/cu2qu/issues/47#issuecomment-245868919

**Comment by behdad** [comment]
> something like this?
> googlei18n/cu2qu#47 (comment)

Yes please!

I'm starting to think that we should move Snippets inside Lib/fontTools so they can be called...

**Comment by anthrotype** [comment]
> I'm starting to think that we should move Snippets inside Lib/fontTools so they can be called...

hmm, I wouldn't like to move the Snippets inside the core library. They are by definition incomplete, otherwise we would have already done that.

What I'm thinking instead is have a new `fontTools.convert` module (and a corresponding `fonttools convert` subcommand) that can be used to convert between the various font formats (TTF, CFF/OTF, WOFF, WOFF2, and... TTX). We could also abuse the `ttx` command for that, although the latter has a long history and we wouldn't be able to change too much its interface.

To avoid a circular dependency between fonttools and cu2qu, I was thinking we could split cu2qu in half: one part (`cu2qu.__init__` and the `cu2qu.pens.Cu2QuPen` segment pen) would be moved inside fonttools, and the rest (`cu2qu.ufo` and the point pens) could stay in its own separate `cu2qu` package (or even moved inside `ufo2ft`).

Let me know what you think.
In the meantime, I can already push the CFF-to-OTF snippet.

**Comment by anthrotype** [comment]
I just added the "Snippets/otf2ttf.py", please test, thanks.

**Comment by anthrotype** [comment]
Done in 2a4b3d5

**Comment by twardoch** [comment]
I'm not sure if it's that simple — the "fonttools convert" function. Would it convert a TTC into multiple TTFs? Would it convert a TTF+gvar into a set of static TTFs? Would it convert an OTF+SVG into a TTF+sbix? And if not, why not? 

I don't think it's so trivial anymore too define what exactly "convert" means. Such a converter would be great but I don't think it should be placed inside fontTools. It should be a separate app. The OTF+SVG to TTF+sbix conversion obviously would require an SVG rasterizer, other conversions might require FreeType or other dependencies.
