### ISSUE TITLE
Opener that can open binary, TTX, UFO, or Glyphs file

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#814]
Would be nice to have an opener that can open anything and return a glyphset.  Should be, like, 50 lines :).  Any volunteers?

Perhaps first write a file type guesser that we can reuse for other things as well.

This will be useful with tools like interpolation compatibility checker that can work on any level as long as a UFO-style glyphset is available.

**Comment by anthrotype** [comment]
This indeed would be useful. However, I wonder if this should belong to fonttools or instead to some other higher-level library.

FontTools traditionally only handles binary formats like sfnt or type1, whereas ufoLib and glyphsLib deal with font sources. They in turn depend on fonttools, e.g. for things like py23, the pen protocol, the xmlWriter, etc.

Importing ufoLib or glyphsLib from a fontTools module could mean adding a circular dependency I'm not saying this couldn't be managed cleanly, just that it might be tricky.

Also, a fontTools.ttLib glyphset is not exactly the same as a UFO-style glyphset: FontTools' glyphs only have `draw` method and use "segment" pens; ufoLib (ex robofab) have `drawPoint` and "point" pens, but it also exposes a segment-pen interface via converter pens. As for glyphsLib, it currently has no objects nor pens, but just a raw dictionary.

How/where do you see this new "opener" fit into all this? Hopefully, it's not just another Snippet.

To be clear, I'm not dismissing this; just trying to understand what the implications would be.

**Comment by anthrotype** [comment]
this just reminded me of https://github.com/typesupply/extractor

**Comment by brawer** [comment]
Regarding dependencies, personally I wouldn’t find it so terrible if the whole zoo (glyphLib, compreffor, cu2qu, etc.) were all part of fonttools. It would simplify things quite a bit. On the other hand, merging is work.

**Comment by anthrotype** [comment]
I agree, it would definitely simplify things.
I think compreffor was meant to be part of fonttools; if it hasn't happened yet I guess it's because it requires a C++ compiler (but there's wheels, and the compiled part could be made optional).
As for cu2qu, at least half of it (the geometry and the pen) could be incorporated nicely in fonttools, while the ufo part not so much.
There was also that other discussion going on about moving all the scattered pens to fonttools. But I don't want to open too many issues at once.
The question here is, should fonttools become "aware" of different source formats (UFO, glyphs, etc.) or should it only provide an interface which other libraries can hook into?

**Comment by behdad** [comment]
I ended up doing this anyway in `varLib.interpolatable`:
https://github.com/fonttools/fonttools/blob/0c2f125ba0a4ad5d72f2072fdc36095421a14618/Lib/fontTools/varLib/interpolatable.py#L367-L418
