### ISSUE TITLE
[subset] Wish: Flatten OpenType features

### ISSUE THREAD

**Issue by yanone** [fonttools/fonttools#817]
Hi everyone,

pyftsubset is one of the most useful tools I’ve come around in my current stream of work. 
Yet a key feature may be missing: Flattening OpenType features, as in: applying all single substitutions from a certain feature before removing it.
So that one could choose a certain hard-wired figure set, for instance, or Small Caps or some Stylistic Set baked as the default into the fonts.

It feels like such a natural part of *pyftsubset*, especially for reducing file sizes for web fonts.
Is there such a thing already that I’ve missed or shall I attempt to make it and push?

**Comment by yanone** [comment]
By the way, the FontFont Subsetter has that feature, so one could ask Eigi if he wants to contribute the code, assuming that it was written around fontTools.

**Comment by anthrotype** [comment]
Check out this script by @twardoch
https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze
Maybe it's what you are looking for?

**Comment by yanone** [comment]
Thanks, I checked it out. 
As Adam writes, it seems to only remap the ´cmap´ table, leaving the rest of the font as it is and my findings seems to confirm it. The entire glyph body and features are still in the font afterwards, whereas I would expect the lowercase glyphs to disappear when I freeze the `smcp` feature. So his approach doesn’t actually optimize anything, just changes the functionality of the font.
That's not what I had in mind.

**Comment by anthrotype** [comment]
I see. What about running pyftfeatfreeze and subset afterwards?

**Comment by yanone** [comment]
This looks very promising. I used *pyftsubset* using ` --unicodes="*" --layout-features='*' --layout-features-='smcp'` on the frozen font. Please correct me as I’m just learning how to use the tools properly. I was afraid that it would then remove the `.sc` glyph as per the features, but I guess that the `cmap`-remapping really did the trick. The glyphs in the final font are still called `.sc` but have the respective standard Unicodes. Also the kerning seems to be correct for the `.sc`. The font lost 42% file size.
Will do some more testing. If I find anything, I’ll let you know. Thank you.

**Comment by twardoch** [comment]
I've been using pyftfeatfreeze and pyftsubset myself. pyftfeatfreeze even has an option to output the new glyphnames, which can then be fed into pyftsubset to create a small font that only includes the remapped glyphs (which can then be included in a CSS font-family call as the first font, followed by the regular font). This is now a bit obsolete for new browsers but may be useful for those that don't support font-feature-settings. 

Though for IE, I'd just run pyftfeatfreeze and produce only the EOT (without WOFF/WOFF2) and specify that webfont as the first one, followed by WOFF/WOFF2 with font-feature-settings applied from the regular font. 

Generally, pyftfeatfreeze and pyftsubset are meant to work together. My tool does its own analysis of lookups because I wrote it before pyftsubset existed. Today, it'd make sense to use the internal of subset.py i.e. out would be very possible to slightly extend subset.py to do the freezing but I never got around to doing it.

**Comment by yanone** [comment]
Thanks for the explanation.
I’m closing this issue. You guys will remember to include a freezer into *pyftsubset* when the time has come.
