### ISSUE TITLE
Off-by-one in HVAR AdvWidthMap

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#901]
I think I found an off-by-one issue in the assembling of **HVAR**'s `AdvWidthMap`. Haven't looked at the code, but I have a test case at https://github.com/adobe-fonts/adobe-variable-font-prototype/tree/hvar-issue

Open **AdobeVFPrototype.ttf** in FontView, move the Weight slider to the right, and notice how the cent jumps toward the dollar when the two glyphs transition to having no bar thru. The dollar glyph with no bar across (`dollar.nostroke`) is the last GID of the font.

Now do the same steps with **AdobeVFPrototype-HVAR_patched.ttf** and notice how the cent does not jump back. This font has an additional entry in the **HVAR**'s `AdvWidthMap`.

Both fonts can be rebuilt using the command `sh ./buildVF.sh`.

**Comment by readroberts** [comment]
I think this is probably a bug in FreeType, or at least FontView, rather than the font. The immediate problem is that the AdvWidthMapping table omits an entry for the last glyph in the font; adding this entry, with the same delta values as the previous entry,  in the 'ttx' file and recompiling the font from this ttx file fixes the observed symptom. However, the OpenType spec for the HVAR table says "If a given glyph ID is greater than mapCount – 1, then the last entry is used." The original HVAR table should be correct by the spec, so the problem must be in the interpretation of this.

**Comment by miguelsousa** [comment]
@brawer @lemzwerg ^^^

**Comment by miguelsousa** [comment]
* [FontView issue #24](https://github.com/googlei18n/fontview/issues/24)
* [FreeType bug #50678](https://savannah.nongnu.org/bugs/index.php?50678)
* [Test font TestHVARTwo](https://github.com/unicode-org/text-rendering-tests/pull/26)

**Comment by miguelsousa** [comment]
[Font files mentioned in the original post](https://github.com/fonttools/fonttools/files/889140/AdobeVFPrototypeFonts.zip), in the event that the repository or the branch referenced get deleted.
