### ISSUE TITLE
[varLib.merger] Merging of makeotf-generated GPOS tables results in missing kern pairs

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#914]
This is sort of a segue of issue #888. In that issue, the GPOS tables of the master fonts were compiled with `feaLib`. If the GPOS tables of the master fonts are instead compiled with `makeotf`, the resulting variable font will not have some kern pairs that were present in the master fonts.

Test files are available at https://github.com/adobe-fonts/source-sans-pro/blob/no-greek-cyrillic-kerning/RomanMasters/build_vf.py
The test string I've been using is **LTaVAWATA**.

**Comment by miguelsousa** [comment]
@behdad do you think 1b5e1c4b062acf3d6ece6b6d81737f6685613773 will fix this issue?

**Comment by behdad** [comment]
> @behdad do you think 1b5e1c4 will fix this issue?

I don't know.  That wasn't motivated by this bug.  I plan to debug this soon.

**Comment by behdad** [comment]
The rest of this issue is to resolve the TODO item that currently only allows one PairPosFormat2 subtable if the coverages are not identical.  The way AFDKO generates optimized subtables violates that.  Fixing it properly will take some time, so I'm going to leave this for now and work on https://github.com/fonttools/fonttools/issues/950 which seems to be a genuine bug rather than shortcoming.

**Comment by behdad** [comment]
I believe I've address this all.
