### ISSUE TITLE
Update varLib to current designspace spec

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#916]
@behdad, does varLib need to be updated to implement the [current designspace spec](https://github.com/LettError/designSpaceDocument/blob/master/README.md)? When building a variable font for [Noto Sans Cherokee](https://github.com/googlei18n/noto-source/raw/master/src/NotoSansCherokee-MM.glyphs) with fontmake, varLib crashes like this:

```text
  File "/home/sascha/src/fontmake/Lib/fontmake/font_project.py", line 200, in build_variable_font
    font, _, _ = varLib.build(designspace_path, finder)
  File "/home/sascha/src/fontmake/env/src/fonttools/Lib/fontTools/varLib/__init__.py", line 380, in build
    model = models.VariationModel(master_locs)
  File "/home/sascha/src/fontmake/env/src/fonttools/Lib/fontTools/varLib/models.py", line 137, in __init__
    keyFunc = self.getMasterLocationsSortKeyFunc(locations, axisOrder=axisOrder)
  File "/home/sascha/src/fontmake/env/src/fonttools/Lib/fontTools/varLib/models.py", line 148, in getMasterLocationsSortKeyFunc
    assert {} in locations, "Base master not found."
AssertionError: Base master not found.
```

When compiling NotoSansCherokee, the `locations` variable has the value `[{u'wght': -1.0}, {u'wght': -1.0}, {u'wght': -0.7}]`, which seems a bit surprising given the generated designspace:

```xml
<?xml version='1.0' encoding='utf-8'?>
<designspace format="3">
    <axes>
        <axis default="400" maximum="900.0" minimum="100.0" name="weight" tag="wght">
            <map input="100.0" output="26" />
            <map input="200.0" output="39" />
            <map input="300.0" output="58" />
            <map input="400.0" output="90" />
            <map input="500.0" output="108" />
            <map input="600.0" output="128" />
            <map input="700.0" output="151" />
            <map input="800.0" output="169" />
            <map input="900.0" output="190" />
            <labelname xml:lang="en">Weight</labelname>
        </axis>
    </axes>
    <sources>
        <source familyname="Noto Sans Cherokee" filename="NotoSansCherokee-Light.ufo" name="Noto Sans Cherokee Light" stylename="Light">
            <location>
                <dimension name="weight" xvalue="26.000000" />
            </location>
        </source>
        <source familyname="Noto Sans Cherokee" filename="NotoSansCherokee-Regular.ufo" name="Noto Sans Cherokee Regular" stylename="Regular">
            <lib copy="1" />
            <groups copy="1" />
            <features copy="1" />
            <info copy="1" />
            <location>
                <dimension name="weight" xvalue="90.000000" />
            </location>
        </source>
        <source familyname="Noto Sans Cherokee" filename="NotoSansCherokee-Bold.ufo" name="Noto Sans Cherokee Bold" stylename="Bold">
            <location>
                <dimension name="weight" xvalue="190.000000" />
            </location>
        </source>
    </sources>
    <instances>
        <instance familyname="Noto Sans Cherokee" filename="../instance_ufo/NotoSansCherokee-Thin.ufo" name="Noto Sans Cherokee Thin" stylename="Thin">
            <location>
                <dimension name="weight" xvalue="26.000000" />
            </location>
            <info />
            <kerning />
        </instance>
        <instance familyname="Noto Sans Cherokee" filename="../instance_ufo/NotoSansCherokee-ExtraLight.ufo" name="Noto Sans Cherokee ExtraLight" stylename="ExtraLight">
            <location>
                <dimension name="weight" xvalue="39.000000" />
            </location>
            <info />
            <kerning />
        </instance>
        <instance familyname="Noto Sans Cherokee" filename="../instance_ufo/NotoSansCherokee-Light.ufo" name="Noto Sans Cherokee Light" stylename="Light">
            <location>
                <dimension name="weight" xvalue="58.000000" />
            </location>
            <info />
            <kerning />
        </instance>
        <instance familyname="Noto Sans Cherokee" filename="../instance_ufo/NotoSansCherokee-Regular.ufo" name="Noto Sans Cherokee Regular" stylename="Regular">
            <location>
                <dimension name="weight" xvalue="90.000000" />
            </location>
            <info />
            <kerning />
        </instance>
        <instance familyname="Noto Sans Cherokee" filename="../instance_ufo/NotoSansCherokee-Medium.ufo" name="Noto Sans Cherokee Medium" stylename="Medium">
            <location>
                <dimension name="weight" xvalue="108.000000" />
            </location>
            <info />
            <kerning />
        </instance>
        <instance familyname="Noto Sans Cherokee" filename="../instance_ufo/NotoSansCherokee-SemiBold.ufo" name="Noto Sans Cherokee SemiBold" stylename="SemiBold">
            <location>
                <dimension name="weight" xvalue="128.000000" />
            </location>
            <info />
            <kerning />
        </instance>
        <instance familyname="Noto Sans Cherokee" filename="../instance_ufo/NotoSansCherokee-Bold.ufo" name="Noto Sans Cherokee Bold" stylename="Bold">
            <location>
                <dimension name="weight" xvalue="151.000000" />
            </location>
            <info />
            <kerning />
        </instance>
        <instance familyname="Noto Sans Cherokee" filename="../instance_ufo/NotoSansCherokee-ExtraBold.ufo" name="Noto Sans Cherokee ExtraBold" stylename="ExtraBold">
            <location>
                <dimension name="weight" xvalue="169.000000" />
            </location>
            <info />
            <kerning />
        </instance>
        <instance familyname="Noto Sans Cherokee" filename="../instance_ufo/NotoSansCherokee-Black.ufo" name="Noto Sans Cherokee Black" stylename="Black">
            <location>
                <dimension name="weight" xvalue="190.000000" />
            </location>
            <info />
            <kerning />
        </instance>
    </instances>
</designspace>
```

I won’t be able to fix this during the coming days (need to prepare for a Google committee; then a full day of committee meetings; then there’s the Easter holiday in Switzerland). So it would be great if @behdad or somebody else could look into this.

**Comment by miguelsousa** [comment]
@brawer in <axis>, change the value of **default** to 90, so that it matches the location of the source that has the <info> element.

**Comment by brawer** [comment]
@miguelsousa, it looks like minimum/maximum/default are supposed to be in external user space, so `default="90"` would be in violation of the [specification](https://github.com/LettError/designSpaceDocument#1-axis-element). So I think varLib should change its implementation.

**Comment by behdad** [comment]
Ok, varLib needs to understand the axis map. After which it should work.  I'll see if I can get this done today.  Hold on.

**Comment by miguelsousa** [comment]
@brawer if you swap the output and input values, and redefine minimum and maximum based on that, it should all work.

@behdad to me what makes most sense is to setup the `<axis>` element according to the font's design, and the OT tables (`fvar`?) according to the values of `output`, rather than the other way around.

**Comment by behdad** [comment]
> @behdad to me what makes most sense is to setup the <axis> element according to the font's design, and the OT tables (fvar?) according to the values of output, rather than the other way around.

Doesn't make most sense to me.  The mapping always goes from user values to internal values, so I think the current to/from makes more sense.

I also like that axis min/default/max show user-visible values.

I do think for <instances> it might make more sense to have them in user-space.  Will be useful to allow both spaces everywhere, using an extra attribute.  But I don't have good names for them.  User-space and Design-space? Linear-space? Blend-space?

Ideas anyone?

In the meantime I'll start implementing current design in varLib so we can test and gather feedback.

**Comment by miguelsousa** [comment]
> I also like that axis min/default/max show user-visible values.

Does that mean that the weight axis values are going to be the same for a lot of fonts in world? To me it feels that the OT spec is commanding the way to setup some of the axes in the designspace document. And my design-inclined brain can't stop thinking that the input/output setup is counter-intuitive.

@LettError what's your take on this?

**Comment by behdad** [comment]
Ok!  Done.  I'll write a detailed report for discussion later.

**Comment by LettError** [comment]
To be honest, I find this the requirement the weakest part of the specification. Looking at https://github.com/googlei18n/fontmake/issues/167, @brawer summarizes: ` For example, Light must be at wght=300, Regular at wght=400, Black at wght=900.` — this is going to be _very_ difficult to enforce. 

* Whether or not a typeface can map to these numbers this _depends on its design_. In order for the font **not** to be on spec it would be enough for someone could have to look and say "that's not regular at all".
* What if the designspace only has a thin and bold, the spec would then state that whatever is at 400 is the regular. This is not necessarily the right weight.
* Weight progression is curved, even in linear interpolation between 2 masters.
* Using **avar** to correct for this is unwanted: avar is to expose certain areas of an axis at a different rate, for instance, gulp, for sliders. It is not intended to correct for realities in a particular typeface and the _expectation of the spec_.
* Regardless of what the spec says, there are going to be many different typefaces expressing many ideas about how weight grows, using the full range of this axis. We might as well start preparing for it. 
* As I understand, this requirement is motivated by a desire to have some interoperability between different fonts, so that if one is missing, another might have a reasonable replacement weight. As a typographer I have my reservations about how useful this is.
* I think the bottom line is the OpenType spec should not make any normative statements on the design of typefaces.  I recommend reconsidering this.

**Comment by PeterCon** [comment]
I'm not following the details of the discussion too closely, but will add a comment in case it helps.

The OT spec aims for interoperability of axis values _to the best extent possible_. Because the 'wght' axis is defined in a somewhat vague way, the best level of interoperability is that there's a fairly good chance a family will have a member with wght = 400, a better chance that it will have (say) a 600 than a 587, a hope (but certainly no guarantee) that a 400 in one family will provide a similar colour on the page as a 400 in another family, etc. On that last point, we know that there's plenty of cases in current practice in which a 400 in one family has very different colour from a 400 in another family.

So, really, the level of interoperability is not much more than that multiple values of 100 are most common and, hence, recommended, that larger numbers mean darker text, and that 400 and 700 may be given particular treatment in certain application UI.

**Comment by miguelsousa** [comment]
Why is this remapping of the Weight (and Width) axis even necessary? Don't named instances have OS/2 values associated with them? If they don't, they should. Then any kind of interoperability between fonts will be just as before.

What if the v-font does not have named instances? Then the remapping is required if and only if the font maker wants to support any kind of interoperability. If he/she doesn't care about that, then it's up to the implementation to decide, or perhaps up to the OT spec to spell out that it will fallback to the default master or something else.

**Comment by miguelsousa** [comment]
Also, similar to what Erik wrote above, hijacking the mapping functionality to do OS/2-fitting precludes it from being used for making axis adjustments that the design may need.

**Comment by behdad** [comment]
> Why is this remapping of the Weight (and Width) axis even necessary? Don't named instances have OS/2 values associated with them?

No they don't.

> If they don't, they should.

Sorry Miguel, too late.  You were in the working group that decided these things and you didn't speak then.

All I'm doing now is implementing what the spec says.  And even then, I'm not hardcoding any of that in code.  If you don't like your weights matching the spec, fine, don't put those numbers in your .designspace file.  I don't understand what you don't like about what I implemented.

**Comment by behdad** [comment]
@LettError while some of your arguments are valid, I don't see how they relate to the patches I pushed into fonttools.  All I did was to implement desginspace's map element and distil those into avar table.  There's no hardcoded weight mapping whatsoever.  That's up to designers, they choose what to put into their designspace file.  How is this not what you want?

It's ok to disagree how different people intend to use the mapping for.

**Comment by twardoch** [comment]
The reasoning behind choosing a “universal” scale for `wght` was because it’s an extremely common axis, and **users** will expect somewhat predictable results when switching fonts or using font fallback. If a user mixes different fonts, especially for different scripts, they should have some expectancy as to what a `wght` value of 800 or 250 will produce. 

Also, it had to do with how the integration of CSS `font-weight` with variable fonts was planned. While with variable fonts, it will be possible to use any CSS `font-weight` value between 1 and 1000, there is still the longtime legacy of CSS+JS code that assumes `font-weight` to be 100, 200, ..., 900, with `normal` being 400 and `bold` being 700. 

When a variable font isn’t available, or doesn’t cover a given script, then typesetting engines will fall back to another variable font, or to a static font — but keeping the declared `font-weight` value. If someone makes a variable font with a weight scale of 25 to 320, where the 320 is a really black design, and there is font fallback, the browser will round the `font-weight` to 300 and supply fallback glyphs that will be very light. 

Note that `wght` is a **registered font axis where the scale is expressed in a universal, or “common” scale**. There is nothing that precludes type designers from shipping a font that includes, say, a `STEM` axis that is scaled from 25 to 320, where the values correspond to either the font units or perhaps — even better — the ‰ of the em. Whether a “stem thickness” or whatever such axis would need to be registered, or at least semi-standardized in a “community project”, is another thing.

**Comment by twardoch** [comment]
In my view, all fonts should try to adhere to the recommendation that the `wght` axis is scaled so that, in user coordinates, the “Light” should be at 300, the “Regular” at 400 and the “Bold” at 700. Let’s agree that the `wght` axis is not “weight” but “universal weight expressed in a common scale”. But this doesn’t have to be the only weight-related axis that ships with the font. The font can also ship an identical `WGHT` or `STEM` axis, for example. Not sure whether this will mean data duplication in the glyph tables. If so, well, then we do have a problem indeed. 

But as I described above, type designers making variable fonts should also try to make the life easier for the people who will implement support for variable fonts in apps and OSes. They **need** to be able to write their code in such a way that for something like weight, which is an extremely common design parameter, things like font fallback and switching the font family without refactoring all the applied styling works painlessly.

**Comment by LettError** [comment]
@twardoch As @PeterCon writes "The OT spec aims for interoperability of axis values _to the best extent possible._". I think that reads a MAY, not a MUST. It should not imply that all fonts are required to have the light at 300, the regular at 400 and the bold at 700. The problem is that weight grows in a curve, even in a linear interpolation between 2 masters. So, depending on the design you may be able to hit 2 of these values, it's unlikely your design will hit three.

**Comment by behdad** [comment]
> Whether or not a typeface can map to these numbers this depends on its design. In order for the font not to be on spec it would be enough for someone could have to look and say "that's not regular at all".

It's the designer's intent that matters.  That's no different for static fonts.

> What if the designspace only has a thin and bold, the spec would then state that whatever is at 400 is the regular. This is not necessarily the right weight.

A mapping can fix that.

> Weight progression is curved, even in linear interpolation between 2 masters.

Indeed, why a mapping is needed.

> Using avar to correct for this is unwanted: avar is to expose certain areas of an axis at a different rate, for instance, gulp, for sliders. It is not intended to correct for realities in a particular typeface and the expectation of the spec.

I disagree.  avar is exactly right to map a linear font weight numbering scheme to the correct interpolation coefficients.

> Regardless of what the spec says, there are going to be many different typefaces expressing many ideas about how weight grows, using the full range of this axis. We might as well start preparing for it.

To allow for arbitrary non-linear progressions of weight growth, one needs an avar table.

> As I understand, this requirement is motivated by a desire to have some interoperability between different fonts, so that if one is missing, another might have a reasonable replacement weight. As a typographer I have my reservations about how useful this is.

By "this requirement" I assume you mean the 100, 200, ... numbers.  That's not part of code I put into fonttools.

> I think the bottom line is the OpenType spec should not make any normative statements on the design of typefaces. I recommend reconsidering this.

You can, but this is not the forum for it.

**Comment by twardoch** [comment]
However, the "9 steps mapping" is **not** a hard requirement. I think it would be good if type designers aimed at their “Regular” to be at `wght` = 400, but the stuff that is lower or higher can be just a linear transposition of your design weight scale (say 25 to 320) to the user scale (1 to 1000 or 100 to 900 or whatever you pick). So on your design scale, if you choose Regular to be 65, and the design scale goes from 25 to 320, and you want your 320 to be compatible to the universal user `wght` of 900, you take 

```
400 - (65 - 25) * ((900 - 400)/(320 - 65))
```

and you get the value of 321.56. 

In other words, if your design scale is such that: 
* design weight min `DWMin = 25`
* design weight default `DWReg = 65`
* design weight max `DWMax = 320`

and you want your `DWReg = 65` to correspond to user weight default `UWReg = 400`, and you want your `DWMax = 320` to correspond to `UWMax = 900`, and you need to find the `UWMin`, you do: 

```
UWMin = UWReg - (DWReg - DWMin) * ((UWMax - UWReg) / (DWMax - DWReg))
```

So you get a nice **linear** mapping from `25, 65, 320` to `321.56, 400, 900`. And you just transform the design weight breakpoints for the instance weights to the user weight breakpoints the same way. That stays within the boundaries of the spec yet does not cause the **slider speed changing** effect that Erik was describing (which may indeed be a problem). Then, you **don’t** need the `avar` table at all! 

That’s what I’d propose as a “compromise” solution.

**Comment by behdad** [comment]
> That’s what I’d propose as a “compromise” solution.

Designer can put that in designspace, with no map element.  Or can put map elements.  I don't get it. How is the code in fonttools wrong, and how can it be different?  I don't dictate what designer puts in their designspace file.

**Comment by behdad** [comment]
> Also, similar to what Erik wrote above, hijacking the mapping functionality to do OS/2-fitting precludes it from being used for making axis adjustments that the design may need.

I suggest you study the code.  The "OS/2-fitting" is in your head, and designer's head.  It's not in the code.

Also, what is being precluded again?  You are completely misunderstanding what the code does.

**Comment by twardoch** [comment]
@behdad There are three sets of scales/coordinates involved, not two: 

* design scale (which exists **only** in sources, like UFO or Glyphs)
* user scale (which might correspond to the design scale, but for `wght` and the other registered axes it has some additional requirements)
* normalized scale (inside the var font, always `-1, 0, 1`)

The `avar` table bends the user scale to the normalized scale. But bending, or linear remapping as I described above, can also happen at font generation time and affect how to get from design scale to user scale. :) 

That’s what **I understand** is the issue here.

**Comment by twardoch** [comment]
So in principle, bending can happen at compile time, at runtime, and both :)

**Comment by miguelsousa** [comment]
> Sorry Miguel, too late. You were in the working group that decided these things and you didn't speak then.

I wasn't. But even if I had been I don't think that I would have foreseen all the implications of the various decisions. And why is it too late? Aren't we all still sorting out the kinks in the spec as we implement it? I'm not the only one that thinks this part isn't quite right, so let's work towards a better solution, otherwise this will remain the Achilles heel of the variations spec. 

> I don't understand what you don't like about what I implemented.

What you implemented​ is fine as it's according​to the spec. It's the spec that is wrong.

**Comment by davelab6** [comment]
> Sorry Miguel, too late. You were in the working group that decided these things and you didn't speak then.

I remain skeptical that the working group involved enough people to decide such things correctly ahead of time. 

Honestly I am quite shocked to hear "Sorry, too late" when MS folks have been (and I believe will continue to) actively revising the 1.8 spec to accommodate issues that are discovered by both system implementors and by font developers.

**Comment by twardoch** [comment]
Actually, I was a bit wrong. You don't bend twice. 

The thing is that the designspace map actually can have a number of entries, so there will be an avar. 

But there should be a way to also "normalize" the linear scale (design min-reg-max to user min-reg-max), using a simple formula that I've given. That normakuzation is just multiplication and addition applied to all coordinates the same way, per axis, so that the user coordinates for registered axes stay with the spec bounds. The bending is a different thing.

**Comment by behdad** [comment]
> design scale (which exists only in sources, like UFO or Glyphs)
> user scale (which might correspond to the design scale, but for wght and the other registered axes it has some additional requirements)
> normalized scale (inside the var font, always -1, 0, 1)

You're one step ahead of everyone else :). Both design scale and normalized scale are linear, so they match topologically.  Indeed, designspace file map elements map user-scale to design-scale.  I losslessly map design-scale to normalized-scale and encode the combined result as avar table.

**Comment by behdad** [comment]
> I remain skeptical that the working group involved enough people to decide such things correctly ahead of time. I would like to see the working group archive made publicly available, and all discussions made in public forums from now on. I do not understand what is gained by keeping it all private, and I see here a clear example of what damage it does.

Bulk of the work happened in all-day in-person meetings.  I'm supportive of making the meeting notes public.  @PeterCon can consider that.  I'm also supportive of making initial proposals and documents public.  I know I like to publish my design papers for ItemVariationStore since it includes a lot of design rationale.

All I'm saying is that this issue is not the right forum to discuss whether spec should be changed.  I implement what's in the spec right now.


> Honestly I am quite shocked to hear "Sorry, too late" when MS folks have been (and I believe will continue to) actively revising the 1.8 spec to accommodate issues that are discovered by both system implementors and by font developers.

They don't do that without asking for consensus to the group.  And the group is well-represented by people in this thread. Most people are there.  Except you I believe and maybe Miguel.  Adam and Erik are there.  I love to see everything done in the open, but unfortunately the OpenType mailing list proved to be a failure and that's not even open to the public...  I'm open to lean alternatives, but in the end I don't make the decision.

**Comment by behdad** [comment]
> That normakuzation is just multiplication and addition applied to all coordinates the same way, per axis

Really, that's exactly what my code does...

**Comment by twardoch** [comment]
For wght, the design weight min, default, max should be transposed so that default becomes 400, min is > 1 and max is <= 1000.  That's a simple linear transposition that does not bend. All design wght coordinates for intermediate masters, instances etc. are all transposed the same way. 

Also the map "in"  values get transposed linearly. The transposed coords go into fvar, the map bending then goes into avar.

**Comment by davelab6** [comment]
> Except you I believe and maybe Miguel

I can think of a bunch of people - say, Belleve, Lasse, Peter Sikking, Marc Foley, Girish Dalvi - who are keenly interested to follow along. 

I'll stop raising this topic here, I acknowledge this issue page isn't the right forum - but there is no right forum IMO, and I feel rather stropy about it :)

**Comment by behdad** [comment]
> I can think of a bunch of people - say, Belleve, Lasse, Peter Sikking, Marc Foley, Girish Dalvi - who are keenly interested to follow along. There are countless others.

You have to draw the line somewhere.  First: this collaboration would have been impossible without regular day-long face-to-face meetings.  There's no way we could have resolved things in looooooooooong email threads.  When you take that into consideration, then there's a limit to how many people you can get into the same room and design things efficiently.  We somehow managed to not bikeshed a lot and not suffer from groupthink much.  That's a major achievement.  Couldn't have been done with another twenty people in the room IMO.

Still, let's focus on specific issues.  I haven't seen any proposal or problem statement paper yet.  If you send me one, I'd happily share with the group and relay back the response.

Also, note that the group is not actively working on the next steps right now. I talked to Peter and we tentatively agreed to start talking about next steps around ATypI time.  In the meantime everyone is busy finishing their implementations.

> And then there is the historical record to preserve.

I like opening up design documents, yes.

**Comment by miguelsousa** [comment]
@behdad can you explain why this particular font —Noto Sans Cherokee— needs weight mappings? Hopefully that will help me understand what I'm allegedly not grasping.

**Comment by behdad** [comment]
Can we close this now?

**Comment by behdad** [comment]
> @behdad can you explain why this particular font —Noto Sans Cherokee— needs weight mappings? Hopefully that will help me understand what I'm allegedly not grasping.

Because the font source uses stem width for weight access internally, while Google wants to generate fonts that comply with OT 1.8 standard and use 100,200... numbers for weight axis.

There's nothing specific about Noto Sans Cherokee.  All Noto fonts are affected.  What happened is that Sascha changed glyphsLib to generate <map> elements for weight and width axes to map from OpenType numbers.  varLib was ignoring the <map> elements, and that broke the font generation.  I've fixed varLib to consume map elements.

If you don't add map elements, varLib does exactly what it used to before.  If you object to the glyphsLib change, then you can raise that in glyphsLib repo.  But given the current wording of the spec, I think it would be hard to argue against that change.

**Comment by PeterCon** [comment]
Some comments on the OT 1.8 spec development process as it pertains to 'wght':

Collectively, we wanted to be practical, and as most of us were dealing with runtime implementations, our primary focus was on what things happen currently in actual practice --- meaning, shipping, static fonts intersecting with platforms and applications. Hence, fonts that ship with OS/2.usWeightClass values that are almost always from a limited set of values (100, 200, ...), and software such as HTML layout engines that compare CSS font-weight values with OS/2.usWeightClass values. We concluded that, from that practical perspective, it made sense to have the scale for 'wght' be the same scale as is used for OS/2.usWeightClass.

Now, while reps from MS, Apple, Adobe and Google were primarily involved in runtime implementations, we new that that perspective alone could have blinders. That is why we made a point very early on to bring some other representation into the working group: some font developers with a strong technical bent, and some tool developers. That led to inclusion of various people including Erik, Adam, George Seifert, John Hudson, Tom Rickner, Dave Opstad.

As we progressed, and as we came to consensus to use the OS/2.usWeightClass scale as the 'wght' scale, there was some acknowledgement that there may be challenges getting values to work well, particularly when re-engineering existing families as variable fonts. But we did not make it a priority for v1 to solve those problems since they were not yet well-enough understood. Nobody involved, including font / font tool developers, insisted that this was such a fundamental problem as to make v1 unviable without a solution for how to get from something more grounded in reality (e.g., actual stem thicknesses as per-mille of em) to OS/2.usWeightClass.

Rob McKaughan and I had some discussion last week with David Berlow about the parametric weight axis he uses in Amstelvar, and I know he feels strongly that 'wght' is broken. But if 'wght' is broken, that's because OS/2.usWeightClass is broken --- though not enough to have prevented people from creating fonts for the past 25+ years, and also not enough to start creating OT variable fonts with a 'wght' axis. As I explained to David, we can't "fix" the 'wght' axis without breaking compatibility with lots of stuff. But we certainly can look for solutions to problems for the future.

There are certainly options going forward that might be handled in a future OT version. Perhaps a new weight-related axis; perhaps some mechanism for synthetic or "meta" axes that users manipulate but that get applied to outline variation data only indirectly through some internal, more fundamental axes. One idea; there may be others. But these are ideas for the future, not things that will happen today, or likely in 2017.

**Comment by miguelsousa** [comment]
@behdad the glyphsLib change is not the problem. The problem is the spec's requirement to use 100,200... numbers for weight axis.

@PeterCon thanks for the insight. Glad to learn that this issue is on the working group's radar.

> Can we close this now?

Yes from me.

**Comment by brawer** [comment]
Ok, let's close it.
