### ISSUE TITLE
should we split combined outer-inner variation index in MVAR ValueRecords?

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#917]
In otData.py, the `MetricsValueRecord` structure has a `uint32` `VarIdx`, described as the "combined outer-inner variation index`.

However, in the otspec, the MVAR ValueRecord has two `uint16` indexes: i.e. an "outer" one to select item variation data subtable within the item variation store, and an "inner" one to select a delta-set row within an item variation data subtable:
https://www.microsoft.com/typography/otspec/mvar.htm

Splitting the uint32 into two distinct `uint16` values would also make the MVAR ttx a bit clearer to read.

**Comment by behdad** [comment]
There's also a TODO item in `varLib.builder:buildVarIdxMap` that reads:

```
# TODO Change VarIdxMap mapping to hold separate outer,inner indices
```

This is kind of a personal grief for me.  In my original design of ItemVariationStore, I made var indices be a uint32. Other people forced the design into separate outer/inner, whereas to me, that's internal implementation detail of the store and has no significance to the users of the store.

In particular, if we change our internal representation to use a tuple of two numbers, that helps nobody, but makes code dealing with them slower and more cumbersome.  There's a beauty in an integer that is lost in a tuple of two, specially when the parts have no semantic meaning whatsoever.

So, I personally like it this way. Ie. the VariationStoreBuilder stuff will continue using ints.  But we can change MVAR and VarIdxMap implementations if you prefer.  Like to hear your thoughts.

**Comment by behdad** [comment]
Ugh. github ate my comment. Typing again: personally I wanted the varstore API to be taking a uint32. Other people forced the outer/inner on it.  The separation is internal implementation detail of the store and holds no significance or semantic value outside of the store whatsoever.  Note that there's also a comment in `varLib.builder:buildVarIdxMap` about the same issue in that structure.

I personally like to keep it this way, at least in the VarStoreBuilder code.  It's just cleaner to use an int instead of tuple of two, specially when the tuple items don't have any significance to the user.  It's also faster...

If you insist, we can make the XML / MVAR / VarIdxMap reflect the separation... I personally suggest we keep it the way it is.  Note that this is not the first time we do this.  For version numbers, OT 1.8 has separate major/minor uint16's all over, whereas we read a uint32 version.

**Comment by behdad** [comment]
Hah, it had not eaten it after all...

**Comment by anthrotype** [comment]
Thanks for the explanation. No, I actually don't mind to leave it like that.

**Comment by moyogo** [comment]
Would it make sense to have those in hex?

**Comment by behdad** [comment]
> Would it make sense to have those in hex?

I thought about it.  But for them to be useful, one needs to convert individual components to integer to look up the data in VarStore.  And don't think anyone will do that often.
