### ISSUE TITLE
Improve BCP-47 matching in name table

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#930]
Currently name table thinks "fa-IR" cannot be encoded in Windows names, because the table only has a "fa" entry.  How should this be resolved?  Keep dropping last item in the langcode while there's no match?

**Comment by brawer** [comment]
Unicode defines an algorithm to minimize BCP47 language identifiers, with supporting data in CLDR. For example, this will transform all of `fa-IR`, `fa-Arab` and `fa-Arab-IR` to `fa`. The algorithm preserves some subtags; for example, `fa-Arab-AF` gets mapped to `fa-AF` because Iran (and not Afghanistan) is assumed to be the default region for the Farsi language.

ICU has implemented this algorithm, so we could call ICU. Alternatively, we could write a pure Python implementation somewhere in fonttools.misc. I think we should do the latter, because the algorithm isn’t all that complicated, and ICU would add a rather hefty dependency to fonttools.

I wouldn’t recommend blindly stripping language tags until we find a match in the old-style enums. The very point of BCP47 is to go beyond limited enums, and the reason for adding `ltag` to TrueType (respectively `name` format 1 to OpenType) was to support arbitrary BCP47 tags.

**Comment by behdad** [comment]
I agree a fontTools.bcp47 would be nice.

**Comment by brawer** [comment]
Here’s two independent Python implementations. They both seem a bit heavy to me, but I’m putting the links here for reference.

* https://github.com/OnroerendErfgoed/language-tags
* https://github.com/LuminosoInsight/langcodes/

**Comment by anthrotype** [comment]
I see that varLib's fvar builder is not using that `addMultilingualNames` method yet, and only adds English names (via `addNames` method). For the time being, couldn't we just use the hard-coded mappings we already have, or do must we wait for full support for BCP-47 tags normalization?

**Comment by brawer** [comment]
Agree, I think the current function is OK for now. It can always be improved later.

**Comment by anthrotype** [comment]
The `addMultilingualNames` method adds Macintosh (platform 1) nameIDs only when it can't find a match for a given BCP-47 tag among Windows (platform 3) language ids.

The `addNames` method currently used by default adds both Mac and Windows (English) nameIDs.

If we un-comment that line and use the former instead of the latter, that means we would no longer add both sets of nameIDs for fvar axes names, but only one set (most often, the Windows ones).

Would that be ok? @robmck-ms reported an issue with OSX requiring platformID=1 names for variable fonts: https://github.com/fonttools/fonttools/issues/683

Is it only the `postScriptNameID` which OSX require as single-byte encoding, or also  `axisNameID` and `subfamilyNameID`?
https://github.com/fonttools/fonttools/issues/756

**Comment by brawer** [comment]
Uhm, why not try and see what works?

**Comment by justvanrossum** [comment]
> The addMultilingualNames method adds Macintosh (platform 1) nameIDs only when it can't find a match for a given BCP-47 tag among Windows (platform 3) language ids.

In the context of #683 I think `addMultilingualNames` should just always add platform 1 versions. Or make it optional via a flag in the method signature. I don't understand what sense it makes to only add them if a windows version can't be made.

As it stands, `addName` by default adds both platform 1 and platform 3 versions, but `addMultilingualNames` only adds platform 3 (in the usual case), which appears inconsistent.

**Comment by justvanrossum** [comment]
I can make a PR.

**Comment by anthrotype** [comment]
thanks!

**Comment by brawer** [comment]
Here’s the upstream source for the likelySubtags data: https://www.unicode.org/repos/cldr/trunk/common/supplemental/likelySubtags.xml

**Comment by behdad** [comment]
> Here’s the upstream source for the likelySubtags data: https://www.unicode.org/repos/cldr/trunk/common/supplemental/likelySubtags.xml

I think we want this in HarfBuzz as well.  Maybe something @dscorbett can look into?

**Comment by brawer** [comment]
And here’s the upstream source for aliasing deprecated tags (`iw` → `he`), overlong tags (`eng` → `en`), etc. Note that some items such as the country code `SU` for the Soviet Union have multiple replacements; it’s probably reasonable to use the first item in the list (in this case, alias `SU` to Russia `RU`).

https://www.unicode.org/repos/cldr/trunk/common/supplemental/supplementalMetadata.xml

Note that ISO 639 and therefore also the IANA language subtag registry have a concept of macro-languages. When ICU sees a language subtag `arb`, it aliases the tag to `ar` (and likewise, `cmn` to `zh`) because of the `<languageAlias reason="macrolanguage">` elements in the CLDR supplementalMetadata file. Go’s `x.text` library, on the other hand, preserves the input code and special-cases macrolanguages at matching time. The reason behind ICU’s behavior is that every programmer on the planet means Mandarin whey they say “Chinese”, so it’s (in ICU’s perspective) best to alias `cmn` to `zh`. Personally I’d recommend following ICU, i.e. treat macrolanguage aliases in CLDR like all the other aliases, simply because ICU is more widely used than Go. But no strong opinions, just wanted to point out this quirk.

**Comment by behdad** [comment]
The likelySubtags map Latin in Iran to Turkmen.  In reality, it would most probably be just Latin transcription of Persian.  I assume other scripts / countries have same issue...

**Comment by behdad** [comment]
But that's something for CLDR, not us...

**Comment by brawer** [comment]
Bug reports welcome: https://unicode.org/cldr/trac/newticket

**Comment by brawer** [comment]
Also relevant: http://unicode.org/reports/tr35/#Unicode_Language_and_Locale_Identifiers
