### ISSUE TITLE
Fire!

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#938]
This was brought to my attention:

  https://github.com/google/python-fire/blob/master/doc/guide.md

I'd love to see us use some of that to make a lot more functionality of fontTools available to commandline without much effort.  I also understand that this is a hack, so don't want to go overboard!

**Comment by anthrotype** [comment]
Yeah, `fire` is nice, and I like how it simplifies writing CLI. With argparse I have to go through the documentation every time I write even a simple main() with a few options (or copy/paste from other scripts when I feel lazy...).

However, I don't think fire is a viable option for fonttools right now, because of its hard dependency on IPython, which in turn drags in a huge list of dependencies... 21 new packages get installed when I `pip install ipython` in a fresh virtualenv on mac (on linux or windows they may be different because ipython also has platform-specific dependencies): 

appdirs, appnope, backports.shutil-get-terminal-size, decorator, enum34, ipython, ipython-genutils, packaging, pathlib2, pexpect, pickleshare, prompt-toolkit, ptyprocess, Pygments, pyparsing, scandir, setuptools, simplegeneric, six, traitlets, wcwidth.

To be clear, I do love ipython, it's my default python shell and the very first package I pip install in all new environments I make. And I am usually the one who is not afraid of python packaging and wishes to add new dependencies instead of reinventing the wheel. But in the case of ipython, I think it would be too much for a library like fonttools.

The python fire developers are discussing about removing the ipython dependency and making it optional here: https://github.com/google/python-fire/issues/7

Maybe we can re-assess once this has happened, and in the mean time we familiarise with the tool or take inspiration from it.

**Comment by behdad** [comment]
Sure.  Indeed I just wanted to share it for now so we can experiment with it.

**Comment by dbieber** [comment]
Heads up that we just closed google/python-fire#7 and `ipython` is no longer a required dependency of fire. Now fire's only dependency is `six`. This will reach pypi with our next release (probably in 1-2 weeks).

**Comment by anthrotype** [comment]
@dbieber that's good, thank you for letting us know!

**Comment by anthrotype** [comment]
the ipython dependency was removed with https://github.com/google/python-fire/releases/tag/v0.1.2
