### ISSUE TITLE
cffLib cleanups re CFF2

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#955]
A few things that come to my mind while having a quick look at the CFF2 code:

In psCharString:
- I'm not convinced that we should separate CFF2CharString from T2CharString, and likewise about decompiler and outline extractors.  The duplication of classes makes it harder to convert between the two, whereas in reality a shared class can do.  We can decide where we want to enforce the distinction, if at all.  For example, endchar and return, while invalid for CFF2, are harmless during execution.

- In CFF2CharString() I see there's a `check_program()` that checks for 'seac'.  In general, I like the explicit validation approach via something like a `check_program()`.  At the same time, I don't think enchar / return should automatically be dropped during compile.  If anything, it should raise an error.

- I don't understand why CFF2SubrCharString() exists.

- In cffLib itself, same thing: I like to see shared classes that take an argument either in their constructor, or their compile() / decompile().

- Some of the branches do not make much sense:
```
                        if not isCFF2:
                                subrCharStringClass = psCharStrings.T2CharString
                                if not hasattr(self, "GlobalSubrs"):
                                        self.GlobalSubrs = GlobalSubrsIndex()
                        elif isCFF2:
                                subrCharStringClass = psCharStrings.CFF2SubrCharString
                                if not hasattr(self, "GlobalSubrs"):
                                        self.GlobalSubrs = GlobalSubrsIndex2()
                        else:
                                assert False, "Unsupported CFF format"
```
The assert can never reach :).

That's mostly it.  The CFF code is not the easiest to follow, mostly because CFF table is complicated.  I think the duplication of the classes just makes it harder to follow, not easier.  But that might be just me.

Thanks @readroberts for working on these in advance!

**Comment by behdad** [comment]
Oh, and while at it, would be great if you can make smaller commits that cleanup / refactor small chunks of code, as opposed to one big change.

**Comment by miguelsousa** [comment]
[C_F_F__2.py](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/C_F_F__2.py) can be greatly simplified if it subclasses [`table_C_F_F_ `](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/C_F_F_.py#L7), can't it?

**Comment by behdad** [comment]
> C_F_F__2.py can be greatly simplified if it subclasses table_C_F_F_, can't it?

Sure, that too.  I wasn't even looking at that...

**Comment by readroberts** [comment]
This all makes sense. I will move the code., in small commit chunks,  to having just a single set of classes for T2 and CFF2. These will need an 'isCFF2' field to use in if…else to choose between CFF2 and CFF1 logic.

Since the CFF2 operator codes are a superset of the CFF1 operator codes, I also propose just having one set of operator codes. We can then enforce what's allowed in CFF2 or CFF1 depending on the  output target.

I had originally intended to reflect the structural differences between CFF2 and CFF1 in the decompiled object data tree and in the XML.  Having seen the comments about this library, and had some experience with using the library to build CFF2 fonts, I now think that it makes more sense to use CFF1 structures throughout, in both the data object tree and in the XML, with new fields and objects added to hold the new CFF2 data. The structural differences would then be expressed only when compiling/decompiling from binary data.

- Read

**Comment by behdad** [comment]
Yes, I agree that while CFF2 simplified a few things, it's better to keep the structure but enforce all differences during compile/decompile.  The latter will guarantee no bad fonts will go out of our code by developer mistake...

**Comment by behdad** [comment]
A side benefit, of course, is that subsetter, subroutinizer, etc can be adapted much quicker.
