### ISSUE TITLE
Is there a documentation or tutorial?

### ISSUE THREAD

**Issue by zyu47** [fonttools/fonttools#997]
Cannot find it anywhere. It is hard to understand the functions without documentations.

**Comment by Arno-Enslin** [comment]
I think, that is a question for the [fonttools forum.](https://groups.google.com/forum/#!forum/fonttools)

You can call the help of the scripts and test their functions by yourself. I am on Windows and I control the AFDKO and the FontTools with the help of batch files. The command for the help of the subset script is for example:

`(path to) python.exe (contained in the AFDKO) (path to) subset\__init__.py -h`

And the suffices to make use of the script. Maybe not in the first attempt, but after a few tries and errors.

A tutorial would be fine, but I assume, you could write a few hundred of pages about all the functions. And probably the problem is, that it is hard to write such a tutorial, if you are user only, but not developer. Writing a tutorial would be very time intensive.

**Comment by anthrotype** [comment]
I hear you @zyu47. The problem is writing and maintaining documentation is very time consuming, and fonttools is more a library for other developers (who can inspect the code) than an end-user tool.
But even for developers, it would still be nice if all the functions and classes that are meant to be public had a docstrings explaining what they do, what the type of arguments, return values and possible exceptions.
Now that @gferreira added support for automatically building documentation from docstrings using sphinx, this shouldn't be too hard to do, again just time consuming.
We would be happy to accept pull requests in that direction though. :)

**Comment by Arno-Enslin** [comment]
@ anthrotype

Whenever I read, that a type designer thinks about buying DTL OTMaster, I recommend the fonttools instead, because in my opinion they are more useful and they are free of charge. And I naturally hope, that they make a donation to the project. The sacrifice of a GUI is a question of accustoming only. But if you are not a code developer you need at least a small documentation, an entry point. For me the batch scripts and the PDF, that are contained in the AFDKO, were the entry point. And the internal help options of some scripts. (Unfortunately not all scripts have such an internal help. In case of the pen scripts for example, I am also overchallenged.) If the fonttools are primary a library for code developers, but not for type designers, I wonder, what the developers are doing with the fonttools. Aren't type designers the group, which could profit the most from the fonttools? And wouldn't it be a chance to improve the fonttools, if the number of those users would increase. That could result in more donations.

I am even not type designer, but I have redirected the payment for help to TTX a few times. (Some designers did insist in payment, although I had helped just for interest and fun.)

**Comment by anthrotype** [comment]
Thanks Arno

> I wonder, what the developers are doing with the fonttools

other tools and scripts.

> wouldn't it be a chance to improve the fonttools, if the number of those users would increase.

Yes, though I suspect the requests for help/support would also increase.

Fonttools doesn't need "payments"; _time_ is the best "donation" we could get. :)

**Comment by gferreira** [comment]
@anthrotype I would happy to dedicate more time to the documentation if this work were funded.

Also, it would be great to integrate the docs to [ReadTheDocs](http://readthedocs.org/), so people can read it online.

**Comment by khaledhosny** [comment]
Nothing actionable here, documentation issues are already tracked elsewhere.

**Comment by bjmgeek** [comment]
@khaledhosny Where are documentation issues tracked?
